/// Module overview (comment coverage pass).
/// comment-coverage: module overview (batch).
///
/// Analyzer-backed tests for `pubspec_lock_resolver_test` (pubspec lock resolver).
///
/// Uses `// LINT` markers and `example/` fixtures per CONTRIBUTING.md.
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:saropa_lints/src/config/pubspec_lock_resolver.dart';
import 'package:test/test.dart';

// pubspec_lock_resolver: path resolution from pubspec.lock package entries.

const _sampleLock = r'''
# Generated by pub
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  drift:
    dependency: "direct main"
    description:
      name: drift
      url: "https://pub.dev"
    source: hosted
    version: "2.20.0"
  foo_bar:
    dependency: direct
    description:
      path: ".."
      relative: true
    source: path
    version: "0.1.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''';

void main() {
  group('parsePubspecLockPackageVersions', () {
    test('extracts hosted and path package versions', () {
      final m = parsePubspecLockPackageVersions(_sampleLock);
      expect(m['collection'], '1.19.1');
      expect(m['foo_bar'], '0.1.0');
    });

    test('returns empty when packages section missing', () {
      expect(parsePubspecLockPackageVersions('name: x\n'), isEmpty);
    });
  });

  group('parsePubspecLockDependencyKinds', () {
    test('distinguishes direct, quoted direct main, and transitive', () {
      final m = parsePubspecLockDependencyKinds(_sampleLock);
      expect(m['collection'], 'transitive');
      expect(m['drift'], 'direct main');
      expect(m['foo_bar'], 'direct');
    });

    test('returns empty when packages section missing', () {
      expect(parsePubspecLockDependencyKinds('name: x\n'), isEmpty);
    });
  });

  group('isDirectDependency', () {
    test('true for direct, false for transitive, null for unknown', () {
      final dir = Directory.systemTemp.createTempSync('saropa_lock_test');
      try {
        File(p.join(dir.path, 'pubspec.lock')).writeAsStringSync(_sampleLock);
        clearPubspecLockResolverCacheForTests();
        expect(isDirectDependency(dir.path, 'drift'), isTrue);
        expect(isDirectDependency(dir.path, 'foo_bar'), isTrue);
        expect(isDirectDependency(dir.path, 'collection'), isFalse);
        // Absent package: unknown, callers treat null as not-direct (§7.3).
        expect(isDirectDependency(dir.path, 'not_present'), isNull);
      } finally {
        clearPubspecLockResolverCacheForTests();
        dir.deleteSync(recursive: true);
      }
    });
  });

  group('readResolvedPackageVersion', () {
    test('reads collection from real self_check lockfile', () {
      final root = p.join('self_check');
      if (!Directory(root).existsSync()) {
        return;
      }
      clearPubspecLockResolverCacheForTests();
      final v = readResolvedPackageVersion(root, 'collection');
      expect(v, isNotNull);
      expect(v!.isNotEmpty, isTrue);
    });
  });
}
