import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:saropa_lints/src/config/pubspec_lock_resolver.dart';
import 'package:test/test.dart';

const _sampleLock = r'''
# Generated by pub
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  foo_bar:
    dependency: direct
    description:
      path: ".."
      relative: true
    source: path
    version: "0.1.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''';

void main() {
  group('parsePubspecLockPackageVersions', () {
    test('extracts hosted and path package versions', () {
      final m = parsePubspecLockPackageVersions(_sampleLock);
      expect(m['collection'], '1.19.1');
      expect(m['foo_bar'], '0.1.0');
    });

    test('returns empty when packages section missing', () {
      expect(parsePubspecLockPackageVersions('name: x\n'), isEmpty);
    });
  });

  group('readResolvedPackageVersion', () {
    test('reads collection from real self_check lockfile', () {
      final root = p.join('self_check');
      if (!Directory(root).existsSync()) {
        return;
      }
      clearPubspecLockResolverCacheForTests();
      final v = readResolvedPackageVersion(root, 'collection');
      expect(v, isNotNull);
      expect(v!.isNotEmpty, isTrue);
    });
  });
}
