/**
 * Command catalog entries: Package Vibrancy and its filter/registry sub-commands.
 *
 * Part of the command catalog registry, split out of commandCatalogRegistry.ts
 * so the large entry literal is not one 1300-line file. The registry composes
 * this array into `catalogEntries`. Each entry's `category` field (not its file
 * or array position) drives grouping in the catalog UI.
 */

import { CatalogEntry } from './commandCatalogTypes';

export const vibrancyCatalogEntries: readonly CatalogEntry[] = [

  // ── Package Vibrancy ─────────────────────────────────────────────────────

  {
    command: 'saropaLints.packageVibrancy.scan',
    title: 'Scan Packages',
    description: 'Fetch health data for all dependencies in pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'refresh',
  },
  {
    command: 'saropaLints.packageVibrancy.rescan',
    title: 'Rescan Packages (Fresh)',
    description: 'Clear the per-package pub.dev cache and re-fetch health data — use when the report shows stale versions.',
    category: 'Package Vibrancy',
    icon: 'refresh',
  },
  {
    command: 'saropaLints.packageVibrancy.openOtherProject',
    title: 'Scan Another Project...',
    description: 'Open a pubspec.yaml from another project in a new VS Code window to run a vibrancy scan there.',
    category: 'Package Vibrancy',
    icon: 'folder-opened',
  },
  {
    command: 'saropaLints.packageVibrancy.showReport',
    title: 'Open Package Dashboard',
    description: 'Open the Package Dashboard in an editor tab with charts and dependency details.',
    category: 'Package Vibrancy',
    icon: 'graph',
  },
  {
    command: 'saropaLints.packageVibrancy.focus',
    title: 'Open Package Dashboard (compat)',
    description:
      'Backward-compatible handler for old `{viewId}.focus` calls on the removed Package Vibrancy sidebar; opens the Package Dashboard tab.',
    category: 'Package Vibrancy',
    icon: 'graph',
    internal: true,
  },
  {
    command: 'saropaLints.focusPackageVibrancyPackages',
    title: 'Focus Package Vibrancy Tree',
    description: 'Focus the Package Vibrancy sidebar tree (dependency list).',
    category: 'Package Vibrancy',
    icon: 'package',
  },
  {
    command: 'saropaLints.openProjectVibrancyReport',
    title: 'Open Code Health Dashboard',
    description:
      'Run a Code Health scan (LCOV + analyzer) using Code Health settings and open the dashboard.',
    category: 'Code Health',
    icon: 'graph',
  },
  {
    command: 'saropaLints.openProjectHealthDashboard',
    title: 'Open Saropa Project Map Dashboard',
    description:
      'Project-wide size map, dead-weight, complexity, git churn, and hot spots (size treemap + churn×complexity charts).',
    category: 'Code Health',
    icon: 'flame',
  },
  {
    command: 'saropaLints.openDashboards',
    title: 'Open Saropa Dashboards (Project Map + Code Health)',
    description:
      'Consolidated page showing the Project Map and Code Health dashboards side by side, each with its full interactive content.',
    category: 'Code Health',
    icon: 'dashboard',
  },
  {
    command: 'saropaLints.toggleProjectMapCodeLensHeat',
    title: 'Toggle Saropa Project Map Heat CodeLens (in-editor)',
    description:
      'Turn the in-editor per-function complexity CodeLens on or off (off by default to avoid clutter).',
    category: 'Code Health',
    icon: 'flame',
  },
  {
    command: 'saropaLints.openProjectVibrancySettings',
    title: 'Open Code Health Settings',
    // Setting key prefix is still `saropaLints.projectVibrancy` from the
    // pre-rename Project Vibrancy era — stays so existing user settings.json
    // entries keep working. The Settings filter passes that exact prefix.
    description: 'Open Settings filtered to saropaLints.projectVibrancy (LCOV path and quality gates).',
    category: 'Code Health',
    icon: 'settings-gear',
  },
  {
    command: 'saropaLints.packageVibrancy.clearCache',
    title: 'Clear Cache',
    description: 'Delete cached pub.dev data so the next scan fetches fresh results.',
    category: 'Package Vibrancy',
    icon: 'trash',
  },
  {
    command: 'saropaLints.packageVibrancy.exportReport',
    title: 'Export Report',
    description: 'Save the vibrancy report to a file (HTML or JSON).',
    category: 'Package Vibrancy',
    icon: 'export',
  },
  {
    command: 'saropaLints.packageVibrancy.browseKnownIssues',
    title: 'Browse Known Issues',
    description: 'Open the known issues database for common package problems.',
    category: 'Package Vibrancy',
    icon: 'library',
  },
  {
    command: 'saropaLints.packageVibrancy.exportSbom',
    title: 'Export SBOM',
    description: 'Generate a CycloneDX Software Bill of Materials for dependencies.',
    category: 'Package Vibrancy',
    icon: 'shield',
  },
  {
    command: 'saropaLints.packageVibrancy.annotatePubspec',
    title: 'Annotate Dependencies',
    description: 'Add inline comments to pubspec.yaml showing package health info.',
    category: 'Package Vibrancy',
    icon: 'note',
  },
  {
    command: 'saropaLints.packageVibrancy.goToPackage',
    title: 'Go to pubspec.yaml',
    description: 'Jump to a package declaration in pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'go-to-file',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.goToLine',
    title: 'Go to Line in pubspec.yaml',
    description: 'Jump to a specific line in pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'go-to-file',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.openOnPubDev',
    title: 'Open on pub.dev',
    description: 'Open the selected package page on pub.dev in the browser.',
    category: 'Package Vibrancy',
    icon: 'link-external',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.showChangelog',
    title: 'Open Changelog on pub.dev',
    description: 'Open the package changelog on pub.dev in the browser.',
    category: 'Package Vibrancy',
    icon: 'book',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.copyAsJson',
    title: 'Copy Package as JSON',
    description: 'Copy the selected package vibrancy data to the clipboard.',
    category: 'Package Vibrancy',
    icon: 'clippy',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.upgradeAndTest',
    title: 'Upgrade & Test',
    description: 'Upgrade a dependency and run tests to verify compatibility.',
    category: 'Package Vibrancy',
    icon: 'beaker',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.suppressPackage',
    title: 'Suppress Package',
    description: 'Hide a specific package from vibrancy diagnostics.',
    category: 'Package Vibrancy',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.unsuppressPackage',
    title: 'Unsuppress Package',
    description: 'Restore a suppressed package to vibrancy diagnostics.',
    category: 'Package Vibrancy',
    icon: 'eye',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.openUrl',
    title: 'Open Link',
    description: 'Open a URL from package metadata in the browser.',
    category: 'Package Vibrancy',
    icon: 'link-external',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.commentOutUnused',
    title: 'Comment Out Unused Dependency',
    description: 'Comment out an unused dependency in pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'comment',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.deleteUnused',
    title: 'Delete Unused Dependency',
    description: 'Remove an unused dependency from pubspec.yaml (with backup).',
    category: 'Package Vibrancy',
    icon: 'trash',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.planUpgrades',
    title: 'Plan & Execute Upgrades',
    description: 'Interactively plan and execute dependency version upgrades.',
    category: 'Package Vibrancy',
    icon: 'rocket',
  },
  {
    command: 'saropaLints.packageVibrancy.goToOverride',
    title: 'Go to Dependency Override',
    description: 'Jump to a dependency_overrides entry in pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'go-to-file',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.suppressPackageByName',
    title: 'Suppress Package Diagnostics',
    description: 'Type a package name to suppress its vibrancy diagnostics.',
    category: 'Package Vibrancy',
    icon: 'eye-closed',
  },
  {
    command: 'saropaLints.packageVibrancy.suppressByCategory',
    title: 'Suppress by Category',
    description: 'Suppress all vibrancy diagnostics of a given category.',
    category: 'Package Vibrancy',
    icon: 'filter',
  },
  {
    command: 'saropaLints.packageVibrancy.suppressAllProblems',
    title: 'Suppress All Unhealthy Packages',
    description: 'Suppress diagnostics for every package currently flagged.',
    category: 'Package Vibrancy',
    icon: 'eye-closed',
  },
  {
    command: 'saropaLints.packageVibrancy.unsuppressAll',
    title: 'Unsuppress All Packages',
    description: 'Restore all suppressed packages to vibrancy diagnostics.',
    category: 'Package Vibrancy',
    icon: 'eye',
  },
  {
    command: 'saropaLints.packageVibrancy.sortDependencies',
    title: 'Sort Dependencies Alphabetically',
    description: 'Reorder dependencies in pubspec.yaml alphabetically.',
    category: 'Package Vibrancy',
    icon: 'list-ordered',
  },
  {
    command: 'saropaLints.packageVibrancy.showCodeLens',
    title: 'Show Vibrancy Badges',
    description: 'Display code lens badges above dependencies in pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'eye',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.hideCodeLens',
    title: 'Hide Vibrancy Badges',
    description: 'Remove code lens badges from pubspec.yaml.',
    category: 'Package Vibrancy',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.toggleCodeLens',
    title: 'Toggle Badges',
    description: 'Toggle code lens vibrancy badges on or off.',
    category: 'Package Vibrancy',
    icon: 'eye',
  },
  {
    command: 'saropaLints.packageVibrancy.focusDetails',
    title: 'Focus Package Details',
    description: 'Open the package details sidebar panel.',
    category: 'Package Vibrancy',
    icon: 'preview',
  },
  {
    command: 'saropaLints.packageVibrancy.logDetails',
    title: 'Log to Output',
    description: 'Print selected package details to the output channel.',
    category: 'Package Vibrancy',
    icon: 'output',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.logAllDetails',
    title: 'Log All Package Details',
    description: 'Print all scanned package details to the output channel.',
    category: 'Package Vibrancy',
    icon: 'output',
  },
  {
    command: 'saropaLints.packageVibrancy.updateFromCodeLens',
    title: 'Update Package Version',
    description: 'Update a package version from a code lens badge click.',
    category: 'Package Vibrancy',
    icon: 'arrow-up',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.focusPackageInTree',
    title: 'Show Package in Sidebar',
    description:
      'Focus Package Vibrancy in the activity bar, reveal this dependency, and open package details when available.',
    category: 'Package Vibrancy',
    icon: 'list-tree',
    internal: true,
  },
  {
    command: 'saropaLints.checkForUpdatesNow',
    title: 'Check for Package Updates Now',
    description: 'Re-check pub.dev for a newer saropa_lints version, re-surfacing the upgrade notification even after it was dismissed.',
    category: 'Package Vibrancy — Updates',
    icon: 'refresh',
  },
  {
    command: 'saropaLints.packageVibrancy.updateToLatest',
    title: 'Update to Latest',
    description: 'Update a selected dependency to its latest stable version.',
    category: 'Package Vibrancy — Updates',
    icon: 'arrow-up',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.updateAllLatest',
    title: 'Update All Dependencies (Latest)',
    description: 'Update every dependency to its latest stable version.',
    category: 'Package Vibrancy — Updates',
    icon: 'cloud-download',
  },
  {
    command: 'saropaLints.packageVibrancy.updateAllMajor',
    title: 'Update All Dependencies (Major Only)',
    description: 'Update every dependency that has a new major version available.',
    category: 'Package Vibrancy — Updates',
    icon: 'arrow-up',
  },
  {
    command: 'saropaLints.packageVibrancy.updateAllMinor',
    title: 'Update All Dependencies (Minor Only)',
    description: 'Update every dependency that has a new minor version available.',
    category: 'Package Vibrancy — Updates',
    icon: 'arrow-up',
  },
  {
    command: 'saropaLints.packageVibrancy.updateAllPatch',
    title: 'Update All Dependencies (Patch Only)',
    description: 'Update every dependency that has a new patch version available.',
    category: 'Package Vibrancy — Updates',
    icon: 'arrow-up',
  },
  {
    command: 'saropaLints.packageVibrancy.showPrereleases',
    title: 'Show Prerelease Versions',
    description: 'Include prerelease versions in CodeLens and Package Vibrancy.',
    category: 'Package Vibrancy — Updates',
    icon: 'beaker',
  },
  {
    command: 'saropaLints.packageVibrancy.hidePrereleases',
    title: 'Hide Prerelease Versions',
    description: 'Exclude prerelease versions from CodeLens and Package Vibrancy.',
    category: 'Package Vibrancy — Updates',
    icon: 'eye-closed',
  },
  {
    command: 'saropaLints.packageVibrancy.updateToPrerelease',
    title: 'Update to Prerelease',
    description: 'Update a selected dependency to its latest prerelease version.',
    category: 'Package Vibrancy — Updates',
    icon: 'beaker',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.comparePackages',
    title: 'Compare Packages',
    description: 'Open a side-by-side comparison of two packages.',
    category: 'Package Vibrancy',
    icon: 'diff',
  },
  {
    command: 'saropaLints.packageVibrancy.compareSelected',
    title: 'Compare Selected Packages',
    description: 'Compare packages after multi-selecting them in Package Vibrancy.',
    category: 'Package Vibrancy',
    icon: 'diff',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.copyHoverToClipboard',
    title: 'Copy Package Info',
    description: 'Copy package hover information to the clipboard.',
    category: 'Package Vibrancy',
    icon: 'clippy',
    internal: true,
  },
  {
    command: 'saropaLints.packageVibrancy.showPackagePanel',
    title: 'Show Package Details',
    description: 'Open the package details panel for a specific dependency.',
    category: 'Package Vibrancy',
    icon: 'preview',
  },
  {
    command: 'saropaLints.packageVibrancy.generateCiConfig',
    title: 'Generate CI Pipeline',
    description: 'Create a CI pipeline configuration for dependency monitoring.',
    category: 'Package Vibrancy',
    icon: 'server-process',
  },
  {
    command: 'saropaLints.packageVibrancy.openSourceFolder',
    title: 'Open Source Folder',
    description: 'Open the local source folder for a cached package dependency.',
    category: 'Package Vibrancy',
    icon: 'folder-opened',
    internal: true,
  },

  // ── Package Vibrancy — Filters ───────────────────────────────────────────

  {
    command: 'saropaLints.packageVibrancy.search',
    title: 'Search',
    description: 'Filter packages in Package Vibrancy by text.',
    category: 'Package Vibrancy — Filters',
    icon: 'search',
  },
  {
    command: 'saropaLints.packageVibrancy.filterBySeverity',
    title: 'Filter by Severity',
    description: 'Show only packages with a specific severity level.',
    category: 'Package Vibrancy — Filters',
    icon: 'filter',
  },
  {
    command: 'saropaLints.packageVibrancy.filterByProblemType',
    title: 'Filter by Problem Type',
    description: 'Show only packages with a specific type of problem.',
    category: 'Package Vibrancy — Filters',
    icon: 'filter',
  },
  {
    command: 'saropaLints.packageVibrancy.filterByCategory',
    title: 'Filter by Health',
    description: 'Show only packages in a specific health category.',
    category: 'Package Vibrancy — Filters',
    icon: 'filter',
  },
  {
    command: 'saropaLints.packageVibrancy.filterBySection',
    title: 'Filter by Section',
    description: 'Show only packages in a specific pubspec section.',
    category: 'Package Vibrancy — Filters',
    icon: 'filter',
  },
  {
    command: 'saropaLints.packageVibrancy.showProblemsOnly',
    title: 'Show Problems Only',
    description: 'Hide healthy packages and show only those with problems.',
    category: 'Package Vibrancy — Filters',
    icon: 'warning',
  },
  {
    command: 'saropaLints.packageVibrancy.clearFilters',
    title: 'Clear Filters',
    description: 'Remove all package vibrancy filters.',
    category: 'Package Vibrancy — Filters',
    icon: 'clear-all',
  },
  {
    command: 'saropaLints.packageVibrancy.expandAll',
    title: 'Expand All',
    description: 'Expand every row in Package Vibrancy (activity bar).',
    category: 'Package Vibrancy — Filters',
    icon: 'expand-all',
  },

  // ── Package Vibrancy — Registries ────────────────────────────────────────

  {
    command: 'saropaLints.packageVibrancy.addRegistryAuth',
    title: 'Add Registry Authentication',
    description: 'Configure credentials for a private package registry.',
    category: 'Package Vibrancy — Registries',
    icon: 'key',
  },
  {
    command: 'saropaLints.packageVibrancy.removeRegistryAuth',
    title: 'Remove Registry Authentication',
    description: 'Delete credentials for a private package registry.',
    category: 'Package Vibrancy — Registries',
    icon: 'trash',
  },
  {
    command: 'saropaLints.packageVibrancy.listRegistries',
    title: 'List Configured Registries',
    description: 'Show all configured private package registries.',
    category: 'Package Vibrancy — Registries',
    icon: 'list-unordered',
  },
];
