/**
 * Command catalog entries: project setup, analysis, violations, rules, security posture, and reporting.
 *
 * Part of the command catalog registry, split out of commandCatalogRegistry.ts
 * so the large entry literal is not one 1300-line file. The registry composes
 * this array into `catalogEntries`. Each entry's `category` field (not its file
 * or array position) drives grouping in the catalog UI.
 */

import { CatalogEntry } from './commandCatalogTypes';

export const projectCatalogEntries: readonly CatalogEntry[] = [

  // ── Setup & Configuration ────────────────────────────────────────────────

  {
    command: 'saropaLints.enable',
    title: 'Set Up Project',
    description: 'Add saropa_lints to pubspec.yaml and create analysis_options.yaml.',
    category: 'Setup & Configuration',
    icon: 'package',
  },
  {
    command: 'saropaLints.disable',
    title: 'Turn Off Lint Integration',
    description: 'Remove saropa_lints integration from the current project.',
    category: 'Setup & Configuration',
    icon: 'circle-slash',
  },
  {
    command: 'saropaLints.initializeConfig',
    title: 'Initialize / Update Analysis Options',
    description: 'Create or refresh the analysis_options.yaml configuration file.',
    category: 'Setup & Configuration',
    icon: 'gear',
  },
  {
    command: 'saropaLints.enableRulePack',
    title: 'Enable Rule Pack',
    description: 'Enable a rule pack for a package in your pubspec, from a Suggestions item.',
    category: 'Setup & Configuration',
    icon: 'extensions',
    internal: true,
  },
  {
    command: 'saropaLints.openConfig',
    title: 'Open Analysis Options',
    description: 'Open the analysis_options.yaml file in the editor.',
    category: 'Setup & Configuration',
    icon: 'go-to-file',
  },
  {
    command: 'saropaLints.openPubspec',
    title: 'Open pubspec.yaml',
    description: 'Open the project root pubspec.yaml in the editor.',
    category: 'Setup & Configuration',
    icon: 'go-to-file',
  },
  {
    command: 'saropaLints.toggleRunAnalysisAfterConfigChange',
    title: 'Toggle Run Analysis After Config Change',
    description: 'Flip the saropaLints.runAnalysisAfterConfigChange setting in one click.',
    category: 'Setup & Configuration',
    icon: 'sync',
  },
  {
    command: 'saropaLints.toggleRunAnalysisAfterDependencyChange',
    title: 'Toggle Run Analysis After Dependency Change',
    description: 'Flip the saropaLints.runAnalysisAfterDependencyChange setting in one click. When on, pubspec.lock changes auto-trigger analysis after a 10-second debounce.',
    category: 'Setup & Configuration',
    icon: 'sync',
  },
  {
    command: 'saropaLints.toggleTodosAndHacksScanner',
    title: 'Toggle TODO/HACK Workspace Scanner',
    description:
      'Enable or disable the saropa file-system TODO/HACK scanner (saropaLints.todosAndHacks.workspaceScanEnabled). When on, the Findings Dashboard and sidebar surface open TODO/HACK markers across the workspace.',
    category: 'Setup & Configuration',
    icon: 'list-tree',
  },
  {
    command: 'saropaLints.pickUiLanguage',
    title: 'Pick UI Language',
    description:
      'Choose the extension UI language from installed locale bundles or follow VS Code display language.',
    category: 'Setup & Configuration',
    icon: 'globe',
  },
  {
    command: 'saropaLints.openConfigDashboard',
    title: 'Open Lints Config',
    description: 'Open the Lints Config dashboard in an editor tab for tiers, packs, and config guidance.',
    category: 'Setup & Configuration',
    icon: 'dashboard',
  },
  {
    command: 'saropaLints.openViolationsWideReport',
    title: 'Open Findings Dashboard',
    description:
      'Open the Findings Dashboard in an editor tab (violations, TODOs, Drift Advisor snapshot).',
    category: 'Setup & Configuration',
    icon: 'warning',
  },
  {
    command: 'saropaLints.openConsolidatedDashboard',
    title: 'Open Dashboard',
    description:
      'Open the consolidated dashboard: live findings grouped by rule and ranked by severity, with the holistic grade. Reads diagnostics live (zero analysis) and updates as you edit.',
    category: 'Setup & Configuration',
    icon: 'dashboard',
  },
  {
    command: 'saropaLints.revealFindingsDashboard',
    title: 'Open Findings Dashboard (preserve filters)',
    description:
      'Same editor tab as Open Findings Dashboard; preserves current filters (does not clear first).',
    category: 'Setup & Configuration',
    icon: 'warning',
  },
  {
    command: 'saropaLints.openPackageVibrancy',
    title: 'Open Package Vibrancy',
    description:
      'Focus the Package Vibrancy activity-bar section and run a scan when no dependency results are loaded yet.',
    category: 'Setup & Configuration',
    icon: 'package',
  },
  {
    command: 'saropaLints.repairConfig',
    title: 'Repair Analysis Options',
    description: 'Detect and fix problems in the analysis_options.yaml file.',
    category: 'Setup & Configuration',
    icon: 'tools',
  },
  {
    command: 'saropaLints.setTier',
    title: 'Set Tier',
    description: 'Choose which rule tier to enforce (Essential through Pedantic).',
    category: 'Setup & Configuration',
    icon: 'layers',
  },
  {
    command: 'saropaLints.emitCompositePluginScaffold',
    title: 'Composite Analyzer Plugin (scaffold)',
    description:
      'Generate a minimal meta-plugin package (Saropa + your rules hook) under a workspace-relative folder.',
    category: 'Setup & Configuration',
    icon: 'new-folder',
  },
  {
    command: 'saropaLints.createSaropaInstructions',
    title: 'Create AI Agent Instructions',
    description: 'Generate a Saropa Lints instruction file for AI coding assistants.',
    category: 'Setup & Configuration',
    icon: 'book',
  },

  // ── Analysis ─────────────────────────────────────────────────────────────

  {
    command: 'saropaLints.runAnalysis',
    title: 'Run Analysis',
    description: 'Analyze the current project and refresh all violation data.',
    category: 'Analysis',
    icon: 'play',
  },
  {
    command: 'saropaLints.crossFile.unusedFiles',
    title: 'Cross-File — Find Unused Files',
    description: 'Run project-wide analysis to find Dart files that are not imported by any other file.',
    category: 'Analysis',
    icon: 'search-remove',
  },
  {
    command: 'saropaLints.crossFile.circularDeps',
    title: 'Cross-File — Detect Circular Dependencies',
    description: 'Run project-wide analysis to detect circular import chains across files.',
    category: 'Analysis',
    icon: 'references',
  },
  {
    command: 'saropaLints.crossFile.importStats',
    title: 'Cross-File — Show Import Statistics',
    description: 'Show cross-file import graph totals like file count and import edges.',
    category: 'Analysis',
    icon: 'graph',
  },
  {
    command: 'saropaLints.crossFile.featureDeps',
    title: 'Cross-File — Show Feature Dependencies',
    description: 'Show feature-to-feature import relationships for projects using lib/features.',
    category: 'Analysis',
    icon: 'organization',
  },
  {
    command: 'saropaLints.crossFile.unusedSymbols',
    title: 'Cross-File — Find Unused Symbols',
    description: 'Report likely unused top-level symbols across project files.',
    category: 'Analysis',
    icon: 'symbol-method',
  },
  {
    command: 'saropaLints.crossFile.deadImports',
    title: 'Cross-File — Find Dead Imports',
    description: 'Report likely dead relative imports where no imported symbols are used.',
    category: 'Analysis',
    icon: 'symbol-namespace',
  },
  {
    command: 'saropaLints.crossFile.unusedL10n',
    title: 'Cross-File — Find Unused l10n Keys',
    description: 'Compare ARB keys to identifier usage in lib/ and test/ (heuristic; may miss dynamic keys).',
    category: 'Analysis',
    icon: 'symbol-string',
  },
  {
    command: 'saropaLints.crossFile.duplicates',
    title: 'Cross-File — Find Duplicate Line Blocks',
    description: 'Find repeated normalized multi-line blocks across Dart files (line-based, not AST).',
    category: 'Analysis',
    icon: 'copy',
  },
  {
    command: 'saropaLints.crossFile.snapshot',
    title: 'Cross-File — Write Project Snapshot (JSON)',
    description: 'Run full cross-file analysis and write cross_file_snapshot.json for ProjectContext consumers.',
    category: 'Analysis',
    icon: 'database',
  },
  {
    command: 'saropaLints.crossFile.graph',
    title: 'Cross-File — Export Import Graph (DOT)',
    description: 'Export the cross-file import graph as a Graphviz DOT file.',
    category: 'Analysis',
    icon: 'type-hierarchy',
  },
  {
    command: 'saropaLints.crossFile.report',
    title: 'Cross-File — Generate HTML Report',
    description: 'Generate an HTML cross-file analysis report under reports/.saropa_lints/cross_file.',
    category: 'Analysis',
    icon: 'output',
  },
  {
    command: 'saropaLints.verifyPlugin',
    title: 'Verify Plugin Is Running',
    description: 'Run the liveness check to confirm the analyzer plugin is connected and producing diagnostics.',
    category: 'Analysis',
    icon: 'pulse',
  },
  {
    command: 'saropaLints.refresh',
    title: 'Refresh',
    description: 'Re-read cached analysis results and update all tree views.',
    category: 'Analysis',
    icon: 'refresh',
  },
  {
    command: 'saropaLints.toggleInlineAnnotations',
    title: 'Toggle Inline Annotations',
    description: 'Show or hide inline violation annotations in the editor.',
    category: 'Analysis',
    icon: 'comment',
  },
  {
    command: 'saropaLints.showOutput',
    title: 'Show Output',
    description: 'Open the Saropa Lints output channel to see diagnostic logs.',
    category: 'Analysis',
    icon: 'output',
  },
  {
    command: 'saropaLints.showRelatedRuleTelemetry',
    title: 'Show Related Rule Telemetry',
    description:
      'Open a UI panel showing related-rule interaction counters and recent event metadata.',
    category: 'Analysis',
    icon: 'graph',
  },
  {
    command: 'saropaLints.resetRelatedRuleTelemetry',
    title: 'Reset Related Rule Telemetry',
    description: 'Clear related-rule interaction counters.',
    category: 'Analysis',
    icon: 'clear-all',
  },
  {
    command: 'saropaLints.copyLatestReport',
    title: 'Copy Latest Report',
    description:
      'Copy the most recent analysis report (reports/<date>/*_saropa_lint_report.log) to the clipboard.',
    category: 'Analysis',
    icon: 'clippy',
  },
  {
    command: 'saropaLints.openLatestReport',
    title: 'Open Latest Report',
    description:
      'Open the most recent analysis report (reports/<date>/*_saropa_lint_report.log) in an editor tab.',
    category: 'Analysis',
    icon: 'file-text',
  },

  // ── Violations & Filtering ───────────────────────────────────────────────

  {
    command: 'saropaLints.focusView',
    title: 'Focus Saropa Lints Sidebar',
    description: 'Reveal the unified Saropa Lints view in the activity bar (editor dashboards, actions, status, settings, triage, help).',
    category: 'Violations & Filtering',
    icon: 'list-tree',
  },
  {
    command: 'saropaLints.focusIssues',
    title: 'Show All Violations',
    description: 'Display every violation found in the project.',
    category: 'Violations & Filtering',
    icon: 'checklist',
  },
  {
    command: 'saropaLints.focusIssuesForFile',
    title: 'Show Violations for File',
    description: 'Filter the violations view to a specific file.',
    category: 'Violations & Filtering',
    icon: 'file',
  },
  {
    command: 'saropaLints.openFileAndFocusIssues',
    title: 'Open File and Show Violations',
    description: 'Open a file in the editor and filter the violations view to it.',
    category: 'Violations & Filtering',
    icon: 'go-to-file',
    internal: true,
  },
  {
    command: 'saropaLints.fileRisk.showViolations',
    title: 'Show Violations for File (File Risk)',
    description: 'Filter the violations view to the selected file risk entry.',
    category: 'Violations & Filtering',
    icon: 'filter',
    internal: true,
  },
  {
    command: 'saropaLints.fileRisk.hideFile',
    title: 'Hide File (File Risk)',
    description: 'Suppress a file from the violations and file risk views.',
    category: 'Violations & Filtering',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.fileRisk.copyPath',
    title: 'Copy Path (File Risk)',
    description: 'Copy the relative file path from a file risk entry.',
    category: 'Violations & Filtering',
    icon: 'clippy',
    internal: true,
  },
  {
    command: 'saropaLints.focusIssuesForActiveFile',
    title: 'Show in Saropa Lints',
    description: 'Show violations for the currently open file in the sidebar.',
    category: 'Violations & Filtering',
    icon: 'file-code',
  },
  {
    command: 'saropaLints.focusIssuesWithImpactFilter',
    title: 'Show Violations by Impact',
    description: 'Filter violations by their impact level.',
    category: 'Violations & Filtering',
    icon: 'flame',
  },
  {
    command: 'saropaLints.focusIssuesWithSeverityFilter',
    title: 'Show Violations by Severity',
    description: 'Filter violations by severity (info, warning, error).',
    category: 'Violations & Filtering',
    icon: 'warning',
  },
  {
    command: 'saropaLints.focusIssuesForRules',
    title: 'Show Violations for Rules',
    description: 'Filter violations to show only specific lint rules.',
    category: 'Violations & Filtering',
    icon: 'filter',
  },
  {
    command: 'saropaLints.focusIssuesByRuleMetadata',
    title: 'Show Violations by Rule Metadata',
    description: 'Filter violations using a rule metadata query (type, tag, status, or CWE).',
    category: 'Violations & Filtering',
    icon: 'filter',
    internal: true,
  },
  {
    command: 'saropaLints.focusIssuesForOwasp',
    title: 'Focus Violations for OWASP Category',
    description: 'Filter violations by a specific OWASP security category.',
    category: 'Violations & Filtering',
    icon: 'shield',
    internal: true,
  },
  {
    command: 'saropaLints.setIssuesFilter',
    title: 'Filter by Text',
    description: 'Type a text query to filter the violations list.',
    category: 'Violations & Filtering',
    icon: 'filter',
  },
  {
    command: 'saropaLints.setIssuesFilterByType',
    title: 'Filter by Type',
    description: 'Filter violations by their diagnostic type.',
    category: 'Violations & Filtering',
    icon: 'filter',
  },
  {
    command: 'saropaLints.setIssuesFilterByRule',
    title: 'Filter by Rule',
    description: 'Pick a specific rule name to filter violations.',
    category: 'Violations & Filtering',
    icon: 'filter',
  },
  {
    command: 'saropaLints.setIssuesFilterByMetadata',
    title: 'Filter by Rule Metadata',
    description: 'Filter violations by rule type, tags, status, and CWE metadata.',
    category: 'Violations & Filtering',
    icon: 'filter',
  },
  {
    command: 'saropaLints.reviewHotspotState',
    title: 'Review Security Hotspot State',
    description: 'Set review workflow state for security hotspots (open/safe/fixed).',
    category: 'Violations & Filtering',
    icon: 'shield',
  },
  {
    command: 'saropaLints.clearIssuesFilters',
    title: 'Clear Filters',
    description: 'Remove all active violation filters.',
    category: 'Violations & Filtering',
    icon: 'clear-all',
  },
  {
    command: 'saropaLints.setGroupBy',
    title: 'Group By',
    description: 'Change how violations are grouped (by file, rule, severity, etc.).',
    category: 'Violations & Filtering',
    icon: 'list-tree',
  },
  {
    command: 'saropaLints.focusFile',
    title: 'Show Only This File',
    description: 'Temporarily restrict the violations view to a single file.',
    category: 'Violations & Filtering',
    icon: 'pinned',
    internal: true,
  },
  {
    command: 'saropaLints.clearFocusFile',
    title: 'Show All Files',
    description: 'Remove the single-file filter and show all violations again.',
    category: 'Violations & Filtering',
    icon: 'close-all',
  },
  {
    command: 'saropaLints.hideFolder',
    title: 'Hide Folder from View',
    description: 'Suppress violations from a specific folder.',
    category: 'Violations & Filtering',
    icon: 'folder',
    internal: true,
  },
  {
    command: 'saropaLints.hideFile',
    title: 'Hide File from View',
    description: 'Suppress violations from a specific file.',
    category: 'Violations & Filtering',
    icon: 'file',
    internal: true,
  },
  {
    command: 'saropaLints.hideRule',
    title: 'Hide Rule from View',
    description: 'Suppress a specific lint rule from the violations view.',
    category: 'Violations & Filtering',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.hideRuleInFile',
    title: 'Hide Rule in This File',
    description: 'Suppress a rule only in a specific file.',
    category: 'Violations & Filtering',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.hideSeverity',
    title: 'Hide This Severity',
    description: 'Suppress all violations of a given severity level.',
    category: 'Violations & Filtering',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.hideImpact',
    title: 'Hide This Impact',
    description: 'Suppress all violations of a given impact level.',
    category: 'Violations & Filtering',
    icon: 'eye-closed',
    internal: true,
  },
  {
    command: 'saropaLints.clearSuppressions',
    title: 'Clear Suppressions',
    description: 'Remove all view-level suppressions and show everything again.',
    category: 'Violations & Filtering',
    icon: 'eye',
  },
  {
    command: 'saropaLints.copyPath',
    title: 'Copy Path',
    description: 'Copy the file path of a violation to the clipboard.',
    category: 'Violations & Filtering',
    icon: 'clippy',
    internal: true,
  },
  {
    command: 'saropaLints.copyMessage',
    title: 'Copy Message',
    description: 'Copy a violation message to the clipboard.',
    category: 'Violations & Filtering',
    icon: 'clippy',
    internal: true,
  },

  // ── Rules & Fixes ────────────────────────────────────────────────────────

  {
    command: 'saropaLints.explainRule',
    title: 'Explain Rule',
    description: 'Open a detailed explanation panel for a lint rule.',
    category: 'Rules & Fixes',
    icon: 'book',
  },
  {
    command: 'saropaLints.explainRuleFromSuggestion',
    title: 'Explain Rule (Suggestion)',
    description: 'Open rule details from a related-rule suggestion action.',
    category: 'Rules & Fixes',
    icon: 'book',
    internal: true,
  },
  {
    command: 'saropaLints.applyFix',
    title: 'Apply Fix',
    description: 'Apply the suggested quick fix for a violation.',
    category: 'Rules & Fixes',
    icon: 'wrench',
    internal: true,
  },
  {
    command: 'saropaLints.fixAllInFile',
    title: 'Fix All in This File',
    description: 'Apply all available quick fixes for violations in a file.',
    category: 'Rules & Fixes',
    icon: 'wand',
    internal: true,
  },
  {
    command: 'saropaLints.disableRules',
    title: 'Disable Rule(s)',
    description: 'Turn off one or more lint rules in the project configuration.',
    category: 'Rules & Fixes',
    icon: 'circle-slash',
  },
  {
    command: 'saropaLints.enableRules',
    title: 'Enable Rule(s)',
    description: 'Turn on one or more lint rules in the project configuration.',
    category: 'Rules & Fixes',
    icon: 'check',
  },

  // ── Security Posture ─────────────────────────────────────────────────────

  {
    command: 'saropaLints.exportOwaspReport',
    title: 'Export OWASP Compliance Report',
    description: 'Generate and save an OWASP compliance report for the project.',
    category: 'Security Posture',
    icon: 'shield',
  },

  // ── Reporting & Export ───────────────────────────────────────────────────

  {
    command: 'saropaLints.issues.copyAsJson',
    title: 'Copy Violations as JSON',
    description: 'Copy the full violations tree data to the clipboard as JSON.',
    category: 'Reporting & Export',
    icon: 'clippy',
  },
  {
    command: 'saropaLints.summary.copyAsJson',
    title: 'Copy Summary as JSON',
    description: 'Copy the summary tree data to the clipboard as JSON.',
    category: 'Reporting & Export',
    icon: 'clippy',
  },
  {
    command: 'saropaLints.securityPosture.copyAsJson',
    title: 'Copy Security Posture as JSON',
    description: 'Copy the security posture tree data to the clipboard as JSON.',
    category: 'Reporting & Export',
    icon: 'clippy',
  },
  {
    command: 'saropaLints.fileRisk.copyAsJson',
    title: 'Copy File Risk as JSON',
    description: 'Copy the file risk tree data to the clipboard as JSON.',
    category: 'Reporting & Export',
    icon: 'clippy',
  },
];
