analyzer:
  plugins:
    - custom_lint
  errors:
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore

# Configure saropa_lints tier
custom_lint:
  saropa_lints:
    tier: recommended  # essential | recommended | professional | comprehensive | insanity
  rules:
    # Enable for testing fixture files
    - prefer_async_callback: true
