analyzer:
  plugins:
    - custom_lint
  errors:
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore

# Configure saropa_lints tier
custom_lint:
  saropa_lints:
    tier: recommended  # essential | recommended | professional | comprehensive | insanity
  rules:
    # Enable for testing fixture files
    - prefer_async_callback: true
    # Enable debug rules for testing (they're in higher tiers)
    - avoid_debug_print: true
    - avoid_print_in_production: true
    # Explicitly enable to debug
    - prefer_where_or_null: true
