/**
 * Labels for the UI language quick pick and settings row.
 *
 * Endonyms (native script) plus English in parentheses for non-English codes
 * so palette text stays discoverable for maintainers and mixed-language teams.
 */
import * as vscode from 'vscode';

import coverageData from './locale_coverage.json';
import { l10n } from './runtime';

/**
 * Per-locale translation coverage, regenerated by
 * `extension/scripts/i18n/generate_locales.py` on every audit/translate run.
 * The picker reads `coveragePct` to badge any locale below 100% so a user can
 * never silently choose a near-English UI (e.g. Chinese at 4%). Sourced from the
 * same audit stats, so the badge can never claim more coverage than was measured.
 */
const LOCALE_COVERAGE: Readonly<Record<string, { coveragePct: number }>> = (
  coverageData as { locales: Record<string, { coveragePct: number }> }
).locales;

/** Values accepted for `saropaLints.uiLanguage` (matches package.json enum). */
export type UiLanguageCode =
  | 'auto'
  | 'ar'
  | 'bn'
  | 'de'
  | 'en'
  | 'es'
  | 'fa'
  | 'fil'
  | 'fr'
  | 'he'
  | 'hi'
  | 'id'
  | 'it'
  | 'ja'
  | 'ko'
  | 'nl'
  | 'pl'
  | 'pt'
  | 'ru'
  | 'sw'
  | 'th'
  | 'tr'
  | 'uk'
  | 'ur'
  | 'vi'
  | 'zh';

const ENGLISH_ENDONYM: Record<Exclude<UiLanguageCode, 'auto'>, string> = {
  ar: 'Arabic',
  bn: 'Bengali',
  de: 'German',
  en: 'English',
  es: 'Spanish',
  fa: 'Persian',
  fil: 'Filipino',
  fr: 'French',
  he: 'Hebrew',
  hi: 'Hindi',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  ko: 'Korean',
  nl: 'Dutch',
  pl: 'Polish',
  pt: 'Portuguese',
  ru: 'Russian',
  sw: 'Swahili',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  vi: 'Vietnamese',
  zh: 'Chinese',
};

const NATIVE_ENDONYM: Record<Exclude<UiLanguageCode, 'auto' | 'en'>, string> = {
  ar: 'العربية',
  bn: 'বাংলা',
  de: 'Deutsch',
  es: 'Español',
  fa: 'فارسی',
  fil: 'Filipino',
  fr: 'Français',
  he: 'עברית',
  hi: 'हिन्दी',
  id: 'Bahasa Indonesia',
  it: 'Italiano',
  ja: '日本語',
  ko: '한국어',
  nl: 'Nederlands',
  pl: 'Polski',
  pt: 'Português',
  ru: 'Русский',
  sw: 'Kiswahili',
  th: 'ไทย',
  tr: 'Türkçe',
  uk: 'Українська',
  ur: 'اردو',
  vi: 'Tiếng Việt',
  zh: '中文',
};

export interface LanguagePickItem extends vscode.QuickPickItem {
  readonly value: UiLanguageCode;
}

/** One-line label for the current value in the Settings tree row. */
export function formatLanguageChoiceLabel(code: string): string {
  if (code === 'auto') {
    return l10n('uiLanguage.pick.auto');
  }
  if (code === 'en') {
    return ENGLISH_ENDONYM.en;
  }
  if (Object.prototype.hasOwnProperty.call(NATIVE_ENDONYM, code)) {
    const k = code as keyof typeof NATIVE_ENDONYM;
    return `${NATIVE_ENDONYM[k]} (${ENGLISH_ENDONYM[k]})`;
  }
  return code;
}

function sortedLocaleCodes(): Exclude<UiLanguageCode, 'auto'>[] {
  const codes = Object.keys(ENGLISH_ENDONYM) as Exclude<UiLanguageCode, 'auto'>[];
  return codes.sort((a, b) =>
    ENGLISH_ENDONYM[a].localeCompare(ENGLISH_ENDONYM[b], 'en', { sensitivity: 'base' }),
  );
}

/**
 * Coverage badge for a locale, or undefined when it is fully translated.
 *
 * A complete locale (100%, or absent from the coverage file) shows no badge so
 * the picker stays clean for the languages that actually work. An incomplete one
 * carries its measured percentage, the honest signal that selecting it leaves
 * most of the UI in English.
 */
function coverageBadge(code: UiLanguageCode): string | undefined {
  const pct = LOCALE_COVERAGE[code]?.coveragePct;
  if (pct === undefined || pct >= 100) {
    return undefined;
  }
  return l10n('uiLanguage.pick.coverage', { pct: String(pct) });
}

/** Rows for `showQuickPick`: `auto` first, then English language names A–Z. */
export function buildUiLanguageQuickPickItems(): LanguagePickItem[] {
  const order: UiLanguageCode[] = ['auto', ...sortedLocaleCodes()];
  const resolvedAuto = vscode.env.language;
  return order.map((value) => {
    const item: LanguagePickItem = {
      label: formatLanguageChoiceLabel(value),
      value,
    };
    // Show the resolved language for "auto" so users know what they're getting.
    if (value === 'auto') {
      return { ...item, description: `→ ${resolvedAuto}` };
    }
    // Badge incomplete locales (e.g. "4% translated — rest shows in English");
    // complete ones get no description so the list stays uncluttered.
    const badge = coverageBadge(value);
    return badge ? { ...item, description: badge } : item;
  });
}
