/**
 * D2: OWASP Compliance Export — generates a markdown report with OWASP Top 10
 * coverage matrix, violation counts by category, and gap analysis.
 */

import { ViolationsData, Violation } from './violationsReader';
import { computeHealthScore } from './healthScore';
import { MOBILE_TOP_10, WEB_TOP_10, normalizeOwaspId } from './views/securityPostureTree';

interface CategoryRow {
  label: string;
  id: string;
  count: number;
  rules: string[];
}

/**
 * Build per-category rows from violations for a given OWASP list (mobile or web).
 * Counts how many violations map to each OWASP category and collects the distinct rule names.
 * Categories with zero violations are still included (for gap analysis).
 */
function buildCategoryRows(
  violations: Violation[],
  categories: readonly string[],
  key: 'mobile' | 'web',
): CategoryRow[] {
  const counts = new Map<string, number>();
  const rulesSeen = new Map<string, Set<string>>();

  for (const v of violations) {
    const arr = v.owasp?.[key];
    if (!Array.isArray(arr)) continue;
    for (const raw of arr) {
      if (typeof raw !== 'string') continue;
      const id = normalizeOwaspId(raw);
      counts.set(id, (counts.get(id) ?? 0) + 1);
      const set = rulesSeen.get(id) ?? new Set<string>();
      set.add(v.rule);
      rulesSeen.set(id, set);
    }
  }

  return categories.map((label) => {
    const id = normalizeOwaspId(label);
    return {
      label,
      id,
      count: counts.get(id) ?? 0,
      rules: [...(rulesSeen.get(id) ?? [])],
    };
  });
}

function formatTable(rows: CategoryRow[]): string {
  const lines: string[] = [];
  lines.push('| Category | Violations | Rules | Status |');
  lines.push('|----------|-----------|-------|--------|');
  for (const r of rows) {
    // Distinguish: has issues, has rules but no issues (clean), or no rules mapped at all (gap).
    const status = r.count > 0
      ? `${r.count} issue${r.count === 1 ? '' : 's'}`
      : r.rules.length > 0 ? 'Clean' : 'No rules';
    const ruleList = r.rules.length > 0 ? r.rules.join(', ') : '--';
    lines.push(`| ${r.label} | ${r.count} | ${ruleList} | ${status} |`);
  }
  return lines.join('\n');
}

/** Generate a full OWASP compliance markdown report from violations data. */
export function generateOwaspReport(
  data: ViolationsData,
  workspaceRoot: string,
): string {
  const health = computeHealthScore(data);
  const tier = data.config?.tier ?? 'unknown';
  const totalRules = data.config?.enabledRuleCount ?? 0;
  const total = data.summary?.totalViolations ?? data.violations.length;

  const mobileRows = buildCategoryRows(data.violations, MOBILE_TOP_10, 'mobile');
  const webRows = buildCategoryRows(data.violations, WEB_TOP_10, 'web');

  // Gap analysis: categories where the current tier has no rules mapped at all.
  // These represent blind spots — OWASP categories with zero lint coverage.
  const mobileGaps = mobileRows.filter((r) => r.count === 0 && r.rules.length === 0);
  const webGaps = webRows.filter((r) => r.count === 0 && r.rules.length === 0);

  const lines: string[] = [];
  lines.push('# OWASP Compliance Report');
  lines.push('');
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Workspace:** ${workspaceRoot}`);
  lines.push(`**Tier:** ${tier} (${totalRules} rules enabled)`);
  if (health) {
    lines.push(`**Health Score:** ${health.score}/100`);
  }
  lines.push(`**Total Violations:** ${total}`);
  lines.push('');

  lines.push('## OWASP Mobile Top 10');
  lines.push('');
  lines.push(formatTable(mobileRows));
  lines.push('');

  lines.push('## OWASP Web Top 10');
  lines.push('');
  lines.push(formatTable(webRows));
  lines.push('');

  if (mobileGaps.length > 0 || webGaps.length > 0) {
    lines.push('## Gap Analysis');
    lines.push('');
    lines.push('Categories with no mapped rules in the current tier:');
    lines.push('');
    for (const g of mobileGaps) {
      lines.push(`- **Mobile** ${g.label}`);
    }
    for (const g of webGaps) {
      lines.push(`- **Web** ${g.label}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Saropa Lints VS Code Extension*');
  lines.push('');

  return lines.join('\n');
}
