version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-dev-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
