# SAROPA LINTS — package development analysis options
#
# This file configures `dart analyze` for the saropa_lints package itself.
# Consumer projects use `dart run saropa_lints:init` to generate their own.
#
# cspell:disable

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"
    - "example/**"
    - "example_async/**"
    - "example_core/**"
    - "example_packages/**"
    - "example_platforms/**"
    - "example_style/**"
    - "example_widgets/**"
linter:
  rules:
    - curly_braces_in_flow_control_structures
