# =============================================================================
# ANALYZER CONFIGURATION
# =============================================================================
#
# These excludes improve analysis performance by skipping files that:
# 1. Cannot be manually fixed (generated code)
# 2. Are not part of the main codebase (build artifacts, examples)
#
# IMPORTANT: Excluding generated files is CRITICAL for performance.
# Generated code can be 10x larger than source code and causes the analyzer
# to spend most of its time on files you can't fix anyway.
# =============================================================================

analyzer:
  errors:
    # TODOs are developer notes, not actionable diagnostics for CI/IDE
    todo: ignore
  exclude:
    # =========================================================================
    # GENERATED CODE - Cannot be manually fixed, regenerated on build
    # =========================================================================
    # These patterns match code generated by build_runner, freezed, json_serializable,
    # auto_route, mockito, and other code generators. Analyzing them wastes time
    # since any fixes would be overwritten on the next build.
    - "**/*.g.dart"           # json_serializable, hive, built_value
    - "**/*.freezed.dart"     # freezed immutable classes
    - "**/*.gr.dart"          # auto_route generated routes
    - "**/*.gen.dart"         # various generators
    - "**/*.mocks.dart"       # mockito mocks
    - "**/*.config.dart"      # injectable, get_it config
    - "**/generated/**"       # catch-all for generated directories

    # =========================================================================
    # BUILD ARTIFACTS - Temporary files, not source code
    # =========================================================================
    # Build output directories contain compiled/bundled code, not source.
    - build/**
    - .dart_tool/**

    # =========================================================================
    # EXAMPLES - Separate from main package, may have intentional violations
    # =========================================================================
    # Example code often demonstrates anti-patterns or uses simplified code
    # that wouldn't pass strict linting. Exclude to reduce noise.
    - example/**

linter:
  rules:
    - curly_braces_in_flow_control_structures
