"use strict";
/**
 * D2: OWASP Compliance Export — generates a markdown report with OWASP Top 10
 * coverage matrix, violation counts by category, and gap analysis.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateOwaspReport = generateOwaspReport;
const healthScore_1 = require("./healthScore");
const securityPostureTree_1 = require("./views/securityPostureTree");
/**
 * Build per-category rows from violations for a given OWASP list (mobile or web).
 * Counts how many violations map to each OWASP category and collects the distinct rule names.
 * Categories with zero violations are still included (for gap analysis).
 */
function buildCategoryRows(violations, categories, key) {
    const counts = new Map();
    const rulesSeen = new Map();
    for (const v of violations) {
        const arr = v.owasp?.[key];
        if (!Array.isArray(arr))
            continue;
        for (const raw of arr) {
            if (typeof raw !== 'string')
                continue;
            const id = (0, securityPostureTree_1.normalizeOwaspId)(raw);
            counts.set(id, (counts.get(id) ?? 0) + 1);
            const set = rulesSeen.get(id) ?? new Set();
            set.add(v.rule);
            rulesSeen.set(id, set);
        }
    }
    return categories.map((label) => {
        const id = (0, securityPostureTree_1.normalizeOwaspId)(label);
        return {
            label,
            id,
            count: counts.get(id) ?? 0,
            rules: [...(rulesSeen.get(id) ?? [])],
        };
    });
}
function formatTable(rows) {
    const lines = [];
    lines.push('| Category | Violations | Rules | Status |');
    lines.push('|----------|-----------|-------|--------|');
    for (const r of rows) {
        // rules[] is populated only from violations, so r.count === 0 implies r.rules is empty.
        // We cannot distinguish "covered but clean" from "no rules" without a rule-catalog lookup.
        // Use a neutral label for zero-violation categories.
        const status = r.count > 0
            ? `${r.count} issue${r.count === 1 ? '' : 's'}`
            : 'No violations';
        const ruleList = r.rules.length > 0 ? r.rules.join(', ') : '--';
        lines.push(`| ${r.label} | ${r.count} | ${ruleList} | ${status} |`);
    }
    return lines.join('\n');
}
/** Generate a full OWASP compliance markdown report from violations data. */
function generateOwaspReport(data, workspaceRoot) {
    const health = (0, healthScore_1.computeHealthScore)(data);
    const tier = data.config?.tier ?? 'unknown';
    const totalRules = data.config?.enabledRuleCount ?? 0;
    const total = data.summary?.totalViolations ?? data.violations.length;
    const mobileRows = buildCategoryRows(data.violations, securityPostureTree_1.MOBILE_TOP_10, 'mobile');
    const webRows = buildCategoryRows(data.violations, securityPostureTree_1.WEB_TOP_10, 'web');
    // Gap analysis: categories with zero violations.
    // Without a rule-to-OWASP catalog we cannot distinguish "rules exist but no violations"
    // from "no rules mapped at all". Both show as r.count === 0.
    const mobileGaps = mobileRows.filter((r) => r.count === 0);
    const webGaps = webRows.filter((r) => r.count === 0);
    const lines = [];
    lines.push('# OWASP Compliance Report');
    lines.push('');
    lines.push(`**Generated:** ${new Date().toISOString()}`);
    lines.push(`**Workspace:** ${workspaceRoot}`);
    lines.push(`**Tier:** ${tier} (${totalRules} rules enabled)`);
    if (health) {
        lines.push(`**Health Score:** ${health.score}/100`);
    }
    lines.push(`**Total Violations:** ${total}`);
    lines.push('');
    lines.push('## OWASP Mobile Top 10');
    lines.push('');
    lines.push(formatTable(mobileRows));
    lines.push('');
    lines.push('## OWASP Web Top 10');
    lines.push('');
    lines.push(formatTable(webRows));
    lines.push('');
    if (mobileGaps.length > 0 || webGaps.length > 0) {
        lines.push('## Gap Analysis');
        lines.push('');
        lines.push('Categories with no violations detected:');
        lines.push('');
        for (const g of mobileGaps) {
            lines.push(`- **Mobile** ${g.label}`);
        }
        for (const g of webGaps) {
            lines.push(`- **Web** ${g.label}`);
        }
        lines.push('');
    }
    lines.push('---');
    lines.push('*Generated by Saropa Lints VS Code Extension*');
    lines.push('');
    return lines.join('\n');
}
//# sourceMappingURL=owaspExport.js.map