// ignore_for_file: depend_on_referenced_packages, deprecated_member_use

/// Envied package lint rules.
///
/// Ensures compile-time secrets generated by Envied are obfuscated so that API
/// keys and tokens are not stored as plain-text string constants in the binary.
library;

import 'package:analyzer/dart/ast/ast.dart';

import '../../saropa_lint_rule.dart';

/// Warns when Envied annotation lacks obfuscate parameter.
///
/// Since: v2.2.0 | Updated: v4.13.0 | Rule version: v2
///
/// Alias: envied_obfuscate, require_env_obfuscation
///
/// Environment variables generated by Envied should be obfuscated to prevent
/// easy extraction from compiled binaries.
///
/// **BAD:**
/// ```dart
/// @Envied()
/// abstract class Env {
///   @EnviedField()
///   static const String apiKey = _Env.apiKey;
/// }
/// ```
///
/// **GOOD:**
/// ```dart
/// @Envied(obfuscate: true)
/// abstract class Env {
///   @EnviedField(obfuscate: true)
///   static const String apiKey = _Env.apiKey;
/// }
/// ```
class RequireEnviedObfuscationRule extends SaropaLintRule {
  RequireEnviedObfuscationRule() : super(code: _code);

  @override
  LintImpact get impact => LintImpact.warning;

  @override
  RuleType? get ruleType => RuleType.codeSmell;

  @override
  Set<String> get tags => const {'packages'};

  @override
  RuleCost get cost => RuleCost.medium;

  static const LintCode _code = LintCode(
    'require_envied_obfuscation',
    '[require_envied_obfuscation] Envied environment variable generated without obfuscation stores secrets as plain text string constants in the compiled binary. Attackers can extract API keys, database URLs, and authentication tokens using basic reverse engineering tools, enabling unauthorized access to your backend services and third-party APIs. {v2}',
    correctionMessage:
        'Add obfuscate: true to the @Envied annotation or individual @EnviedField annotations to encode secrets at compile time and prevent plain text extraction.',
    severity: DiagnosticSeverity.WARNING,
  );

  @override
  void runWithReporter(
    SaropaDiagnosticReporter reporter,
    SaropaContext context,
  ) {
    context.addAnnotation((Annotation node) {
      final String name = node.name.name;
      if (name != 'Envied' && name != 'EnviedField') return;

      // For class-level @Envied, skip if all @EnviedField annotations
      // in the class already specify obfuscate explicitly.
      if (name == 'Envied') {
        final AstNode? classNode = node.parent;
        if (classNode is ClassDeclaration &&
            _allFieldsHandleObfuscation(classNode)) {
          return;
        }
      }

      // Check for obfuscate: true
      final ArgumentList? args = node.arguments;
      if (args == null) {
        reporter.atNode(node);
        return;
      }

      final bool hasObfuscate = args.arguments.any((Expression arg) {
        if (arg is NamedExpression) {
          if (arg.name.label.name == 'obfuscate') {
            return arg.expression.toSource() == 'true';
          }
        }
        return false;
      });

      if (!hasObfuscate) {
        reporter.atNode(node);
      }
    });
  }

  /// Returns true if every @EnviedField in the class explicitly
  /// specifies an `obfuscate` argument (true or false).
  static bool _allFieldsHandleObfuscation(ClassDeclaration classDecl) {
    bool hasAnyField = false;

    for (final ClassMember member in classDecl.bodyMembers) {
      if (member is! FieldDeclaration) continue;

      for (final Annotation annotation in member.metadata) {
        if (annotation.name.name != 'EnviedField') continue;
        hasAnyField = true;

        final ArgumentList? args = annotation.arguments;
        if (args == null) return false;

        final bool specifiesObfuscate = args.arguments.any((Expression arg) {
          if (arg is NamedExpression) {
            return arg.name.label.name == 'obfuscate';
          }
          return false;
        });

        if (!specifiesObfuscate) return false;
      }
    }

    return hasAnyField;
  }
}
