/// Writes a minimal composite analyzer-plugin package (Saropa + TODO hooks).
library;

import 'dart:io';

import 'package:path/path.dart' as p;

/// Sanitize a directory basename into a valid pub package `name`.
String compositePubspecNameFromBasename(String basename) {
  final cleaned = basename
      .replaceAll('-', '_')
      .replaceAll(RegExp(r'[^a-z0-9_]'), '');
  if (cleaned.isEmpty) return 'saropa_composite_plugin';
  // Pub package names must start with a letter or underscore.
  if (RegExp(r'^[0-9]').hasMatch(cleaned)) return 'p_$cleaned';
  return cleaned;
}

/// YAML `plugins:` key must match [Plugin.name] (see composite guide).
String compositePluginYamlKey(String pubspecName) {
  if (pubspecName.endsWith('_plugin')) {
    return pubspecName.split('_plugin').first;
  }
  return pubspecName;
}

/// Creates [root] with `pubspec.yaml`, `lib/main.dart`, and `README.md`.
void emitCompositePluginScaffold(Directory root) {
  if (!root.existsSync()) {
    root.createSync(recursive: true);
  }
  final lib = Directory('${root.path}/lib');
  if (!lib.existsSync()) {
    lib.createSync(recursive: true);
  }

  final basename = p.basename(root.path);
  final packageName = compositePubspecNameFromBasename(basename);
  final pluginKey = compositePluginYamlKey(packageName);

  File('${root.path}/pubspec.yaml').writeAsStringSync('''
name: $packageName
description: Composite analyzer plugin (Saropa Lints + your org rules). Generated by saropa_lints init.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  analysis_server_plugin: ^0.3.4
  saropa_lints: ^12.6.0
''');

  File('${root.path}/lib/main.dart').writeAsStringSync('''
// Generated by: dart run saropa_lints:init --emit-composite-plugin-scaffold
//
// Enable this plugin under the same key as [SaropaCompositePlugin.name] —
// see doc/guides/composite_analyzer_plugin.md

import 'dart:async' show FutureOr;

import 'package:analysis_server_plugin/plugin.dart';
import 'package:analysis_server_plugin/registry.dart';
import 'package:saropa_lints/saropa_lints.dart';

/// Top-level plugin instance discovered by the analysis server.
final plugin = SaropaCompositePlugin();

class SaropaCompositePlugin extends Plugin {
  @override
  String get name => '$pluginKey';

  @override
  FutureOr<void> start() {
    loadNativePluginConfig();
  }

  @override
  void register(PluginRegistry registry) {
    registerSaropaLintRules(registry);
    // Register org-specific rules and fixes on [registry] here.
  }
}
''');

  File('${root.path}/README.md').writeAsStringSync('''
# $packageName

Composite analyzer plugin scaffold. **One** `plugins:` entry in
`analysis_options.yaml` should point at this package; use key `$pluginKey`
to match `Plugin.name`.

Copy Saropa settings (`version`, `diagnostics`, `rule_packs`, …) under
that block. See `doc/guides/composite_analyzer_plugin.md` in saropa_lints.
''');
}
