/// Reading and extracting user customizations from generated YAML.
library;

/// Matches rule entries like `rule_name: true` or `rule_name: false`.
final RegExp ruleEntryPattern = RegExp(
  r'^\s+(\w+):\s*(true|false)',
  multiLine: true,
);

final RegExp _userCustomSectionPattern = RegExp(
  r'USER CUSTOMIZATIONS',
  multiLine: true,
);

/// Extract existing user customizations from the generated YAML.
///
/// Reads from two sources:
/// 1. The USER CUSTOMIZATIONS section (explicitly marked overrides)
/// 2. Tier sections where a rule value differs from the section's expected
///    direction (e.g., `false` in ENABLED → user manually disabled it)
///
/// This prevents tier changes from creating spurious "customizations"
/// while still preserving intentional manual edits.
///
/// Parameters:
/// - [yamlContent] - The existing YAML file content
/// - [allRules] - All known saropa_lints rules (v7 lowerCaseName)
/// - [v7NormalizedCount] - If non-null, incremented when a rule name is
///   normalized from mixed-case (v6) to lowerCaseName (v7)
///
/// Returns a record with [customizations] and [tierEdits] so the caller
/// can show the "Recovered N manually edited rule(s)" message without
/// scanning tier sections again.
({Map<String, bool> customizations, Map<String, bool> tierEdits})
extractUserCustomizations(
  String yamlContent,
  Set<String> allRules, [
  List<int>? v7NormalizedCount,
]) {
  final Map<String, bool> customizations = <String, bool>{};

  // Find USER CUSTOMIZATIONS section
  final Match? customizationsMatch = _userCustomSectionPattern.firstMatch(
    yamlContent,
  );

  if (customizationsMatch == null) {
    // No customizations section - file wasn't generated by this tool
    // or user hasn't made any customizations
    return (customizations: customizations, tierEdits: <String, bool>{});
  }

  // Find the content after USER CUSTOMIZATIONS header
  final String afterHeader = yamlContent.substring(customizationsMatch.end);

  // Find the end of the customizations section (next major section header)
  // Look for ENABLED, DISABLED, STYLISTIC, or TIER headers
  final sectionEndPattern = RegExp(
    r'(ENABLED RULES|DISABLED RULES|STYLISTIC|TIER \d+:)',
    multiLine: true,
  );
  final Match? nextSection = sectionEndPattern.firstMatch(afterHeader);
  final String customizationsSection = nextSection != null
      ? afterHeader.substring(0, nextSection.start)
      : afterHeader;

  // Extract rules from the customizations section only.
  // Normalize to v7 lowerCaseName so v6 config (mixed-case) is preserved.
  for (final Match match in ruleEntryPattern.allMatches(
    customizationsSection,
  )) {
    final rawName = match.group(1);
    if (rawName == null) continue;
    final String ruleName = rawName.toLowerCase();
    final bool currentEnabled = match.group(2) == 'true';

    // Skip rules that aren't in our rule set (might be from other plugins)
    if (!allRules.contains(ruleName)) continue;
    if (v7NormalizedCount != null && rawName != ruleName) {
      v7NormalizedCount[0] = v7NormalizedCount[0] + 1;
    }
    customizations[ruleName] = currentEnabled;
  }

  // Detect manual edits in tier sections: the ENABLED section should only
  // contain true entries and DISABLED should only contain false. Any rule
  // with the opposite value was manually edited and should be preserved.
  final manualEdits = detectManualTierEdits(
    yamlContent,
    allRules,
    v7NormalizedCount,
  );
  for (final entry in manualEdits.entries) {
    // Existing USER CUSTOMIZATIONS take precedence
    if (!customizations.containsKey(entry.key)) {
      customizations[entry.key] = entry.value;
    }
  }

  return (customizations: customizations, tierEdits: manualEdits);
}

/// Detect rules manually edited in ENABLED/DISABLED tier sections.
///
/// Init generates `true` in ENABLED sections and `false` in DISABLED
/// sections. Any opposite value was changed by the user after generation.
Map<String, bool> detectManualTierEdits(
  String yamlContent,
  Set<String> allRules, [
  List<int>? v7NormalizedCount,
]) {
  final Map<String, bool> edits = <String, bool>{};

  // ENABLED section: false entries are manual disables
  collectOppositeEntries(
    yamlContent,
    allRules,
    sectionHeader: 'ENABLED RULES',
    expectedValue: true,
    edits: edits,
    v7NormalizedCount: v7NormalizedCount,
  );

  // DISABLED section: true entries are manual enables
  collectOppositeEntries(
    yamlContent,
    allRules,
    sectionHeader: 'DISABLED RULES',
    expectedValue: false,
    edits: edits,
    v7NormalizedCount: v7NormalizedCount,
  );

  return edits;
}

/// Scan a tier section for rules whose value differs from [expectedValue].
/// Normalizes rule names to v7 lowerCaseName when reading.
void collectOppositeEntries(
  String yamlContent,
  Set<String> allRules, {
  required String sectionHeader,
  required bool expectedValue,
  required Map<String, bool> edits,
  List<int>? v7NormalizedCount,
}) {
  final headerMatch = RegExp(sectionHeader).firstMatch(yamlContent);

  if (headerMatch == null) return;

  final afterHeader = yamlContent.substring(headerMatch.end);

  // Section ends at the next major section header
  final nextSection = RegExp(
    r'(USER CUSTOMIZATIONS|ENABLED RULES|DISABLED RULES|STYLISTIC RULES)',
  ).firstMatch(afterHeader);

  final section = nextSection != null
      ? afterHeader.substring(0, nextSection.start)
      : afterHeader;

  for (final match in ruleEntryPattern.allMatches(section)) {
    final rawName = match.group(1);
    if (rawName == null) continue;
    final String ruleName = rawName.toLowerCase();
    final value = match.group(2) == 'true';

    if (!allRules.contains(ruleName)) continue;
    if (v7NormalizedCount != null && rawName != ruleName) {
      v7NormalizedCount[0] = v7NormalizedCount[0] + 1;
    }
    if (value != expectedValue) {
      edits[ruleName] = value;
    }
  }
}

// ---------------------------------------------------------------------------
// V6 → V7 (lowerCaseName) migration
// ---------------------------------------------------------------------------
