/// Core custom overrides file management.
///
/// Handles file creation, rule extraction, analysis settings, and migration
/// from the old bloated format to the minimal format (I3).
library;

import 'dart:io';

import 'package:saropa_lints/src/init/display.dart';
import 'package:saropa_lints/src/init/log_writer.dart';
import 'package:saropa_lints/src/init/platforms_packages.dart';
import 'package:saropa_lints/src/init/stylistic_section_parser.dart';
import 'package:saropa_lints/src/tiers.dart' as tiers;
import 'package:saropa_lints/src/string_slice_utils.dart';

/// Extract rule overrides from analysis_options_custom.yaml.
///
/// Supports multiple formats:
/// ```yaml
/// # Custom rule overrides (survives --reset)
/// avoid_print: false  # Allow print in this project
/// - avoid_null_assertion: false # With hyphen prefix
///   - require_error_widget: false # Indented with hyphen
/// prefer_const_constructors: true
/// ```
///
/// These overrides are always applied, even when using --reset.
Map<String, bool> extractOverridesFromFile(File file, Set<String> allRules) {
  final Map<String, bool> overrides = <String, bool>{};

  if (!file.existsSync()) {
    return overrides;
  }

  final content = file.readAsStringSync();

  // Match rule entries with optional hyphen, indentation, and trailing comments:
  // - rule_name: true/false # optional comment
  //   rule_name: true/false
  // rule_name: false
  final rulePattern = RegExp(
    r'^\s*-?\s*([\w_]+):\s*(true|false)',
    multiLine: true,
  );

  for (final match in rulePattern.allMatches(content)) {
    final ruleName = match.group(1);
    if (ruleName == null) continue;
    final enabled = match.group(2) == 'true';

    // Only include rules we know about
    if (allRules.contains(ruleName)) {
      overrides[ruleName] = enabled;
    }
  }

  return overrides;
}

/// Create a minimal analysis_options_custom.yaml file.
///
/// Contains only: analysis settings, platform settings, and the RULE OVERRIDES
/// section. Packages are auto-detected from pubspec; stylistic rules are
/// managed via --no-stylistic/--stylistic-all flags and rule overrides.
void createCustomOverridesFile(File file) {
  file.writeAsStringSync(buildMinimalConfig(tiers.defaultPlatforms, {}));
}

/// Build the minimal config file content.
///
/// Keeps only analysis settings, platform settings, and rule overrides.
/// Packages and stylistic sections are no longer written — packages are
/// auto-detected from pubspec, stylistic choices go in RULE OVERRIDES.
String buildMinimalConfig(
  Map<String, bool> platforms,
  Map<String, bool> ruleOverrides, {
  int maxIssues = 500,
  String output = 'both',
}) {
  final buf = StringBuffer();

  // Bold ASCII-box notice directing users to the extension
  buf.writeln(
    '# ╔═══════════════════════════════════════════════════════════════════════════╗',
  );
  buf.writeln(
    '# ║  DO NOT EDIT THIS FILE MANUALLY                                         ║',
  );
  buf.writeln(
    '# ║  Use the Saropa Lints VS Code extension to manage rule overrides.       ║',
  );
  buf.writeln(
    '# ║  Manual edits may be overwritten by the extension or init.              ║',
  );
  buf.writeln(
    '# ╚═══════════════════════════════════════════════════════════════════════════╝',
  );
  buf.writeln();
  buf.writeln('# SAROPA LINTS CUSTOM CONFIG');
  buf.writeln('# Settings that persist across tier changes and --reset.');
  buf.writeln();

  buf.writeln('# ANALYSIS SETTINGS');
  buf.writeln('max_issues: $maxIssues');
  buf.writeln('output: $output');
  // log_level and lane live here (not under plugins > saropa_lints: in
  // analysis_options.yaml) to avoid unsupported_option warnings from the
  // Dart SDK's plugin-block validator, which hardcodes the allowed key set.
  buf.writeln('log_level: info # off | error | warning | info | debug');
  buf.writeln('# lane: light # full | light (default when absent: light)');
  // shed_rules opts into graduated rule shedding under memory pressure —
  // commented out (off) by default so diagnostics never silently vanish
  // unless the user explicitly asks for the RSS trade-off.
  buf.writeln(
    '# shed_rules: false # true disables low-severity rules under memory pressure',
  );
  buf.writeln();

  // rule_packs lives here (not under plugins > saropa_lints:) to avoid
  // unsupported_option warnings from the SDK's plugin-block validator.
  buf.writeln('# RULE PACKS');
  buf.writeln('# Enable migration / compatibility packs by uncommenting:');
  buf.writeln('# rule_packs:');
  buf.writeln('#   enabled:');
  buf.writeln('#     - collection_compat');
  buf.writeln('#     - dart_sdk_3_2');
  buf.writeln();

  // Platform settings (no auto-detection available — user controls these)
  buf.writeln('# PLATFORM SETTINGS');
  buf.writeln("# Disable platforms your project doesn't target.");
  buf.writeln('platforms:');
  for (final entry in platforms.entries) {
    buf.writeln('  ${entry.key}: ${entry.value}');
  }
  buf.writeln();

  // Rule overrides section header (must match configWriter.ts OVERRIDES_MARKER)
  buf.writeln('# ${'─' * 77}');
  buf.writeln('# RULE OVERRIDES');
  buf.writeln('# ${'─' * 77}');
  buf.writeln('# FORMAT: rule_name: true/false');
  buf.writeln('# Add your custom rule overrides below:');
  buf.writeln();

  // Write any migrated overrides (sorted for stable output)
  final sorted = ruleOverrides.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  for (final entry in sorted) {
    buf.writeln('${entry.key}: ${entry.value}');
  }

  return buf.toString();
}

/// Migrate old bloated custom config to minimal format (one-time).
///
/// Detects the old format by presence of `# STYLISTIC RULES` section.
/// Extracts max_issues, output, platforms, enabled stylistic rules, and
/// existing rule overrides. Backs up old file as .bak, writes minimal.
/// If [logLine] is non-null, it is called instead of [log.terminal] (for headless use).
void migrateToMinimalFormat(
  File file,
  Set<String> stylisticRules, {
  void Function(String)? logLine,
}) {
  final content = file.readAsStringSync();

  // Already minimal — no stylistic section to migrate from.
  if (!stylisticSectionHeaderPattern.hasMatch(content)) return;

  // Extract current analysis settings
  final maxIssues = _extractMaxIssues(content);
  final output = _extractOutput(content);

  // Extract current platform settings
  final platforms = extractPlatformsFromFile(file);

  // Extract enabled stylistic rules to migrate into RULE OVERRIDES.
  // Only true entries matter — false is the default with --no-stylistic.
  final stylisticValues = extractStylisticSectionValues(content);
  final enabledStylistic = <String, bool>{};
  for (final entry in stylisticValues.entries) {
    if (entry.value) enabledStylistic[entry.key] = true;
  }

  // Extract existing rule overrides (from RULE OVERRIDES section only)
  final existingOverrides = extractOverrideSectionValues(content);

  // Merge: existing overrides take priority over migrated stylistic
  final allOverrides = <String, bool>{
    ...enabledStylistic,
    ...existingOverrides,
  };

  // Backup old file before rewriting
  final backupPath = _uniqueBackupPath(file.path);
  File(backupPath).writeAsStringSync(content);
  // Use split on both / and \ so the filename displays correctly on Windows
  final backupName = backupPath.split(RegExp(r'[/\\]')).last;
  final report = logLine ?? log.terminal;
  report(
    '${InitColors.dim}Backed up old config as '
    '$backupName${InitColors.reset}',
  );

  // Write minimal format with preserved analysis settings
  file.writeAsStringSync(
    buildMinimalConfig(
      platforms,
      allOverrides,
      maxIssues: maxIssues,
      output: output,
    ),
  );

  final stylisticCount = enabledStylistic.length;
  final overrideCount = existingOverrides.length;
  report(
    '${InitColors.green}✓ Migrated to minimal config${InitColors.reset}${stylisticCount > 0 ? ' ($stylisticCount stylistic → overrides)' : ''}${overrideCount > 0 ? ' ($overrideCount existing overrides kept)' : ''}',
  );
}

/// Extract max_issues value from file content. Returns 500 if not found.
int _extractMaxIssues(String content) {
  final match = RegExp(
    r'^max_issues:\s*(\d+)',
    multiLine: true,
  ).firstMatch(content);
  if (match == null) return 500;
  return int.tryParse(match.group(1)!) ?? 500;
}

/// Extract output value from file content. Returns 'both' if not found.
String _extractOutput(String content) {
  final match = RegExp(
    r'^output:\s*(\w+)',
    multiLine: true,
  ).firstMatch(content);
  return match?.group(1) ?? 'both';
}

/// Generate a unique backup path, appending date if .bak already exists.
String _uniqueBackupPath(String originalPath) {
  final basePath = '$originalPath.bak';
  if (!File(basePath).existsSync()) return basePath;

  final now = DateTime.now();
  final stamp =
      '${now.year}'
      '${now.month.toString().padLeft(2, '0')}'
      '${now.day.toString().padLeft(2, '0')}';
  return '$originalPath.bak.$stamp';
}

/// Ensure max_issues setting exists in an existing custom config file.
///
/// Added in v4.9.1 - older files won't have this setting, so we add it
/// at the top of the file if missing.
/// If [logLine] is non-null, it is called instead of [log.terminal] (for headless use).
void ensureMaxIssuesSetting(File file, {void Function(String)? logLine}) {
  var content = file.readAsStringSync();

  final hasMaxIssues = RegExp(
    r'^max_issues:\s*\d+',
    multiLine: true,
  ).hasMatch(content);
  final hasOutput = RegExp(
    r'^output:\s*\w+',
    multiLine: true,
  ).hasMatch(content);

  if (hasMaxIssues && hasOutput) return; // Both settings present

  final report = logLine ?? log.terminal;
  if (!hasMaxIssues) {
    // Neither setting exists — add the full block
    content = addAnalysisSettingsBlock(content);
    file.writeAsStringSync(content);
    report(
      '${InitColors.green}✓ Added analysis settings to '
      '${file.path}${InitColors.reset}',
    );

    return;
  }

  // max_issues exists but output is missing — add output after max_issues
  if (!hasOutput) {
    content = addOutputSetting(content);
    file.writeAsStringSync(content);
    report(
      '${InitColors.green}✓ Added output setting to '
      '${file.path}${InitColors.reset}',
    );
  }
}

/// Add the full analysis settings block (max_issues + output).
///
/// Inserts after the file header comment. Handles both old-format (ASCII box)
/// and new minimal-format (single-line) headers.
String addAnalysisSettingsBlock(String content) {
  const settingBlock = '''
# ANALYSIS SETTINGS
max_issues: 500
output: both

''';

  // Try old ASCII box header first, then minimal header
  final headerEndMatch =
      RegExp(r'╚[═]+╝\n*').firstMatch(content) ??
      RegExp(
        r'^# SAROPA LINTS CUSTOM CONFIG\n[^\n]*\n*',
        multiLine: true,
      ).firstMatch(content);

  if (headerEndMatch != null) {
    final insertPos = headerEndMatch.end;
    return '${content.prefix(insertPos)}\n$settingBlock${content.afterIndex(insertPos)}';
  }

  return settingBlock + content;
}

/// Add just the output setting after an existing max_issues line.
String addOutputSetting(String content) {
  final maxIssuesMatch = RegExp(
    r'^(max_issues:\s*\d+.*)\n',
    multiLine: true,
  ).firstMatch(content);

  if (maxIssuesMatch == null) return content;

  final insertPos = maxIssuesMatch.end;
  const outputLine = 'output: both\n';

  return content.prefix(insertPos) + outputLine + content.afterIndex(insertPos);
}

// ---------------------------------------------------------------------------
// rule_packs in analysis_options_custom.yaml
// ---------------------------------------------------------------------------

/// Pattern matching a top-level `rule_packs:` block (with `enabled:` list).
///
/// Only matches indented children (at least one leading space) so it cannot
/// eat into the next section's unindented comments or headers.
final _rulePacksBlockPattern = RegExp(
  r'^rule_packs:\s*\n(?:\s+\S[^\n]*\n)*',
  multiLine: true,
);

/// Writes (or replaces) the top-level `rule_packs:` block in [customFile].
///
/// If [packIds] is empty, any existing block is removed. If non-empty, the
/// block is written sorted alphabetically. Creates the file if it doesn't
/// exist, inserting after the `# ANALYSIS SETTINGS` section when present.
void writeRulePacksToCustomFile(File customFile, List<String> packIds) {
  var content = customFile.existsSync() ? customFile.readAsStringSync() : '';

  // Build the new block (empty string if no packs).
  final block = _buildRulePacksBlock(packIds);

  if (_rulePacksBlockPattern.hasMatch(content)) {
    // Replace existing block.
    content = content.replaceFirst(_rulePacksBlockPattern, block);
  } else if (block.isNotEmpty) {
    // Insert new block. Prefer after the commented-out rule_packs template
    // (from buildMinimalConfig), otherwise after `# RULE PACKS` header,
    // otherwise before `# PLATFORM SETTINGS` or `platforms:`.
    content = _insertRulePacksBlock(content, block);
  }

  // Remove any commented-out template lines that the block replaces.
  if (block.isNotEmpty) {
    content = _removeRulePacksTemplate(content);
  }

  customFile.writeAsStringSync(content);
}

/// Builds the YAML text for a `rule_packs:` block (top-level, no indentation).
String _buildRulePacksBlock(List<String> packIds) {
  if (packIds.isEmpty) return '';
  final sorted = List<String>.of(packIds)..sort();
  final buf = StringBuffer();
  buf.writeln('rule_packs:');
  buf.writeln('  enabled:');
  for (final id in sorted) {
    buf.writeln('    - $id');
  }
  return buf.toString();
}

/// Insert rule_packs block at a sensible location in the custom file.
String _insertRulePacksBlock(String content, String block) {
  // After `# RULE PACKS` header line (from template).
  final headerMatch = RegExp(
    r'^# RULE PACKS\n',
    multiLine: true,
  ).firstMatch(content);
  if (headerMatch != null) {
    // Skip past comment lines belonging to the template — stop at the first
    // blank line so we don't eat into the next section's header comments.
    var pos = headerMatch.end;
    final lines = content.substring(pos).split('\n');
    for (final line in lines) {
      if (line.trim().isEmpty) {
        // Consume the blank line separator, then stop.
        pos += line.length + 1;
        break;
      }
      if (line.trimLeft().startsWith('#')) {
        pos += line.length + 1;
      } else {
        break;
      }
    }
    return content.prefix(pos) + block + content.afterIndex(pos);
  }

  // Before `# PLATFORM SETTINGS` or `platforms:`.
  final platformMatch = RegExp(
    r'^(?:# PLATFORM SETTINGS|platforms:)',
    multiLine: true,
  ).firstMatch(content);
  if (platformMatch != null) {
    return '${content.prefix(platformMatch.start)}$block\n${content.afterIndex(platformMatch.start)}';
  }

  // Fallback: append before end.
  if (content.isNotEmpty && !content.endsWith('\n')) {
    return '$content\n$block';
  }
  return '$content$block';
}

/// Remove the commented-out `# RULE PACKS` template (header + comment lines).
///
/// Stops at the first blank line so it cannot eat into the next section's
/// `# PLATFORM SETTINGS` header or other unrelated comments.
String _removeRulePacksTemplate(String content) {
  return content.replaceAll(
    RegExp(
      r'^# RULE PACKS\n(?:#[^\n]*\n)*(?:\n)?',
      multiLine: true,
    ),
    '',
  );
}
