/// Core custom overrides file management.
///
/// Handles file creation, rule extraction, analysis settings, and migration
/// from the old bloated format to the minimal format (I3).
library;

import 'dart:io';

import 'package:saropa_lints/src/init/display.dart';
import 'package:saropa_lints/src/init/log_writer.dart';
import 'package:saropa_lints/src/init/platforms_packages.dart';
import 'package:saropa_lints/src/init/stylistic_section_parser.dart';
import 'package:saropa_lints/src/tiers.dart' as tiers;

/// Extract rule overrides from analysis_options_custom.yaml.
///
/// Supports multiple formats:
/// ```yaml
/// # Custom rule overrides (survives --reset)
/// avoid_print: false  # Allow print in this project
/// - avoid_null_assertion: false # With hyphen prefix
///   - require_error_widget: false # Indented with hyphen
/// prefer_const_constructors: true
/// ```
///
/// These overrides are always applied, even when using --reset.
Map<String, bool> extractOverridesFromFile(File file, Set<String> allRules) {
  final Map<String, bool> overrides = <String, bool>{};

  if (!file.existsSync()) {
    return overrides;
  }

  final content = file.readAsStringSync();

  // Match rule entries with optional hyphen, indentation, and trailing comments:
  // - rule_name: true/false # optional comment
  //   rule_name: true/false
  // rule_name: false
  final rulePattern = RegExp(
    r'^\s*-?\s*([\w_]+):\s*(true|false)',
    multiLine: true,
  );

  for (final match in rulePattern.allMatches(content)) {
    final ruleName = match.group(1);
    if (ruleName == null) continue;
    final enabled = match.group(2) == 'true';

    // Only include rules we know about
    if (allRules.contains(ruleName)) {
      overrides[ruleName] = enabled;
    }
  }

  return overrides;
}

/// Create a minimal analysis_options_custom.yaml file.
///
/// Contains only: analysis settings, platform settings, and the RULE OVERRIDES
/// section. Packages are auto-detected from pubspec; stylistic rules are
/// managed via --no-stylistic/--stylistic-all flags and rule overrides.
void createCustomOverridesFile(File file) {
  file.writeAsStringSync(buildMinimalConfig(tiers.defaultPlatforms, {}));
}

/// Build the minimal config file content.
///
/// Keeps only analysis settings, platform settings, and rule overrides.
/// Packages and stylistic sections are no longer written — packages are
/// auto-detected from pubspec, stylistic choices go in RULE OVERRIDES.
String buildMinimalConfig(
  Map<String, bool> platforms,
  Map<String, bool> ruleOverrides, {
  int maxIssues = 500,
  String output = 'both',
}) {
  final buf = StringBuffer();

  // Bold ASCII-box notice directing users to the extension
  buf.writeln(
    '# ╔═══════════════════════════════════════════════════════════════════════════╗',
  );
  buf.writeln(
    '# ║  DO NOT EDIT THIS FILE MANUALLY                                         ║',
  );
  buf.writeln(
    '# ║  Use the Saropa Lints VS Code extension to manage rule overrides.       ║',
  );
  buf.writeln(
    '# ║  Manual edits may be overwritten by the extension or init.              ║',
  );
  buf.writeln(
    '# ╚═══════════════════════════════════════════════════════════════════════════╝',
  );
  buf.writeln();
  buf.writeln('# SAROPA LINTS CUSTOM CONFIG');
  buf.writeln('# Settings that persist across tier changes and --reset.');
  buf.writeln();

  buf.writeln('# ANALYSIS SETTINGS');
  buf.writeln('max_issues: $maxIssues');
  buf.writeln('output: $output');
  buf.writeln();

  // Platform settings (no auto-detection available — user controls these)
  buf.writeln('# PLATFORM SETTINGS');
  buf.writeln("# Disable platforms your project doesn't target.");
  buf.writeln('platforms:');
  for (final entry in platforms.entries) {
    buf.writeln('  ${entry.key}: ${entry.value}');
  }
  buf.writeln();

  // Rule overrides section header (must match configWriter.ts OVERRIDES_MARKER)
  buf.writeln('# ${'─' * 77}');
  buf.writeln('# RULE OVERRIDES');
  buf.writeln('# ${'─' * 77}');
  buf.writeln('# FORMAT: rule_name: true/false');
  buf.writeln('# Add your custom rule overrides below:');
  buf.writeln();

  // Write any migrated overrides (sorted for stable output)
  final sorted = ruleOverrides.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  for (final entry in sorted) {
    buf.writeln('${entry.key}: ${entry.value}');
  }

  return buf.toString();
}

/// Migrate old bloated custom config to minimal format (one-time).
///
/// Detects the old format by presence of `# STYLISTIC RULES` section.
/// Extracts max_issues, output, platforms, enabled stylistic rules, and
/// existing rule overrides. Backs up old file as .bak, writes minimal.
/// If [logLine] is non-null, it is called instead of [log.terminal] (for headless use).
void migrateToMinimalFormat(
  File file,
  Set<String> stylisticRules, {
  void Function(String)? logLine,
}) {
  final content = file.readAsStringSync();

  // Already minimal — no stylistic section to migrate from.
  if (!stylisticSectionHeaderPattern.hasMatch(content)) return;

  // Extract current analysis settings
  final maxIssues = _extractMaxIssues(content);
  final output = _extractOutput(content);

  // Extract current platform settings
  final platforms = extractPlatformsFromFile(file);

  // Extract enabled stylistic rules to migrate into RULE OVERRIDES.
  // Only true entries matter — false is the default with --no-stylistic.
  final stylisticValues = extractStylisticSectionValues(content);
  final enabledStylistic = <String, bool>{};
  for (final entry in stylisticValues.entries) {
    if (entry.value) enabledStylistic[entry.key] = true;
  }

  // Extract existing rule overrides (from RULE OVERRIDES section only)
  final existingOverrides = extractOverrideSectionValues(content);

  // Merge: existing overrides take priority over migrated stylistic
  final allOverrides = <String, bool>{
    ...enabledStylistic,
    ...existingOverrides,
  };

  // Backup old file before rewriting
  final backupPath = _uniqueBackupPath(file.path);
  File(backupPath).writeAsStringSync(content);
  // Use split on both / and \ so the filename displays correctly on Windows
  final backupName = backupPath.split(RegExp(r'[/\\]')).last;
  final report = logLine ?? log.terminal;
  report(
    '${InitColors.dim}Backed up old config as '
    '$backupName${InitColors.reset}',
  );

  // Write minimal format with preserved analysis settings
  file.writeAsStringSync(
    buildMinimalConfig(
      platforms,
      allOverrides,
      maxIssues: maxIssues,
      output: output,
    ),
  );

  final stylisticCount = enabledStylistic.length;
  final overrideCount = existingOverrides.length;
  report(
    '${InitColors.green}✓ Migrated to minimal config${InitColors.reset}'
    '${stylisticCount > 0 ? ' ($stylisticCount stylistic → overrides)' : ''}'
    '${overrideCount > 0 ? ' ($overrideCount existing overrides kept)' : ''}',
  );
}

/// Extract max_issues value from file content. Returns 500 if not found.
int _extractMaxIssues(String content) {
  final match = RegExp(
    r'^max_issues:\s*(\d+)',
    multiLine: true,
  ).firstMatch(content);
  if (match == null) return 500;
  return int.tryParse(match.group(1)!) ?? 500;
}

/// Extract output value from file content. Returns 'both' if not found.
String _extractOutput(String content) {
  final match = RegExp(
    r'^output:\s*(\w+)',
    multiLine: true,
  ).firstMatch(content);
  return match?.group(1) ?? 'both';
}

/// Generate a unique backup path, appending date if .bak already exists.
String _uniqueBackupPath(String originalPath) {
  final basePath = '$originalPath.bak';
  if (!File(basePath).existsSync()) return basePath;

  final now = DateTime.now();
  final stamp =
      '${now.year}'
      '${now.month.toString().padLeft(2, '0')}'
      '${now.day.toString().padLeft(2, '0')}';
  return '$originalPath.bak.$stamp';
}

/// Ensure max_issues setting exists in an existing custom config file.
///
/// Added in v4.9.1 - older files won't have this setting, so we add it
/// at the top of the file if missing.
/// If [logLine] is non-null, it is called instead of [log.terminal] (for headless use).
void ensureMaxIssuesSetting(File file, {void Function(String)? logLine}) {
  var content = file.readAsStringSync();

  final hasMaxIssues = RegExp(
    r'^max_issues:\s*\d+',
    multiLine: true,
  ).hasMatch(content);
  final hasOutput = RegExp(
    r'^output:\s*\w+',
    multiLine: true,
  ).hasMatch(content);

  if (hasMaxIssues && hasOutput) return; // Both settings present

  final report = logLine ?? log.terminal;
  if (!hasMaxIssues) {
    // Neither setting exists — add the full block
    content = addAnalysisSettingsBlock(content);
    file.writeAsStringSync(content);
    report(
      '${InitColors.green}✓ Added analysis settings to '
      '${file.path}${InitColors.reset}',
    );
    return;
  }

  // max_issues exists but output is missing — add output after max_issues
  if (!hasOutput) {
    content = addOutputSetting(content);
    file.writeAsStringSync(content);
    report(
      '${InitColors.green}✓ Added output setting to '
      '${file.path}${InitColors.reset}',
    );
  }
}

/// Add the full analysis settings block (max_issues + output).
///
/// Inserts after the file header comment. Handles both old-format (ASCII box)
/// and new minimal-format (single-line) headers.
String addAnalysisSettingsBlock(String content) {
  const settingBlock = '''
# ANALYSIS SETTINGS
max_issues: 500
output: both

''';

  // Try old ASCII box header first, then minimal header
  final headerEndMatch =
      RegExp(r'╚[═]+╝\n*').firstMatch(content) ??
      RegExp(
        r'^# SAROPA LINTS CUSTOM CONFIG\n[^\n]*\n*',
        multiLine: true,
      ).firstMatch(content);

  if (headerEndMatch != null) {
    final insertPos = headerEndMatch.end;
    return content.substring(0, insertPos) +
        '\n' +
        settingBlock +
        content.substring(insertPos);
  }

  return settingBlock + content;
}

/// Add just the output setting after an existing max_issues line.
String addOutputSetting(String content) {
  final maxIssuesMatch = RegExp(
    r'^(max_issues:\s*\d+.*)\n',
    multiLine: true,
  ).firstMatch(content);

  if (maxIssuesMatch == null) return content;

  final insertPos = maxIssuesMatch.end;
  const outputLine = 'output: both\n';

  return content.substring(0, insertPos) +
      outputLine +
      content.substring(insertPos);
}
