/// Writes a GitHub Actions workflow that calls the `saropa/saropa_lints`
/// composite action (see `action.yml` at the repo root).
library;

// Filesystem output for `--emit-ci`. Mirrors composite_plugin_scaffold.dart's
// approach: a plain string template written verbatim, no templating engine.
import 'dart:io';

import 'package:saropa_lints/saropa_lints.dart' show saropaLintsVersion;

/// Outcome of an [emitCiWorkflow] call, so the caller (init_runner.dart) can
/// report the right message without re-deriving what happened from the
/// filesystem.
enum EmitCiResult {
  /// File did not exist and `--dry-run` was not set: written to disk.
  written,

  /// File did not exist but `--dry-run` was set: nothing written.
  wouldWrite,

  /// File already exists: refused. `--emit-ci` never overwrites — a
  /// generated workflow a human has since hand-edited must not be silently
  /// clobbered, and the `managed-by` marker only means anything if we never
  /// touch a file we didn't just create.
  refusedExists,
}

/// Builds the workflow body written by [emitCiWorkflow].
///
/// Kept in sync with the "GitHub Actions CI with SARIF" example in
/// doc/guides/cli.md — that doc is the hand-authored reference, this is the
/// generated copy of it.
///
/// The action reference is pinned to the exact saropa_lints version doing the
/// generating, resolved at runtime from the consumer's package_config.json.
/// That is self-consistent by construction: a release old enough to lack
/// `action.yml` at its tag is also too old to have `--emit-ci`, so any version
/// that can reach this code has an action to point at.
///
/// A hardcoded pin cannot make that guarantee, and did not: this was written
/// as `v16.2.1`, a tag that predates `action.yml` entirely, so every workflow
/// it generated referenced an action that could not resolve.
///
/// Never a moving major like `@v16` — the release process creates exact tags
/// only, so that would not resolve either.
String buildCiWorkflow({String? version}) {
  final String resolved = version ?? saropaLintsVersion;

  // 'unknown' means package_config.json could not be read. Emitting
  // `@vunknown` would be a broken reference dressed up as a real one, so
  // fall back to the default branch and say so in the generated file rather
  // than leaving a silent trap for whoever pushes it.
  final bool known = resolved != 'unknown';
  final String ref = known ? 'v$resolved' : 'main';
  final String note = known
      ? ''
      : '#\n'
          '# NOTE: the saropa_lints version could not be determined, so this\n'
          '# references the default branch rather than a release tag. Pin it\n'
          '# to the version you depend on before relying on this in CI.\n';

  return '''
# Generated by saropa_lints init --emit-ci
# managed-by: saropa_lints
$note
name: saropa_lints

on:
  pull_request:
    paths: ['**.dart']

permissions:
  security-events: write   # required for the SARIF upload
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: saropa/saropa_lints@$ref
        with:
          since: origin/\${{ github.base_ref }}   # changed files only
          mode: annotate                        # annotate | gate | both
''';
}

/// Writes [buildCiWorkflow]'s output to [outputFile].
///
/// Never overwrites an existing file (see [EmitCiResult.refusedExists]);
/// under `--dry-run` reports what it would do without touching disk.
EmitCiResult emitCiWorkflow(File outputFile, {required bool dryRun}) {
  if (outputFile.existsSync()) {
    return EmitCiResult.refusedExists;
  }

  if (dryRun) {
    return EmitCiResult.wouldWrite;
  }

  final Directory parent = outputFile.parent;
  if (!parent.existsSync()) {
    parent.createSync(recursive: true);
  }
  outputFile.writeAsStringSync(buildCiWorkflow());

  return EmitCiResult.written;
}
