/// Writes a GitHub Actions workflow that calls the `saropa/saropa_lints`
/// composite action (see `action.yml` at the repo root).
library;

// Filesystem output for `--emit-ci`. Mirrors composite_plugin_scaffold.dart's
// approach: a plain string template written verbatim, no templating engine.
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:saropa_lints/saropa_lints.dart' show saropaLintsVersion;

/// Outcome of an [emitCiWorkflow] call, so the caller (init_runner.dart) can
/// report the right message without re-deriving what happened from the
/// filesystem.
enum EmitCiResult {
  /// File did not exist and `--dry-run` was not set: written to disk.
  written,

  /// File did not exist but `--dry-run` was set: nothing written.
  wouldWrite,

  /// File already exists: refused. `--emit-ci` never overwrites — a
  /// generated workflow a human has since hand-edited must not be silently
  /// clobbered, and the `managed-by` marker only means anything if we never
  /// touch a file we didn't just create.
  refusedExists,
}

/// Builds the workflow body written by [emitCiWorkflow].
///
/// Kept in sync with the "GitHub Actions CI with SARIF" example in
/// doc/guides/cli.md — that doc is the hand-authored reference, this is the
/// generated copy of it.
///
/// The action reference is pinned to the exact saropa_lints version doing the
/// generating, resolved at runtime from the consumer's package_config.json.
/// That is self-consistent by construction: a release old enough to lack
/// `action.yml` at its tag is also too old to have `--emit-ci`, so any version
/// that can reach this code has an action to point at.
///
/// A hardcoded pin cannot make that guarantee, and did not: this was written
/// as `v16.2.1`, a tag that predates `action.yml` entirely, so every workflow
/// it generated referenced an action that could not resolve.
///
/// Deliberately the exact version rather than the moving major (`@v16`) that
/// the release script also maintains: a generated file should pin to the
/// release it was generated against, so regenerating is the only thing that
/// can change which action runs.
/// True when [projectDir] has no saropa_lints rule configuration, so the
/// generated `scan` would exit 2 unless the workflow names a tier.
///
/// Deliberately a substring check rather than a YAML parse: configuration
/// reaches analysis_options.yaml several ways — a tier `include:`, an
/// init-generated per-rule block, a `plugins:` section — and every one of them
/// mentions saropa_lints. Absence is the signal worth acting on.
///
/// Mirrors `needsExplicitTier` in the extension's `ciWorkflow.ts`, because the
/// card and this command must generate the identical file.
bool ciNeedsExplicitTier(Directory projectDir) {
  try {
    final File options = File(p.join(projectDir.path, 'analysis_options.yaml'));
    if (!options.existsSync()) {
      return true;
    }
    return !options.readAsStringSync().contains('saropa_lints');
  } on Object {
    // An unreadable file is indistinguishable from an absent one here, and
    // guessing "configured" would generate a workflow that exits 2.
    return true;
  }
}

String buildCiWorkflow({String? version, String? tier}) {
  final String resolved = version ?? saropaLintsVersion;

  // Emitted only when the project has no rule configuration of its own.
  // Naming a tier for a project that IS configured would override the rule
  // set the team already chose; omitting it for one that is not produces a
  // `scan` that exits 2 on the workflow's very first run.
  final String tierLine = tier == null ? '' : '\n          tier: $tier';

  // 'unknown' means package_config.json could not be read. Emitting
  // `@vunknown` would be a broken reference dressed up as a real one, so
  // fall back to the default branch and say so in the generated file rather
  // than leaving a silent trap for whoever pushes it.
  final bool known = resolved != 'unknown';
  final String ref = known ? 'v$resolved' : 'main';
  final String note = known
      ? ''
      : '#\n'
            '# NOTE: the saropa_lints version could not be determined, so this\n'
            '# references the default branch rather than a release tag. Pin it\n'
            '# to the version you depend on before relying on this in CI.\n';

  return '''
# Generated by saropa_lints init --emit-ci
# managed-by: saropa_lints
$note
name: saropa_lints

on:
  pull_request:
    paths: ['**.dart']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: saropa/saropa_lints@$ref
        # Reports; does not block. Remove this line to make a finding fail the
        # pull request once the project is clean enough to enforce.
        continue-on-error: true
        with:
          # gate runs the `scan` command, which honors THIS project's
          # analysis_options.yaml — the tier and per-rule choices already made
          # here. The alternative, annotate, runs every rule regardless of
          # configured tier, which on a 2332-rule set means findings from rules
          # the project never enabled.
          mode: gate$tierLine
''';
}

/// Writes [buildCiWorkflow]'s output to [outputFile].
///
/// Never overwrites an existing file (see [EmitCiResult.refusedExists]);
/// under `--dry-run` reports what it would do without touching disk.
///
/// [projectDir] is the project the workflow is being written for. It decides
/// whether a `tier:` input is needed — see [ciNeedsExplicitTier]. When
/// omitted, the file is generated without one.
EmitCiResult emitCiWorkflow(
  File outputFile, {
  required bool dryRun,
  Directory? projectDir,
}) {
  if (outputFile.existsSync()) {
    return EmitCiResult.refusedExists;
  }

  if (dryRun) {
    return EmitCiResult.wouldWrite;
  }

  final Directory parent = outputFile.parent;
  if (!parent.existsSync()) {
    parent.createSync(recursive: true);
  }
  outputFile.writeAsStringSync(
    buildCiWorkflow(
      tier: projectDir != null && ciNeedsExplicitTier(projectDir)
          ? 'recommended'
          : null,
    ),
  );

  return EmitCiResult.written;
}
