/// Writes a GitHub Actions workflow that calls the `saropa/saropa_lints`
/// composite action (see `action.yml` at the repo root).
library;

// Filesystem output for `--emit-ci`. Mirrors composite_plugin_scaffold.dart's
// approach: a plain string template written verbatim, no templating engine.
import 'dart:io';

/// Outcome of an [emitCiWorkflow] call, so the caller (init_runner.dart) can
/// report the right message without re-deriving what happened from the
/// filesystem.
enum EmitCiResult {
  /// File did not exist and `--dry-run` was not set: written to disk.
  written,

  /// File did not exist but `--dry-run` was set: nothing written.
  wouldWrite,

  /// File already exists: refused. `--emit-ci` never overwrites — a
  /// generated workflow a human has since hand-edited must not be silently
  /// clobbered, and the `managed-by` marker only means anything if we never
  /// touch a file we didn't just create.
  refusedExists,
}

/// The workflow body written by [emitCiWorkflow].
///
/// Kept in sync with the "GitHub Actions CI with SARIF" example in
/// doc/guides/cli.md — that doc is the hand-authored reference, this is the
/// generated copy of it. The `@v16.2.1` pin is deliberate: the release
/// process only ever creates exact-version tags (no moving `@v16`), so a
/// generated workflow must reference a tag that is guaranteed to resolve.
const String ciWorkflowTemplate = '''
# Generated by saropa_lints init --emit-ci
# managed-by: saropa_lints
name: saropa_lints

on:
  pull_request:
    paths: ['**.dart']

permissions:
  security-events: write   # required for the SARIF upload
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: saropa/saropa_lints@v16.2.1
        with:
          since: origin/\${{ github.base_ref }}   # changed files only
          mode: annotate                        # annotate | gate | both
''';

/// Writes [ciWorkflowTemplate] to [outputFile].
///
/// Never overwrites an existing file (see [EmitCiResult.refusedExists]);
/// under `--dry-run` reports what it would do without touching disk.
EmitCiResult emitCiWorkflow(File outputFile, {required bool dryRun}) {
  if (outputFile.existsSync()) {
    return EmitCiResult.refusedExists;
  }

  if (dryRun) {
    return EmitCiResult.wouldWrite;
  }

  final Directory parent = outputFile.parent;
  if (!parent.existsSync()) {
    parent.createSync(recursive: true);
  }
  outputFile.writeAsStringSync(ciWorkflowTemplate);

  return EmitCiResult.written;
}
