analyzer:
  plugins:
    - custom_lint
  errors:
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    todo: ignore
    fixme: ignore
    hack: ignore

# Configure saropa_lints tier
custom_lint:
  saropa_lints:
    tier: recommended
  rules:
    - prefer_async_callback: true
    - avoid_debug_print: true
    - avoid_print_in_production: true
    - prefer_where_or_null: true
    - prefer_explicit_type_arguments: true
    - require_dispose: false
    - avoid_undisposed_instances: false
