// ignore_for_file: depend_on_referenced_packages

/// Custom lint rules for Saropa codebase.
///
/// To use these rules:
/// 1. Add `custom_lint: ^0.8.0` to dev_dependencies in pubspec.yaml
/// 2. Add `analyzer: plugins: - custom_lint` to analysis_options.yaml
/// 3. Run `dart run custom_lint` to check for issues
library;

import 'package:custom_lint_builder/custom_lint_builder.dart';

import 'package:saropa_lints/src/rules/all_rules.dart';

// Export all rule classes for documentation
export 'package:saropa_lints/src/rules/all_rules.dart';

/// Entry point for custom_lint
PluginBase createPlugin() => _SaropaLints();

/// All available rules - instantiated once
const List<LintRule> _allRules = <LintRule>[
  // Core rules
  AlwaysFailRule(),
  AvoidNullAssertionRule(),
  AvoidDebugPrintRule(),
  AvoidUnguardedDebugRule(),
  PreferConstStringListRule(),
  AvoidContextInInitStateDisposeRule(),
  AvoidIsarEnumFieldRule(),
  AvoidAdjacentStringsRule(),
  AvoidContinueRule(),
  AvoidEmptySpreadRule(),
  AvoidOnlyRethrowRule(),
  NoEmptyStringRule(),
  PreferContainsRule(),
  PreferFirstRule(),
  RequireDisposeRule(),
  AvoidMisnamedPaddingRule(),
  AvoidUnsafeSetStateRule(),
  AvoidRedundantElseRule(),
  AvoidDuplicateMapKeysRule(),
  AvoidNestedSwitchesRule(),
  AvoidLocalFunctionsRule(),
  AvoidUnnecessarySuperRule(),
  AvoidNestedFuturesRule(),
  AvoidOneFieldRecordsRule(),
  AvoidNestedTryRule(),
  AvoidMapKeysContainsRule(),
  AvoidEmptySetStateRule(),
  AvoidSingleChildColumnRowRule(),
  AvoidLongParameterListRule(),
  PreferBooleanPrefixesRule(),
  AvoidReturningCascadesRule(),
  AvoidPositionalRecordFieldAccessRule(),
  AvoidDeclaringCallMethodRule(),
  AvoidNestedStreamsAndFuturesRule(),
  AvoidIfWithManyBranchesRule(),
  AvoidInvertedBooleanChecksRule(),
  AvoidNegatedConditionsRule(),
  AvoidStreamToStringRule(),
  AvoidStatelessWidgetInitializedFieldsRule(),
  AvoidStateConstructorsRule(),
  AvoidAssignmentsAsConditionsRule(),
  AvoidConditionsWithBooleanLiteralsRule(),
  AvoidSelfAssignmentRule(),
  AvoidSelfCompareRule(),
  NoEmptyBlockRule(),
  PreferLastRule(),
  AvoidDoubleSlashImportsRule(),
  AvoidNestedRecordsRule(),
  PreferCommentingAnalyzerIgnoresRule(),
  AvoidReturningVoidRule(),
  AvoidUnnecessaryConstructorRule(),
  AvoidWeakCryptographicAlgorithmsRule(),
  NoObjectDeclarationRule(),
  PreferReturningConditionRule(),
  PreferDedicatedMediaQueryMethodRule(),
  AvoidCascadeAfterIfNullRule(),
  AvoidDuplicateExportsRule(),
  NoEqualThenElseRule(),
  AvoidGlobalStateRule(),
  PreferImmediateReturnRule(),
  PreferIterableOfRule(),
  AvoidExpandedAsSpacerRule(),
  AvoidDuplicateMixinsRule(),
  AvoidDuplicateNamedImportsRule(),
  AvoidThrowInCatchBlockRule(),
  AvoidUnnecessaryConditionalsRule(),
  PreferEnumsByNameRule(),
  AvoidBorderAllRule(),
  PreferConstBorderRadiusRule(),
  AvoidRedundantAsyncRule(),
  AvoidPassingSelfAsArgumentRule(),
  PreferCorrectEdgeInsetsConstructorRule(),
  PreferTextRichRule(),
  AvoidWrappingInPaddingRule(),
  PreferDefineHeroTagRule(),
  AvoidNullableToStringRule(),
  AvoidIncorrectImageOpacityRule(),
  PreferUsingListViewRule(),
  AvoidMissingImageAltRule(),
  AvoidDuplicateTestAssertionsRule(),
  UseSetStateSynchronouslyRule(),
  AvoidSubstringRule(),
  AvoidTopLevelMembersInTestsRule(),
  AvoidUnnecessaryTypeAssertionsRule(),
  AvoidUnnecessaryTypeCastsRule(),
  AvoidExplicitPatternFieldNameRule(),
  AlwaysRemoveListenerRule(),
  AvoidGenericsShadowingRule(),
  AvoidMissedCallsRule(),
  AvoidMisusedSetLiteralsRule(),
  AvoidUnrelatedTypeAssertionsRule(),
  AvoidUnusedParametersRule(),
  PreferCorrectTestFileNameRule(),
  AvoidCastingToExtensionTypeRule(),
  AvoidCollectionMethodsWithUnrelatedTypesRule(),
  AvoidIncompleteCopyWithRule(),
  AvoidUnnecessarySetStateRule(),
  AvoidUnnecessaryStatefulWidgetsRule(),
  CheckForEqualsInRenderObjectSettersRule(),
  ConsistentUpdateRenderObjectRule(),
  AvoidSingleFieldDestructuringRule(),
  AvoidUnsafeCollectionMethodsRule(),
  PreferNamedBooleanParametersRule(),
  PreferEarlyReturnRule(),
  AvoidFlexibleOutsideFlexRule(),
  ProperSuperCallsRule(),
  AvoidNestedAssignmentsRule(),
  AvoidUnconditionalBreakRule(),
  AvoidUnnecessaryReturnRule(),
  AvoidBitwiseOperatorsWithBooleansRule(),
  AvoidCollapsibleIfRule(),
  AvoidFunctionTypeInRecordsRule(),
  AvoidNestedSwitchExpressionsRule(),
  NoEqualConditionsRule(),
  AvoidUnnecessaryNegationsRule(),
  PreferCorrectIdentifierLengthRule(),
  AvoidUnsafeReduceRule(),
  PreferNamedParametersRule(),
  AvoidRecursiveCallsRule(),
  AvoidRecursiveToStringRule(),
  AvoidShadowingRule(),
  AvoidThrowObjectsWithoutToStringRule(),
  AvoidDuplicateCascadesRule(),
  AvoidEqualExpressionsRule(),
  AvoidCollectionEqualityChecksRule(),
  AvoidDuplicateSwitchCaseConditionsRule(),
  AvoidMixingNamedAndPositionalFieldsRule(),
  AvoidMultiAssignmentRule(),
  NoMagicStringRule(),
  PreferTypeOverVarRule(),
  AvoidMountedInSetStateRule(),
  PreferSliverPrefixRule(),
  AvoidConstantAssertConditionsRule(),
  AvoidConstantSwitchesRule(),
  AvoidUnnecessaryGetterRule(),
  AvoidLateContextRule(),
  AvoidUnnecessaryGestureDetectorRule(),
  PreferWidgetPrivateMembersRule(),
  AvoidBarrelFilesRule(),
  AvoidBottomTypeInPatternsRule(),
  AvoidBottomTypeInRecordsRule(),
  AvoidExtensionsOnRecordsRule(),
  AvoidImmediatelyInvokedFunctionsRule(),
  AvoidLongFilesRule(),
  AvoidLongFunctionsRule(),
  AvoidLongRecordsRule(),
  AvoidComplexArithmeticExpressionsRule(),
  AvoidComplexConditionsRule(),
  AvoidNonAsciiSymbolsRule(),
  AvoidNonEmptyConstructorBodiesRule(),
  AvoidRedundantPositionalFieldNameRule(),
  AvoidReferencingDiscardedVariablesRule(),
  AvoidUnnecessaryBlockRule(),
  AvoidUnnecessaryCallRule(),
  AvoidUnnecessaryContinueRule(),
  AvoidUnnecessaryExtendsRule(),
  AvoidInconsistentDigitSeparatorsRule(),
  AvoidIncorrectUriRule(),
  MaxImportsRule(),
  PreferAdditionSubtractionAssignmentsRule(),
  PreferCorrectErrorNameRule(),
  PreferTrailingCommaRule(),
  FormatCommentRule(),
  NoEqualArgumentsRule(),
  PreferCompoundAssignmentOperatorsRule(),
  PreferCorrectSetterParameterNameRule(),
  PreferDigitSeparatorsRule(),
  PreferExplicitFunctionTypeRule(),
  PreferNullAwareSpreadRule(),
  PreferParenthesesWithIfNullRule(),
  AvoidImplicitlyNullableExtensionTypesRule(),
  AvoidKeywordsInWildcardPatternRule(),
  AvoidNegationsInEqualityChecksRule(),
  MatchGetterSetterFieldNamesRule(),
  PreferWildcardPatternRule(),
  AvoidNullableParametersWithDefaultValuesRule(),
  AvoidUnnecessaryCollectionsRule(),
  AvoidUnnecessaryDigitSeparatorsRule(),
  AvoidUnnecessaryEnumArgumentsRule(),
  FormatTestNameRule(),
  PreferCorrectSwitchLengthRule(),
  PreferCorrectTypeNameRule(),
  PreferReturningConditionalsRule(),
  AvoidExcessiveExpressionsRule(),
  MapKeysOrderingRule(),
  MatchClassNamePatternRule(),
  NewlineBeforeCaseRule(),
  ParametersOrderingConventionRule(),
  PreferCorrectHandlerNameRule(),
  PreferUniqueTestNamesRule(),
  UnnecessaryTrailingCommaRule(),
  AvoidRedundantPragmaInlineRule(),
  AvoidUnknownPragmaRule(),
  NewlineBeforeMethodRule(),
  PreferExplicitParameterNamesRule(),
  PreferPrefixedGlobalConstantsRule(),
  PreferPrivateExtensionTypeFieldRule(),
  PreferReturningShorthandsRule(),
  RecordFieldsOrderingRule(),
  MatchLibFolderStructureRule(),
  MoveRecordsToTypedefsRule(),
  NewlineBeforeConstructorRule(),
  PatternFieldsOrderingRule(),
  PreferBothInliningAnnotationsRule(),
  PreferCommentingFutureDelayedRule(),
  PreferSimplerPatternsNullCheckRule(),
  PreferSortedParametersRule(),
  PreferVisibleForTestingOnMembersRule(),
  MatchPositionalFieldNamesOnAssignmentRule(),
  MissingUseResultAnnotationRule(),
  PreferAssigningAwaitExpressionsRule(),
  PreferCorrectFutureReturnTypeRule(),
  PreferCorrectStreamReturnTypeRule(),
  PreferExtractingFunctionCallbacksRule(),
  PreferNamedImportsRule(),
  PreferNullAwareElementsRule(),
  PreferTestStructureRule(),
  TagNameRule(),
  AvoidNestedShorthandsRule(),
  AvoidGetterPrefixRule(),
  AvoidEmptyTestGroupsRule(),
  AvoidEnumValuesByIndexRule(),
  AvoidUnnecessaryLengthCheckRule(),
  AvoidUnnecessaryCompareToRule(),
  AvoidFutureIgnoreRule(),
  AvoidFutureToStringRule(),
  PreferCorrectCallbackFieldNameRule(),
  AvoidNullableInterpolationRule(),
  AvoidNonFinalExceptionClassFieldsRule(),
  AvoidUnnecessaryEnumPrefixRule(),
  AvoidUnassignedStreamSubscriptionsRule(),
  PreferExpectLaterRule(),
  PreferPublicExceptionClassesRule(),
  PreferSpecifyingFutureValueTypeRule(),
  AvoidUnremovableCallbacksInListenersRule(),
  PreferDeclaringConstConstructorRule(),
  AvoidUnnecessaryIfRule(),

  // Noisy rules - disabled by default but available
  AvoidCommentedOutCodeRule(),
  AvoidDynamicRule(),
  AvoidLateKeywordRule(),
  AvoidNestedConditionalExpressionsRule(),
  AvoidPassingAsyncWhenSyncExpectedRule(),
  BinaryExpressionOperandOrderRule(),
  DoubleLiteralFormatRule(),
  MemberOrderingRule(),
  NewlineBeforeReturnRule(),
  NoMagicNumberRule(),
  PreferAsyncAwaitRule(),
  PreferConditionalExpressionsRule(),
  PreferMatchFileNameRule(),
  PreferMovingToVariableRule(),
  PreferStaticClassRule(),
  AvoidReturningWidgetsRule(),
  AvoidShrinkWrapInListsRule(),
  PreferExtractingCallbacksRule(),
  PreferSingleWidgetPerFileRule(),

  // Collection rules
  PreferAddAllRule(),
  AvoidDuplicateCollectionElementsRule(),
  PreferReturnAwaitRule(),
  MissingTestAssertionRule(),
  PreferSetForLookupRule(),

  // Code quality rules
  AvoidUnnecessaryLocalVariableRule(),
  AvoidUnnecessaryReassignmentRule(),
  PreferStaticMethodRule(),
  PreferAbstractFinalStaticClassRule(),
  AvoidHardcodedColorsRule(),

  // Flutter widget rules
  AvoidDeeplyNestedWidgetsRule(),
  RequireAnimationDisposalRule(),
  AvoidUncontrolledTextFieldRule(),
  AvoidHardcodedAssetPathsRule(),
  AvoidPrintInProductionRule(),
  AvoidCatchingGenericExceptionRule(),
  AvoidServiceLocatorOveruseRule(),
  PreferUtcDatetimesRule(),
  AvoidRegexInLoopRule(),
  PreferGetterOverMethodRule(),
  PreferNamedExtensionsRule(),
  PreferTypedefForCallbacksRule(),
  PreferEnhancedEnumsRule(),
  AvoidUnusedCallbackParametersRule(),
  PreferConstWidgetsInListsRule(),
  AvoidScaffoldMessengerAfterAwaitRule(),
  AvoidBuildContextInProvidersRule(),
  PreferSemanticWidgetNamesRule(),
  AvoidTextScaleFactorRule(),
  PreferWidgetStateMixinRule(),
  AvoidImageWithoutCacheRule(),
  PreferSplitWidgetConstRule(),
  AvoidNavigatorPushWithoutRouteNameRule(),
  AvoidDuplicateWidgetKeysRule(),
  PreferSafeAreaConsumerRule(),
  AvoidUnrestrictedTextFieldLengthRule(),
  PreferScaffoldMessengerMaybeOfRule(),
  AvoidFormWithoutKeyRule(),

  // Async rules
  AvoidUnusedGenericsRule(),
  PreferTrailingUnderscoreForUnusedRule(),
  AvoidUnnecessaryFuturesRule(),
  AvoidThrowInFinallyRule(),
  AvoidUnnecessaryNullableReturnTypeRule(),

  // Performance rules
  AvoidListViewWithoutItemExtentRule(),
  AvoidMediaQueryInBuildRule(),
  PreferSliverListDelegateRule(),
  AvoidLayoutBuilderMisuseRule(),
  AvoidRepaintBoundaryMisuseRule(),
  AvoidSingleChildScrollViewWithColumnRule(),
  PreferCachedNetworkImageRule(),
  AvoidGestureDetectorInScrollViewRule(),
  AvoidStatefulWidgetInListRule(),
  PreferOpacityWidgetRule(),

  // Additional code quality rules
  AvoidAlwaysNullParametersRule(),
  AvoidAssigningToStaticFieldRule(),
  AvoidAsyncCallInSyncFunctionRule(),
  AvoidComplexLoopConditionsRule(),
  AvoidConstantConditionsRule(),
  AvoidContradictoryExpressionsRule(),
  AvoidIdenticalExceptionHandlingBlocksRule(),
  AvoidLateFinalReassignmentRule(),
  AvoidMissingCompleterStackTraceRule(),
  AvoidMissingEnumConstantInMapRule(),
  AvoidMutatingParametersRule(),
  AvoidSimilarNamesRule(),
  AvoidUnnecessaryNullableParametersRule(),
  FunctionAlwaysReturnsNullRule(),
  AvoidAccessingCollectionsByConstantIndexRule(),
  AvoidDefaultToStringRule(),
  AvoidDuplicateConstantValuesRule(),
  AvoidDuplicateInitializersRule(),
  AvoidUnnecessaryOverridesRule(),
  AvoidUnnecessaryStatementsRule(),
  AvoidUnusedAssignmentRule(),
  AvoidUnusedInstancesRule(),
  AvoidUnusedAfterNullCheckRule(),
  AvoidWildcardCasesWithEnumsRule(),
  FunctionAlwaysReturnsSameValueRule(),
  NoEqualNestedConditionsRule(),
  NoEqualSwitchCaseRule(),
  PreferAnyOrEveryRule(),
  PreferForInRule(),
  AvoidDuplicatePatternsRule(),
  AvoidNestedExtensionTypesRule(),
  AvoidSlowCollectionMethodsRule(),
  AvoidUnassignedFieldsRule(),
  AvoidUnassignedLateFieldsRule(),
  AvoidUnnecessaryLateFieldsRule(),
  AvoidUnnecessaryNullableFieldsRule(),
  AvoidUnnecessaryPatternsRule(),
  AvoidWildcardCasesWithSealedClassesRule(),
  NoEqualSwitchExpressionCasesRule(),
  PreferBytesBuilderRule(),
  PreferPushingConditionalExpressionsRule(),
  PreferShorthandsWithConstructorsRule(),
  PreferShorthandsWithEnumsRule(),
  PreferShorthandsWithStaticFieldsRule(),

  // Medium complexity rules
  PassCorrectAcceptedTypeRule(),
  PassOptionalArgumentRule(),
  PreferSingleDeclarationPerFileRule(),
  PreferSwitchExpressionRule(),
  PreferSwitchWithEnumsRule(),
  PreferSwitchWithSealedClassesRule(),
  PreferTestMatchersRule(),
  PreferUnwrappingFutureOrRule(),

  // Hard complexity rules
  AvoidInferrableTypeArgumentsRule(),
  AvoidPassingDefaultValuesRule(),
  AvoidShadowedExtensionMethodsRule(),
  AvoidUnnecessaryLocalLateRule(),
  MatchBaseClassDefaultValueRule(),
  MoveVariableCloserToUsageRule(),
  MoveVariableOutsideIterationRule(),
  PreferOverridingParentEqualityRule(),
  PreferSpecificCasesFirstRule(),
  UseExistingDestructuringRule(),
  UseExistingVariableRule(),

  // Flutter-specific rules
  AvoidInheritedWidgetInInitStateRule(),
  AvoidRecursiveWidgetCallsRule(),
  AvoidUndisposedInstancesRule(),
  AvoidUnnecessaryOverridesInStateRule(),
  DisposeFieldsRule(),
  PassExistingFutureToFutureBuilderRule(),
  PassExistingStreamToStreamBuilderRule(),

  // Accessibility rules (NEW)
  AvoidIconButtonsWithoutTooltipRule(),
  AvoidSmallTouchTargetsRule(),
  RequireExcludeSemanticsJustificationRule(),
  AvoidColorOnlyIndicatorsRule(),
  AvoidGestureOnlyInteractionsRule(),
  RequireSemanticsLabelRule(),
  AvoidMergedSemanticsHidingInfoRule(),
  RequireLiveRegionRule(),
  RequireHeadingSemanticsRule(),
  AvoidImageButtonsWithoutTooltipRule(),

  // Security rules (NEW)
  AvoidLoggingSensitiveDataRule(),
  RequireSecureStorageRule(),
  AvoidHardcodedCredentialsRule(),
  RequireInputSanitizationRule(),
  AvoidWebViewJavaScriptEnabledRule(),
  RequireBiometricFallbackRule(),
  AvoidEvalLikePatternsRule(),
  RequireCertificatePinningRule(),

  // Performance rules (NEW)
  RequireKeysInAnimatedListsRule(),
  AvoidExpensiveBuildRule(),
  PreferConstChildWidgetsRule(),
  AvoidSynchronousFileIoRule(),
  PreferComputeForHeavyWorkRule(),
  AvoidObjectCreationInHotLoopsRule(),
  PreferCachedGetterRule(),
  AvoidExcessiveWidgetDepthRule(),
  RequireItemExtentForLargeListsRule(),
  RequireImageCacheDimensionsRule(),
  PreferImagePrecacheRule(),
  AvoidControllerInBuildRule(),
  AvoidSetStateInBuildRule(),

  // State management rules (NEW)
  RequireNotifyListenersRule(),
  RequireStreamControllerDisposeRule(),
  RequireValueNotifierDisposeRule(),
  RequireMountedCheckRule(),
  AvoidWatchInCallbacksRule(),
  AvoidBlocEventInConstructorRule(),
  RequireUpdateShouldNotifyRule(),
  AvoidGlobalRiverpodProvidersRule(),
  AvoidStatefulWithoutStateRule(),
  AvoidGlobalKeyInBuildRule(),

  // Error handling rules (NEW)
  AvoidSwallowingExceptionsRule(),
  AvoidLosingStackTraceRule(),
  RequireFutureErrorHandlingRule(),
  AvoidGenericExceptionsRule(),
  RequireErrorContextRule(),
  PreferResultPatternRule(),
  RequireAsyncErrorDocumentationRule(),
  RequireErrorBoundaryRule(),

  // Architecture rules (NEW)
  AvoidDirectDataAccessInUiRule(),
  AvoidBusinessLogicInUiRule(),
  AvoidCircularDependenciesRule(),
  AvoidGodClassRule(),
  AvoidUiInDomainLayerRule(),
  AvoidCrossFeatureDependenciesRule(),
  AvoidSingletonPatternRule(),

  // Documentation rules (NEW)
  RequirePublicApiDocumentationRule(),
  AvoidMisleadingDocumentationRule(),
  RequireDeprecationMessageRule(),
  RequireComplexLogicCommentsRule(),
  RequireParameterDocumentationRule(),
  RequireReturnDocumentationRule(),
  RequireExceptionDocumentationRule(),
  RequireExampleInDocumentationRule(),

  // Testing best practices rules (NEW)
  RequireTestAssertionsRule(),
  AvoidVagueTestDescriptionsRule(),
  AvoidRealNetworkCallsInTestsRule(),
  AvoidHardcodedTestDelaysRule(),
  RequireTestSetupTeardownRule(),
  RequirePumpAfterInteractionRule(),
  AvoidProductionConfigInTestsRule(),

  // Internationalization rules (NEW)
  AvoidHardcodedStringsInUiRule(),
  RequireLocaleAwareFormattingRule(),
  RequireDirectionalWidgetsRule(),
  RequirePluralHandlingRule(),
  AvoidHardcodedLocaleRule(),
  AvoidStringConcatenationInUiRule(),
  AvoidTextInImagesRule(),
  AvoidHardcodedAppNameRule(),

  // API & Network rules (NEW)
  RequireHttpStatusCheckRule(),
  RequireApiTimeoutRule(),
  AvoidHardcodedApiUrlsRule(),
  RequireRetryLogicRule(),
  RequireTypedApiResponseRule(),
  RequireConnectivityCheckRule(),
  RequireApiErrorMappingRule(),

  // Dependency Injection rules (NEW)
  AvoidServiceLocatorInWidgetsRule(),
  AvoidTooManyDependenciesRule(),
  AvoidInternalDependencyCreationRule(),
  PreferAbstractDependenciesRule(),
  AvoidSingletonForScopedDependenciesRule(),
  AvoidCircularDiDependenciesRule(),
  PreferNullObjectPatternRule(),
  RequireTypedDiRegistrationRule(),

  // Memory Management rules (NEW)
  AvoidLargeObjectsInStateRule(),
  RequireImageDisposalRule(),
  AvoidCapturingThisInCallbacksRule(),
  RequireCacheEvictionPolicyRule(),
  PreferWeakReferencesForCacheRule(),
  AvoidExpandoCircularReferencesRule(),
  AvoidLargeIsolateCommunicationRule(),

  // Type Safety rules (NEW)
  AvoidUnsafeCastRule(),
  PreferConstrainedGenericsRule(),
  RequireCovariantDocumentationRule(),
  RequireSafeJsonParsingRule(),
  RequireNullSafeExtensionsRule(),
  PreferSpecificNumericTypesRule(),
  RequireFutureOrDocumentationRule(),

  // Resource Management rules (NEW)
  RequireFileCloseInFinallyRule(),
  RequireDatabaseCloseRule(),
  RequireHttpClientCloseRule(),
  RequireNativeResourceCleanupRule(),
  RequireWebSocketCloseRule(),
  RequirePlatformChannelCleanupRule(),
  RequireIsolateKillRule(),

  // New formatting rules
  AvoidDigitSeparatorsRule(),
  FormatCommentFormattingRule(),
  MemberOrderingFormattingRule(),
  ParametersOrderingConventionRule(),
];

class _SaropaLints extends PluginBase {
  @override
  List<LintRule> getLintRules(CustomLintConfigs configs) {
    // Return all rules - filtering is done via configs.rules (set rule: false to disable)
    return _allRules.toList();
  }
}
