/** * Module overview (comment coverage pass). * comment-coverage: module overview (batch). * * Vibrancy UI experiment: scoring, providers, and webview assets. */
import { CiThresholds, CiPlatform } from '../types';

// Stubs for GitHub Actions, GitLab CI, and shell from vibrancy thresholds.
/** Generate CI workflow content for the specified platform. */
export function generateCiWorkflow(
    platform: CiPlatform,
    thresholds: CiThresholds,
): string {
    switch (platform) {
        case 'github-actions':
            return generateGitHubActions(thresholds);
        case 'gitlab-ci':
            return generateGitLabCi(thresholds);
        case 'shell-script':
            return generateShellScript(thresholds);
    }
}

/** Get the default output path for a CI platform. */
export function getDefaultOutputPath(platform: CiPlatform): string {
    switch (platform) {
        case 'github-actions':
            return '.github/workflows/vibrancy-check.yml';
        case 'gitlab-ci':
            return '.gitlab-ci-vibrancy.yml';
        case 'shell-script':
            return 'scripts/vibrancy-check.sh';
    }
}

/** Generate a GitHub Actions workflow. */
export function generateGitHubActions(thresholds: CiThresholds): string {
    const failOnVuln = thresholds.failOnVulnerability ? 'true' : 'false';

    return `# Generated by Package Vibrancy
# Checks dependency health on PRs that modify pubspec files

name: Dependency Health Check

on:
  pull_request:
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'

jobs:
  vibrancy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Check dependency health
        id: health-check
        run: |
          echo "Checking dependency health thresholds..."

          # Get outdated packages info
          flutter pub outdated --json > outdated.json

          # Write the checker to a real file: \`dart run\` cannot read a
          # program from stdin, so a heredoc piped into it silently no-ops.
          cat > vibrancy_check.dart <<'DART_SCRIPT'
          import 'dart:convert';
          import 'dart:io';

          void main() {
            final json = jsonDecode(File('outdated.json').readAsStringSync());
            final packages = json['packages'] as List? ?? [];

            var outdatedCount = 0;
            var majorUpdates = 0;

            for (final pkg in packages) {
              final current = pkg['current']?['version'];
              final latest = pkg['latest']?['version'];
              if (current != null && latest != null && current != latest) {
                outdatedCount++;
                final currentMajor = int.tryParse(current.split('.')[0]) ?? 0;
                final latestMajor = int.tryParse(latest.split('.')[0]) ?? 0;
                if (latestMajor > currentMajor) majorUpdates++;
              }
            }

            print('📊 Dependency Health Summary');
            print('   Outdated packages: \$outdatedCount');
            print('   Major updates available: \$majorUpdates');

            // Thresholds from configuration
            const maxAbandoned = ${thresholds.maxAbandoned};
            const maxEol = ${thresholds.maxEndOfLife};
            const maxOutdated = ${thresholds.maxOutdated};
            const minAvgVibrancy = ${thresholds.minAverageVibrancy};
            const failOnVuln = ${failOnVuln};

            print('');
            print('   Thresholds:');
            print('     Max Abandoned: \$maxAbandoned');
            print('     Max EOL: \$maxEol');
            print('     Max Outdated: \$maxOutdated');
            print('     Min Avg Vibrancy: \$minAvgVibrancy');
            print('     Fail on Vulnerability: \$failOnVuln');

            var failed = false;
            if (outdatedCount > maxOutdated) {
              print('❌ FAIL: outdated packages (\$outdatedCount) exceed max allowed (\$maxOutdated)');
              failed = true;
            } else {
              print('✅ Outdated package count is within threshold.');
            }

            // maxAbandoned, maxEol, and minAvgVibrancy describe package
            // abandonment, end-of-life status, and computed vibrancy scores.
            // \`flutter pub outdated\` does not report any of that, so those
            // thresholds cannot be honestly evaluated here. Surface the gap
            // instead of pretending to enforce it.
            if (maxAbandoned >= 0 || maxEol >= 0 || minAvgVibrancy >= 0) {
              print('ℹ️  Max Abandoned / Max EOL / Min Avg Vibrancy require full vibrancy scoring data that \`pub outdated\` does not provide, so they are NOT enforced by this basic check. Use saropa_vibrancy_cli for those.');
            }

            // failOnVulnerability has no data source here either: pub
            // outdated reports version currency, not known vulnerabilities.
            // Do not fabricate a vulnerability count — say so plainly.
            if (failOnVuln) {
              print('⚠️  Fail on Vulnerability is enabled but \`pub outdated\` reports no vulnerability data, so this check cannot enforce it. Use saropa_vibrancy_cli or a dedicated vulnerability scanner.');
            }

            // For full vibrancy scoring use saropa_vibrancy_cli when available.
            exit(failed ? 1 : 0);
          }
          DART_SCRIPT

          dart run vibrancy_check.dart

      - name: Upload dependency report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: outdated.json
          retention-days: 7

      - name: Comment on PR
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let report = '## 📊 Dependency Health Check\\n\\n';
            
            try {
              const outdated = JSON.parse(fs.readFileSync('outdated.json', 'utf8'));
              const packages = outdated.packages || [];
              const outdatedCount = packages.filter(p => 
                p.current?.version && p.latest?.version && 
                p.current.version !== p.latest.version
              ).length;
              
              report += '| Metric | Value | Threshold | Status |\\n';
              report += '|--------|-------|-----------|--------|\\n';
              report += \`| Outdated | \${outdatedCount} | — | \${outdatedCount === 0 ? '✅' : 'ℹ️'} |\\n\`;
              report += \`| Abandoned Limit | — | ≤ ${thresholds.maxAbandoned} | — |\\n\`;
              report += \`| EOL Limit | — | ≤ ${thresholds.maxEndOfLife} | — |\\n\`;
              report += \`| Outdated Limit | — | ≤ ${thresholds.maxOutdated} | — |\\n\`;
              report += \`| Min Avg Vibrancy | — | ≥ ${thresholds.minAverageVibrancy} | — |\\n\`;
              report += '\\n*Full vibrancy analysis requires saropa_vibrancy_cli*\\n';
            } catch (e) {
              report += 'Failed to parse dependency report.\\n';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
`;
}

/** Generate a GitLab CI job configuration. */
export function generateGitLabCi(thresholds: CiThresholds): string {
    const failOnVuln = thresholds.failOnVulnerability ? 'true' : 'false';

    return `# Generated by Package Vibrancy
# Add this to your .gitlab-ci.yml or include as a separate file

vibrancy-check:
  stage: test
  image: cirrusci/flutter:stable
  rules:
    - changes:
        - pubspec.yaml
        - pubspec.lock
  script:
    - flutter pub get
    - echo "Checking dependency health thresholds..."
    - flutter pub outdated --json > outdated.json
    - |
      # Write the checker to a real file: \`dart run\` cannot read a program
      # from stdin, so a heredoc piped into it silently no-ops.
      cat > vibrancy_check.dart <<'DART_SCRIPT'
      import 'dart:convert';
      import 'dart:io';

      void main() {
        final json = jsonDecode(File('outdated.json').readAsStringSync());
        final packages = json['packages'] as List? ?? [];

        var outdatedCount = 0;
        for (final pkg in packages) {
          final current = pkg['current']?['version'];
          final latest = pkg['latest']?['version'];
          if (current != null && latest != null && current != latest) {
            outdatedCount++;
          }
        }

        print('📊 Dependency Health Summary');
        print('   Outdated packages: \$outdatedCount');

        // Thresholds
        const maxAbandoned = ${thresholds.maxAbandoned};
        const maxEol = ${thresholds.maxEndOfLife};
        const maxOutdated = ${thresholds.maxOutdated};
        const minAvgVibrancy = ${thresholds.minAverageVibrancy};
        const failOnVuln = ${failOnVuln};

        print('   Max Abandoned: \$maxAbandoned');
        print('   Max EOL: \$maxEol');
        print('   Max Outdated: \$maxOutdated');
        print('   Min Avg Vibrancy: \$minAvgVibrancy');
        print('   Fail on Vulnerability: \$failOnVuln');

        var failed = false;
        if (outdatedCount > maxOutdated) {
          print('❌ FAIL: outdated packages (\$outdatedCount) exceed max allowed (\$maxOutdated)');
          failed = true;
        } else {
          print('✅ Outdated package count is within threshold.');
        }

        // maxAbandoned, maxEol, and minAvgVibrancy need full vibrancy
        // scoring data (abandonment status, end-of-life dates, computed
        // scores) that \`pub outdated\` does not provide, so they are NOT
        // enforced here. Use saropa_vibrancy_cli for those.
        if (maxAbandoned >= 0 || maxEol >= 0 || minAvgVibrancy >= 0) {
          print('ℹ️  Max Abandoned / Max EOL / Min Avg Vibrancy are not enforced by this basic check (no data source). Use saropa_vibrancy_cli.');
        }

        // No vulnerability data is available from \`pub outdated\`; do not
        // fabricate one. Report the gap instead of silently passing.
        if (failOnVuln) {
          print('⚠️  Fail on Vulnerability is enabled but cannot be enforced here (no vulnerability data source). Use saropa_vibrancy_cli or a dedicated scanner.');
        }

        exit(failed ? 1 : 0);
      }
      DART_SCRIPT

      dart run vibrancy_check.dart
  artifacts:
    paths:
      - outdated.json
    expire_in: 1 week
    when: always
`;
}

/** Generate a portable shell script for manual/custom CI. */
export function generateShellScript(thresholds: CiThresholds): string {
    const failOnVuln = thresholds.failOnVulnerability ? 'true' : 'false';

    return `#!/bin/bash
# Generated by Package Vibrancy
# Portable dependency health check script

set -e

# Configuration thresholds
MAX_ABANDONED=${thresholds.maxAbandoned}
MAX_EOL=${thresholds.maxEndOfLife}
MAX_OUTDATED=${thresholds.maxOutdated}
MIN_AVG_VIBRANCY=${thresholds.minAverageVibrancy}
FAIL_ON_VULN=${failOnVuln}

echo "📊 Dependency Health Check"
echo "=========================="
echo ""

# Ensure Flutter is available
if ! command -v flutter &> /dev/null; then
    echo "❌ Flutter not found in PATH"
    exit 1
fi

# Install dependencies
echo "Installing dependencies..."
flutter pub get

# Get outdated packages
echo "Checking for outdated packages..."
flutter pub outdated --json > /tmp/outdated.json

# Parse results with Dart.
# \`dart run\` cannot read a program from stdin, so it must be written to a
# real file first — piping a heredoc into it silently does nothing.
cat > /tmp/vibrancy_check.dart <<'DART_SCRIPT'
import 'dart:convert';
import 'dart:io';

void main() {
  final json = jsonDecode(File('/tmp/outdated.json').readAsStringSync());
  final packages = json['packages'] as List? ?? [];

  var outdatedCount = 0;
  var majorUpdates = 0;
  final outdatedList = <String>[];

  for (final pkg in packages) {
    final name = pkg['package'] as String?;
    final current = pkg['current']?['version'];
    final latest = pkg['latest']?['version'];

    if (current != null && latest != null && current != latest) {
      outdatedCount++;
      outdatedList.add('  - \$name: \$current → \$latest');

      final currentMajor = int.tryParse(current.split('.')[0]) ?? 0;
      final latestMajor = int.tryParse(latest.split('.')[0]) ?? 0;
      if (latestMajor > currentMajor) majorUpdates++;
    }
  }

  print('Results:');
  print('  Total packages: \${packages.length}');
  print('  Outdated: \$outdatedCount');
  print('  Major updates: \$majorUpdates');

  if (outdatedList.isNotEmpty) {
    print('');
    print('Outdated packages:');
    for (final item in outdatedList) {
      print(item);
    }
  }

  print('');
  print('Thresholds:');
  const maxAbandoned = ${thresholds.maxAbandoned};
  const maxEol = ${thresholds.maxEndOfLife};
  const maxOutdated = ${thresholds.maxOutdated};
  const minAvgVibrancy = ${thresholds.minAverageVibrancy};
  const failOnVuln = ${failOnVuln};

  print('  Max Abandoned: \$maxAbandoned');
  print('  Max End-of-Life: \$maxEol');
  print('  Max Outdated: \$maxOutdated');
  print('  Min Average Vibrancy: \$minAvgVibrancy');
  print('  Fail on Vulnerability: \$failOnVuln');

  var failed = false;
  if (outdatedCount > maxOutdated) {
    print('❌ FAIL: outdated packages (\$outdatedCount) exceed max allowed (\$maxOutdated)');
    failed = true;
  } else {
    print('✅ Outdated package count is within threshold.');
  }

  // Max Abandoned / Max End-of-Life / Min Average Vibrancy need full
  // vibrancy scoring data (abandonment status, end-of-life dates, computed
  // scores) that \`pub outdated\` does not provide, so they are NOT enforced
  // by this basic check.
  if (maxAbandoned >= 0 || maxEol >= 0 || minAvgVibrancy >= 0) {
    print('ℹ️  Max Abandoned / Max End-of-Life / Min Average Vibrancy are not enforced here (no data source in pub outdated). Use saropa_vibrancy_cli.');
  }

  // \`pub outdated\` reports no vulnerability data. Do not fabricate one —
  // report the gap honestly instead of pretending to enforce it.
  if (failOnVuln) {
    print('⚠️  Fail on Vulnerability is enabled but cannot be enforced here (no vulnerability data source). Use saropa_vibrancy_cli or a dedicated scanner.');
  }

  // For full vibrancy scoring use saropa_vibrancy_cli when available.
  exit(failed ? 1 : 0);
}
DART_SCRIPT

dart run /tmp/vibrancy_check.dart
# \`set -e\` above means a non-zero exit from the check above aborts this
# script immediately with that same exit code, so the caller sees the
# failure — nothing below runs unless the thresholds passed.

echo ""
echo "✅ Dependency check complete"
echo ""
echo "Note: For full vibrancy scoring, install saropa_vibrancy_cli:"
echo "  dart pub global activate saropa_vibrancy_cli"
`;
}

/** Get platform display name for UI. */
export function getPlatformDisplayName(platform: CiPlatform): string {
    switch (platform) {
        case 'github-actions':
            return 'GitHub Actions';
        case 'gitlab-ci':
            return 'GitLab CI';
        case 'shell-script':
            return 'Shell Script (portable)';
    }
}

/** Get all available platforms for quick-pick. */
export function getAvailablePlatforms(): { id: CiPlatform; label: string; description: string }[] {
    return [
        {
            id: 'github-actions',
            label: '$(github) GitHub Actions',
            description: '.github/workflows/vibrancy-check.yml',
        },
        {
            id: 'gitlab-ci',
            label: '$(git-merge) GitLab CI',
            description: '.gitlab-ci-vibrancy.yml',
        },
        {
            id: 'shell-script',
            label: '$(terminal) Shell Script',
            description: 'scripts/vibrancy-check.sh (portable)',
        },
    ];
}
