// GENERATED FILE — do not edit by hand.
// Run: dart run tool/generate_rule_pack_registry.dart
// ignore_for_file: always_specify_types

/// Rule codes per pack, extracted from lib/src/rules/packages/.
const Map<String, Set<String>> kRulePackRuleCodesGenerated = {
  'app_links': {
    'app_links_avoid_get_initial_link_string',
    'app_links_listen_in_build',
    'app_links_uncaught_stream_error',
    'avoid_app_links_sensitive_params',
  },
  'app_links_6': {
    'app_links_use_get_initial_link',
    'app_links_use_get_latest_link',
    'app_links_use_uri_link_stream',
  },
  'audioplayers': {
    'audioplayers_hardcoded_volume_above_one',
    'audioplayers_low_latency_with_seek',
    'audioplayers_low_latency_with_stream_listen',
    'audioplayers_pool_not_disposed',
    'audioplayers_release_mode_loop_with_complete_listener',
    'audioplayers_url_source_in_asset_context',
  },
  'auto_route': {
    'avoid_auto_route_context_navigation',
    'avoid_auto_route_keep_history_misuse',
    'prefer_auto_route_path_params_simple',
    'prefer_auto_route_typed_args',
    'require_auto_route_deep_link_config',
    'require_auto_route_full_hierarchy',
    'require_auto_route_guard_resume',
  },
  'awesome_notifications': {
    'awesome_notifications_create_without_permission_check',
    'awesome_notifications_handler_wrong_parameter_type',
    'awesome_notifications_listeners_before_display',
    'awesome_notifications_missing_pragma_annotation',
    'awesome_notifications_negative_notification_id',
    'awesome_notifications_non_static_listener',
    'awesome_notifications_undeclared_channel_key',
  },
  'bloc': {
    'avoid_bloc_business_logic_in_ui',
    'avoid_bloc_context_dependency',
    'avoid_bloc_emit_after_close',
    'avoid_bloc_event_in_constructor',
    'avoid_bloc_event_mutation',
    'avoid_bloc_in_bloc',
    'avoid_bloc_listen_in_build',
    'avoid_bloc_public_fields',
    'avoid_bloc_public_methods',
    'avoid_bloc_state_mutation',
    'avoid_cubit_usage',
    'avoid_duplicate_bloc_event_handlers',
    'avoid_existing_instances_in_bloc_provider',
    'avoid_instantiating_in_bloc_value_provider',
    'avoid_large_bloc',
    'avoid_long_event_handlers',
    'avoid_overengineered_bloc_states',
    'avoid_passing_bloc_to_bloc',
    'avoid_passing_build_context_to_blocs',
    'avoid_returning_value_from_cubit_methods',
    'avoid_yield_in_on_event',
    'check_is_not_closed_after_async_gap',
    'emit_new_bloc_state_instances',
    'prefer_bloc_event_suffix',
    'prefer_bloc_extensions',
    'prefer_bloc_hydration',
    'prefer_bloc_listener_for_side_effects',
    'prefer_bloc_state_suffix',
    'prefer_bloc_transform',
    'prefer_copy_with_for_state',
    'prefer_correct_bloc_provider',
    'prefer_cubit_for_simple',
    'prefer_cubit_for_simple_state',
    'prefer_immutable_bloc_events',
    'prefer_immutable_bloc_state',
    'prefer_multi_bloc_provider',
    'prefer_sealed_bloc_events',
    'prefer_sealed_bloc_state',
    'prefer_sealed_events',
    'require_bloc_close',
    'require_bloc_consumer_when_both',
    'require_bloc_error_state',
    'require_bloc_event_sealed',
    'require_bloc_initial_state',
    'require_bloc_loading_state',
    'require_bloc_manual_dispose',
    'require_bloc_observer',
    'require_bloc_repository_abstraction',
    'require_bloc_repository_injection',
    'require_bloc_selector',
    'require_bloc_transformer',
    'require_error_state',
    'require_immutable_bloc_state',
    'require_initial_state',
  },
  'bloc_8': {'avoid_bloc_map_event_to_state'},
  'cached_network_image': {
    'avoid_inline_cache_manager_construction',
    'require_cached_image_provider_dimensions',
    'require_cached_image_provider_error_listener',
  },
  'connectivity_plus': {'connectivity_satellite_missing'},
  'connectivity_plus_6': {'avoid_pre_v6_single_connectivity_result'},
  'device_calendar': {
    'device_calendar_event_missing_calendar_id',
    'device_calendar_event_utc_timezone',
    'device_calendar_missing_permission_check',
    'device_calendar_result_data_before_success_check',
    'device_calendar_retrieve_events_empty_params',
    'device_calendar_retrieve_events_missing_end_date',
    'device_calendar_unchecked_result',
    'require_calendar_timezone_handling',
  },
  'dio': {
    'avoid_dio_debug_print_production',
    'avoid_dio_form_data_leak',
    'avoid_dio_without_base_url',
    'prefer_dio_base_options',
    'prefer_dio_cancel_token',
    'prefer_dio_over_http',
    'prefer_dio_transformer',
    'require_dio_error_handling',
    'require_dio_interceptor_error_handler',
    'require_dio_response_type',
    'require_dio_retry_interceptor',
    'require_dio_singleton',
    'require_dio_ssl_pinning',
    'require_dio_timeout',
  },
  'dio_5': {'avoid_dio_error'},
  'drift': {
    'avoid_drift_close_streams_in_tests',
    'avoid_drift_database_on_main_isolate',
    'avoid_drift_enum_index_reorder',
    'avoid_drift_foreign_key_in_migration',
    'avoid_drift_get_single_without_unique',
    'avoid_drift_insert_missing_conflict_target',
    'avoid_drift_lazy_database',
    'avoid_drift_log_statements_production',
    'avoid_drift_missing_updates_param',
    'avoid_drift_nullable_converter_mismatch',
    'avoid_drift_query_in_migration',
    'avoid_drift_raw_sql_interpolation',
    'avoid_drift_replace_without_all_columns',
    'avoid_drift_unsafe_web_storage',
    'avoid_drift_update_without_where',
    'avoid_drift_validate_schema_production',
    'avoid_drift_value_null_vs_absent',
    'avoid_isar_import_with_drift',
    'prefer_drift_batch_operations',
    'prefer_drift_foreign_key_declaration',
    'prefer_drift_isolate_sharing',
    'prefer_drift_use_columns_false',
    'require_await_in_drift_transaction',
    'require_drift_create_all_in_oncreate',
    'require_drift_database_close',
    'require_drift_equals_value',
    'require_drift_foreign_key_pragma',
    'require_drift_onupgrade_handler',
    'require_drift_read_table_or_null',
    'require_drift_reads_from',
    'require_drift_schema_version_bump',
    'require_drift_stream_cancel',
  },
  'envied': {'require_envied_obfuscation'},
  'equatable': {
    'avoid_equatable_datetime',
    'avoid_equatable_nested_equality',
    'avoid_mutable_field_in_equatable',
    'list_all_equatable_fields',
    'prefer_equatable_mixin',
    'prefer_equatable_stringify',
    'prefer_immutable_annotation',
    'prefer_record_over_equatable',
    'prefer_unmodifiable_collections',
    'require_copy_with_null_handling',
    'require_deep_equality_collections',
    'require_equatable_copy_with',
    'require_equatable_props_override',
    'require_extend_equatable',
  },
  'file_picker': {
    'file_picker_custom_type_missing_extensions',
    'file_picker_extension_with_dot',
    'file_picker_extensions_without_custom_type',
    'file_picker_path_on_web',
    'file_picker_unchecked_null_result',
    'file_picker_with_data_large_files',
  },
  'file_picker_10': {'file_picker_deprecated_allow_compression'},
  'file_picker_12': {
    'file_picker_deprecated_allow_multiple',
    'file_picker_deprecated_with_data',
    'file_picker_deprecated_with_read_stream',
  },
  'firebase': {
    'avoid_database_in_build',
    'avoid_firebase_realtime_in_build',
    'avoid_firebase_user_data_in_auth',
    'avoid_firestore_in_widget_build',
    'avoid_firestore_unbounded_query',
    'avoid_map_markers_in_build',
    'avoid_secure_storage_on_web',
    'avoid_storing_user_data_in_auth',
    'incorrect_firebase_event_name',
    'incorrect_firebase_parameter_name',
    'prefer_correct_topics',
    'prefer_deep_link_auth',
    'prefer_firebase_auth_persistence',
    'prefer_firebase_remote_config_defaults',
    'prefer_firebase_transaction_for_counters',
    'prefer_firestore_batch_write',
    'prefer_marker_clustering',
    'prefer_transaction_for_batch',
    'require_analytics_error_handling',
    'require_background_message_handler',
    'require_crashlytics_user_id',
    'require_database_index',
    'require_database_migration',
    'require_fcm_token_refresh_handler',
    'require_firebase_app_check',
    'require_firebase_app_check_production',
    'require_firebase_composite_index',
    'require_firebase_email_enumeration_protection',
    'require_firebase_error_handling',
    'require_firebase_init_before_use',
    'require_firebase_offline_persistence',
    'require_firebase_reauthentication',
    'require_firebase_token_refresh',
    'require_firestore_index',
    'require_firestore_security_rules',
    'require_map_idle_callback',
  },
  'flame': {'avoid_creating_vector_in_update', 'avoid_redundant_async_on_load'},
  'flutter_animate': {
    'flutter_animate_auto_play_false_no_driver',
    'flutter_animate_empty_animate_list',
    'flutter_animate_fixed_target_literal',
    'flutter_animate_no_key_in_list',
    'flutter_animate_restart_on_hot_reload_in_release',
    'flutter_animate_unconditional_repeat_in_on_play',
  },
  'flutter_hooks': {
    'avoid_conditional_hooks',
    'avoid_hooks_outside_build',
    'avoid_misused_hooks',
    'avoid_unnecessary_hook_widgets',
    'prefer_use_callback',
  },
  'flutter_keyboard_visibility': {'require_keyboard_visibility_dispose'},
  'flutter_map': {
    'flutter_map_deprecated_polygon_label_placement',
    'flutter_map_deprecated_tile_size',
    'flutter_map_fallback_url_disables_cache',
    'flutter_map_legacy_map_options_center',
    'flutter_map_missing_error_tile_callback',
    'flutter_map_missing_user_agent',
  },
  'flutter_svg': {
    'require_svg_error_handler',
    'svg_missing_semantics_label',
    'svg_network_missing_error_builder',
    'svg_network_missing_placeholder',
    'svg_string_missing_error_builder',
  },
  'flutter_svg_2': {'prefer_svg_color_filter'},
  'geocoding': {
    'geocoding_call_in_text_field_listener',
    'geocoding_concurrent_locale_race',
    'geocoding_deprecated_locale_param',
    'geocoding_locale_set_before_call',
    'geocoding_missing_exception_handler',
    'geocoding_missing_is_present_check',
    'geocoding_prefer_no_result_found_catch',
    'geocoding_unchecked_first',
  },
  'geolocator': {
    'avoid_continuous_location_updates',
    'avoid_geolocator_background_without_config',
    'prefer_geocoding_cache',
    'prefer_geolocation_coarse_location',
    'prefer_geolocator_distance_filter',
    'require_geolocator_battery_awareness',
  },
  'get_it': {
    'avoid_getit_in_build',
    'prefer_injectable_package',
    'require_getit_dispose_registration',
    'require_getit_registration_order',
    'require_getit_reset_in_tests',
  },
  'getx': {
    'always_remove_getx_listener',
    'avoid_get_find_in_build',
    'avoid_getx_build_context_bypass',
    'avoid_getx_context_outside_widget',
    'avoid_getx_dialog_snackbar_in_controller',
    'avoid_getx_global_navigation',
    'avoid_getx_global_state',
    'avoid_getx_rx_inside_build',
    'avoid_getx_rx_nested_obs',
    'avoid_getx_static_context',
    'avoid_getx_static_get',
    'avoid_mutable_rx_variables',
    'avoid_obs_outside_controller',
    'avoid_tight_coupling_with_getx',
    'dispose_getx_fields',
    'prefer_getx_builder',
    'prefer_getx_builder_over_obx',
    'proper_getx_super_calls',
    'require_getx_binding',
    'require_getx_binding_routes',
    'require_getx_controller_dispose',
    'require_getx_lazy_put',
    'require_getx_permanent_cleanup',
    'require_getx_worker_dispose',
  },
  'go_router_6': {'avoid_go_router_legacy_redirect'},
  'google_fonts': {'require_google_fonts_fallback'},
  'google_maps_flutter': {
    'google_maps_animate_camera_in_build',
    'google_maps_bitmap_descriptor_in_build',
    'google_maps_cloud_map_id_deprecated',
    'google_maps_markers_rebuilt_in_build',
    'google_maps_set_map_style_deprecated',
    'google_maps_unknown_map_id_error_unchecked',
  },
  'google_sign_in': {
    'google_sign_in_auth_token_from_authenticate',
    'google_sign_in_authenticate_before_initialize',
    'google_sign_in_canceled_not_handled',
    'google_sign_in_missing_exception_handler',
    'google_sign_in_unchecked_supports_authenticate',
    'require_google_signin_error_handling',
  },
  'google_sign_in_7': {'avoid_pre_v7_google_sign_in'},
  'graphql': {'avoid_graphql_string_queries'},
  'hive': {
    'avoid_hive_binary_storage',
    'avoid_hive_box_name_collision',
    'avoid_hive_datetime_local',
    'avoid_hive_field_index_reuse',
    'avoid_hive_large_single_entry',
    'avoid_hive_synchronous_in_ui',
    'avoid_hive_type_modification',
    'prefer_hive_compact',
    'prefer_hive_compact_periodically',
    'prefer_hive_encryption',
    'prefer_hive_lazy_box',
    'prefer_hive_value_listenable',
    'prefer_hive_web_aware',
    'prefer_lazy_box_for_large',
    'require_hive_adapter_registration_order',
    'require_hive_box_close',
    'require_hive_database_close',
    'require_hive_encryption_key_secure',
    'require_hive_field_default_value',
    'require_hive_initialization',
    'require_hive_migration_strategy',
    'require_hive_nested_object_adapter',
    'require_hive_type_adapter',
    'require_hive_type_id_management',
    'require_hive_web_subdirectory',
    'require_type_adapter_registration',
  },
  'home_widget': {
    'home_widget_callback_missing_pragma',
    'home_widget_callback_not_top_level',
    'home_widget_ios_missing_app_group',
    'home_widget_save_without_update',
    'home_widget_update_no_name',
    'home_widget_widget_clicked_without_initial_launch',
  },
  'http': {
    'avoid_http_string_url',
    'avoid_http_top_level_in_loop',
    'require_http_package_client_close',
  },
  'image_picker': {
    'avoid_image_picker_quick_succession',
    'image_picker_camera_source_without_support_check',
    'image_picker_invalid_image_quality',
    'image_picker_lost_data_empty_check_missing',
    'image_picker_missing_retrieve_lost_data',
    'image_picker_multi_result_unchecked_empty',
    'prefer_image_picker_max_dimensions',
  },
  'in_app_review': {
    'in_app_review_button_callback_request',
    'in_app_review_ios_store_listing_missing_app_id',
    'in_app_review_missing_availability_check',
    'in_app_review_missing_store_listing_fallback',
    'in_app_review_request_in_init_state',
  },
  'isar': {
    'avoid_cached_isar_stream',
    'avoid_isar_clear_in_production',
    'avoid_isar_embedded_large_objects',
    'avoid_isar_enum_field',
    'avoid_isar_float_equality_queries',
    'avoid_isar_import_with_drift',
    'avoid_isar_schema_breaking_changes',
    'avoid_isar_string_contains_without_index',
    'avoid_isar_transaction_nesting',
    'avoid_isar_web_limitations',
    'prefer_isar_async_writes',
    'prefer_isar_batch_operations',
    'prefer_isar_composite_index',
    'prefer_isar_for_complex_queries',
    'prefer_isar_index_for_queries',
    'prefer_isar_lazy_links',
    'prefer_isar_query_stream',
    'require_isar_close_on_dispose',
    'require_isar_collection_annotation',
    'require_isar_id_field',
    'require_isar_inspector_debug_only',
    'require_isar_links_load',
    'require_isar_nullable_field',
  },
  'local_auth': {
    'local_auth_biometric_only_sensitive',
    'local_auth_missing_capability_check',
    'local_auth_missing_lockout_handling',
    'local_auth_unchecked_result',
    'local_auth_unhandled_exception',
  },
  'local_auth_3': {
    'local_auth_deprecated_options_class',
    'local_auth_platform_exception_catch',
    'local_auth_sticky_auth_renamed',
    'local_auth_use_error_dialogs_removed',
  },
  'lottie': {
    'lottie_controller_missing_on_loaded',
    'lottie_frame_rate_max_without_render_cache',
    'lottie_network_missing_background_loading',
    'lottie_network_missing_error_builder',
    'lottie_render_cache_raster_large_risk',
  },
  'openai': {'avoid_openai_key_in_code', 'require_openai_error_handling'},
  'permission_handler': {
    'permission_handler_batched_request_preferred',
    'permission_handler_deprecated_calendar',
    'permission_handler_location_always_before_when_in_use',
    'permission_handler_request_in_build',
    'permission_handler_status_without_request',
  },
  'provider': {
    'avoid_change_notifier_in_widget',
    'avoid_instantiating_in_value_provider',
    'avoid_nested_providers',
    'avoid_provider_in_init_state',
    'avoid_provider_in_widget',
    'avoid_provider_listen_false_in_build',
    'avoid_provider_of_in_build',
    'avoid_provider_recreate',
    'avoid_provider_value_rebuild',
    'avoid_watch_in_callbacks',
    'dispose_provided_instances',
    'dispose_provider_instances',
    'prefer_change_notifier_proxy',
    'prefer_change_notifier_proxy_provider',
    'prefer_consumer_over_provider_of',
    'prefer_context_read_in_callbacks',
    'prefer_multi_provider',
    'prefer_nullable_provider_types',
    'prefer_provider_extensions',
    'prefer_proxy_provider',
    'prefer_selector_over_consumer',
    'prefer_selector_widget',
    'require_multi_provider',
    'require_provider_dispose',
    'require_provider_generic_type',
    'require_provider_update_should_notify',
    'require_update_callback',
    'require_update_should_notify',
  },
  'qr_scanner': {
    'avoid_qr_scanner_always_active',
    'require_qr_content_validation',
    'require_qr_scan_feedback',
  },
  'quick_actions': {
    'quick_actions_empty_localized_title',
    'quick_actions_empty_shortcut_type',
    'quick_actions_flutter_asset_icon',
    'quick_actions_missing_initialize',
    'quick_actions_set_before_initialize',
  },
  'receive_sharing_intent': {
    'rsi_missing_initial_media',
    'rsi_missing_reset_after_initial_media',
    'rsi_unfiltered_shared_media_type',
  },
  'riverpod': {
    'avoid_assigning_notifiers',
    'avoid_circular_provider_deps',
    'avoid_global_riverpod_providers',
    'avoid_listen_in_async',
    'avoid_notifier_constructors',
    'avoid_nullable_async_value_pattern',
    'avoid_ref_in_build_body',
    'avoid_ref_in_dispose',
    'avoid_ref_inside_state_dispose',
    'avoid_ref_read_inside_build',
    'avoid_ref_watch_outside_build',
    'avoid_riverpod_for_network_only',
    'avoid_riverpod_navigation',
    'avoid_riverpod_notifier_in_build',
    'avoid_riverpod_state_mutation',
    'avoid_riverpod_string_provider_name',
    'avoid_unnecessary_consumer_widgets',
    'prefer_consumer_widget',
    'prefer_context_selector',
    'prefer_family_for_params',
    'prefer_immutable_provider_arguments',
    'prefer_ref_watch_over_read',
    'prefer_riverpod_auto_dispose',
    'prefer_riverpod_code_gen',
    'prefer_riverpod_family_for_params',
    'prefer_riverpod_keep_alive',
    'prefer_riverpod_select',
    'prefer_select_for_partial',
    'require_async_value_order',
    'require_auto_dispose',
    'require_error_handling_in_async',
    'require_flutter_riverpod_not_riverpod',
    'require_flutter_riverpod_package',
    'require_provider_scope',
    'require_riverpod_async_value_guard',
    'require_riverpod_error_handling',
    'require_riverpod_lint',
    'use_ref_and_state_synchronously',
    'use_ref_read_synchronously',
  },
  'riverpod_2': {'prefer_notifier_over_state'},
  'riverpod_3': {'avoid_riverpod_state_notifier'},
  'rxdart': {
    'avoid_behavior_subject_last_value',
    'prefer_rxdart_for_complex_streams',
  },
  'sensors_plus': {
    'sensors_plus_fastest_interval',
    'sensors_plus_missing_on_error',
    'sensors_plus_no_sampling_period',
  },
  'sensors_plus_4': {'prefer_sensors_event_stream'},
  'share_plus': {
    'share_plus_empty_share_params',
    'share_plus_missing_position_origin',
    'share_plus_unchecked_result',
    'share_plus_uri_and_text_conflict',
  },
  'share_plus_11': {'prefer_shareplus_instance'},
  'shared_preferences': {
    'avoid_auth_state_in_prefs',
    'avoid_prefs_for_large_data',
    'avoid_shared_prefs_in_isolate',
    'avoid_shared_prefs_large_data',
    'avoid_shared_prefs_sensitive_data',
    'avoid_shared_prefs_sync_race',
    'prefer_encrypted_prefs',
    'prefer_shared_prefs_async_api',
    'prefer_typed_prefs_wrapper',
    'require_shared_prefs_key_constants',
    'require_shared_prefs_null_handling',
    'require_shared_prefs_prefix',
  },
  'sign_in_with_apple': {
    'apple_sign_in_null_identity_token',
    'apple_sign_in_relying_on_name_email',
    'apple_sign_in_unchecked_availability',
    'apple_sign_in_unchecked_credential_state',
    'apple_sign_in_unhandled_authorization_exception',
    'apple_sign_in_unhandled_cancel',
    'require_apple_signin_nonce',
  },
  'speech_to_text': {'require_speech_stop_on_dispose'},
  'sqflite': {
    'avoid_sqflite_type_mismatch',
    'prefer_sqflite_encryption',
    'require_sqflite_index_for_queries',
  },
  'supabase': {
    'avoid_supabase_anon_key_in_code',
    'require_supabase_error_handling',
    'require_supabase_realtime_unsubscribe',
  },
  'url_launcher': {
    'avoid_url_launcher_simulator_tests',
    'prefer_url_launcher_fallback',
    'require_url_launcher_can_launch_check',
    'require_url_launcher_mode',
  },
  'uuid': {'prefer_uuid_v4'},
  'webview_flutter': {
    'avoid_pre_v4_webview_widget',
    'avoid_webview_file_access',
    'require_webview_ssl_error_handling',
  },
  'workmanager': {
    'require_workmanager_constraints',
    'require_workmanager_for_background',
    'require_workmanager_result_return',
  },
  'youtube_player_flutter': {
    'youtube_player_auto_fullscreen_without_portrait_guard',
    'youtube_player_controller_not_closed',
    'youtube_player_convert_url_unchecked',
    'youtube_player_mute_not_respected_in_params',
    'youtube_player_scaffold_deprecated',
  },
};

/// Pubspec markers for generated packs (keep extension rulePackDefinitions in sync).
const Map<String, Set<String>> kRulePackPubspecMarkersGenerated = {
  'app_links': {'app_links'},
  'app_links_6': {'app_links'},
  'audioplayers': {'audioplayers'},
  'auto_route': {'auto_route'},
  'awesome_notifications': {'awesome_notifications'},
  'bloc': {'bloc', 'flutter_bloc', 'hydrated_bloc'},
  'bloc_8': {'bloc', 'flutter_bloc', 'hydrated_bloc'},
  'cached_network_image': {'cached_network_image'},
  'connectivity_plus': {'connectivity_plus'},
  'connectivity_plus_6': {'connectivity_plus'},
  'device_calendar': {'device_calendar'},
  'dio': {'dio'},
  'dio_5': {'dio'},
  'drift': {'drift', 'drift_dev'},
  'envied': {'envied'},
  'equatable': {'equatable'},
  'file_picker': {'file_picker'},
  'file_picker_10': {'file_picker'},
  'file_picker_12': {'file_picker'},
  'firebase': {
    'cloud_firestore',
    'firebase_analytics',
    'firebase_auth',
    'firebase_core',
    'firebase_messaging',
    'firebase_storage',
  },
  'flame': {'flame'},
  'flutter_animate': {'flutter_animate'},
  'flutter_hooks': {'flutter_hooks'},
  'flutter_keyboard_visibility': {'flutter_keyboard_visibility'},
  'flutter_map': {'flutter_map'},
  'flutter_svg': {'flutter_svg'},
  'flutter_svg_2': {'flutter_svg'},
  'geocoding': {'geocoding'},
  'geolocator': {'geolocator'},
  'get_it': {'get_it'},
  'getx': {'get', 'getx'},
  'go_router_6': {'go_router'},
  'google_fonts': {'google_fonts'},
  'google_maps_flutter': {'google_maps_flutter'},
  'google_sign_in': {'google_sign_in'},
  'google_sign_in_7': {'google_sign_in'},
  'graphql': {'graphql'},
  'hive': {'hive', 'hive_flutter'},
  'home_widget': {'home_widget'},
  'http': {'http'},
  'image_picker': {'image_picker'},
  'in_app_review': {'in_app_review'},
  'isar': {'isar', 'isar_flutter_libs'},
  'local_auth': {'local_auth'},
  'local_auth_3': {'local_auth'},
  'lottie': {'lottie'},
  'openai': {'chat_gpt_sdk'},
  'permission_handler': {'permission_handler'},
  'provider': {'provider'},
  'qr_scanner': {'mobile_scanner', 'qr_flutter'},
  'quick_actions': {'quick_actions'},
  'receive_sharing_intent': {'receive_sharing_intent'},
  'riverpod': {'flutter_riverpod', 'hooks_riverpod', 'riverpod'},
  'riverpod_2': {'flutter_riverpod', 'hooks_riverpod', 'riverpod'},
  'riverpod_3': {'flutter_riverpod', 'hooks_riverpod', 'riverpod'},
  'rxdart': {'rxdart'},
  'sensors_plus': {'sensors_plus'},
  'sensors_plus_4': {'sensors_plus'},
  'share_plus': {'share_plus'},
  'share_plus_11': {'share_plus'},
  'shared_preferences': {'shared_preferences'},
  'sign_in_with_apple': {'sign_in_with_apple'},
  'speech_to_text': {'speech_to_text'},
  'sqflite': {'sqflite'},
  'supabase': {'supabase', 'supabase_flutter'},
  'url_launcher': {'url_launcher'},
  'uuid': {'uuid'},
  'webview_flutter': {'webview_flutter'},
  'workmanager': {'workmanager'},
  'youtube_player_flutter': {'youtube_player_flutter', 'youtube_player_iframe'},
};
