analyzer:
  plugins:
    - custom_lint
  errors:
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    todo: ignore
    fixme: ignore
    hack: ignore

# Configure saropa_lints tier
custom_lint:
  saropa_lints:
    tier: recommended
  rules:
    - prefer_multi_bloc_provider: true
    - prefer_correct_bloc_provider: true
    - prefer_multi_provider: true
    - require_google_signin_error_handling: true
    - require_supabase_error_handling: true
    - require_workmanager_constraints: true
    - require_svg_error_handler: true
    - require_google_fonts_fallback: true
    - require_extend_equatable: true
    - prefer_equatable_mixin: true
    - require_dispose: false
    - avoid_undisposed_instances: false
