import * as assert from 'assert';

import {
  applicableDisabledPacks,
  compareSemver,
  parseLockVersions,
  satisfiesMinConstraint,
} from '../../rulePacks/upgradePackNudgeLogic';

describe('upgradePackNudgeLogic', () => {
  describe('parseLockVersions', () => {
    it('extracts resolved versions from a pubspec.lock', () => {
      const lock = [
        '# Generated by pub',
        'packages:',
        '  dio:',
        '    dependency: "direct main"',
        '    source: hosted',
        '    version: "5.4.0"',
        '  collection:',
        '    dependency: transitive',
        '    version: "1.19.1"',
        'sdks:',
        '  dart: ">=3.0.0 <4.0.0"',
      ].join('\n');
      const m = parseLockVersions(lock);
      assert.strictEqual(m.get('dio'), '5.4.0');
      assert.strictEqual(m.get('collection'), '1.19.1');
      assert.strictEqual(m.has('dart'), false);
    });
  });

  describe('compareSemver / satisfiesMinConstraint', () => {
    it('compares numeric segments', () => {
      assert.ok(compareSemver('5.4.0', '5.0.0') > 0);
      assert.ok(compareSemver('4.0.6', '5.0.0') < 0);
      assert.strictEqual(compareSemver('2.0.0', '2.0.0'), 0);
    });

    it('honors >= constraints', () => {
      assert.ok(satisfiesMinConstraint('5.0.0', '>=5.0.0'));
      assert.ok(satisfiesMinConstraint('5.4.3', '>=5.0.0'));
      assert.ok(!satisfiesMinConstraint('4.0.6', '>=5.0.0'));
      // Build / prerelease suffixes are tolerated (leading x.y.z is parsed).
      assert.ok(satisfiesMinConstraint('6.0.0-beta.1', '>=6.0.0'));
    });
  });

  describe('applicableDisabledPacks', () => {
    it('returns dio_5 when dio resolves >=5.0.0 and the pack is off', () => {
      const lock = new Map([['dio', '5.4.0']]);
      const ids = applicableDisabledPacks(lock, new Set()).map((d) => d.id);
      assert.ok(ids.includes('dio_5'));
    });

    it('excludes dio_5 when dio is 4.x', () => {
      const lock = new Map([['dio', '4.0.6']]);
      const ids = applicableDisabledPacks(lock, new Set()).map((d) => d.id);
      assert.ok(!ids.includes('dio_5'));
    });

    it('excludes a pack that is already enabled', () => {
      const lock = new Map([['dio', '5.4.0']]);
      const ids = applicableDisabledPacks(lock, new Set(['dio_5'])).map((d) => d.id);
      assert.ok(!ids.includes('dio_5'));
    });

    it('excludes SDK packs (handled by a separate flow)', () => {
      const lock = new Map([['flutter', '3.38.0']]);
      const ids = applicableDisabledPacks(lock, new Set()).map((d) => d.id);
      assert.ok(!ids.some((id) => id.startsWith('flutter_sdk_')));
    });
  });
});
