analyzer:
  plugins:
    - custom_lint
  errors:
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    todo: ignore
    fixme: ignore
    hack: ignore

# Configure saropa_lints tier
custom_lint:
  saropa_lints:
    tier: recommended
  rules:
    - prefer_no_commented_out_code: true
    - prefer_capitalized_comment_start: true
    - prefer_explicit_type_arguments: true
    - require_dispose: false
    - avoid_undisposed_instances: false
