/// Module overview (comment coverage pass).
/// comment-coverage: module overview (batch).
///
/// Analyzer-backed tests for `init_emit_ci_test` (init `--emit-ci`).
///
/// Uses `// LINT` markers and `example/` fixtures per CONTRIBUTING.md.
library;

import 'dart:io';

import 'package:saropa_lints/src/init/cli_args.dart';
import 'package:saropa_lints/src/init/emit_ci_workflow.dart';
import 'package:test/test.dart';

import '../support/safe_delete.dart';

// emit_ci_workflow: emitted GitHub Actions workflow file for --emit-ci.

void main() {
  test('emitCiWorkflow writes a workflow with the provenance header', () {
    final dir = Directory.systemTemp.createTempSync('saropa_emit_ci_');
    try {
      final outFile = File('${dir.path}/.github/workflows/saropa-lints.yml');
      final result = emitCiWorkflow(outFile, dryRun: false);

      expect(result, EmitCiResult.written);
      expect(outFile.existsSync(), isTrue);

      final contents = outFile.readAsStringSync();
      // The provenance header is load-bearing: later tooling reads the
      // `managed-by` marker to tell a generated-and-untouched file apart
      // from one a human has since hand-edited.
      expect(
        contents,
        startsWith(
          '# Generated by saropa_lints init --emit-ci\n'
          '# managed-by: saropa_lints\n',
        ),
      );
      expect(contents, contains('uses: saropa/saropa_lints@v16.2.1'));
      // Never the moving major-version tag: the release process only ever
      // creates exact tags, so `@v16` would not resolve.
      expect(contents, isNot(contains('saropa_lints@v16\n')));
      expect(contents, contains("since: origin/\${{ github.base_ref }}"));
      expect(contents, contains('mode: annotate'));
      expect(contents, contains('security-events: write'));
      expect(contents, contains('contents: read'));
    } finally {
      safeDeleteDir(dir);
    }
  });

  test('emitCiWorkflow --dry-run writes nothing', () {
    final dir = Directory.systemTemp.createTempSync('saropa_emit_ci_');
    try {
      final outFile = File('${dir.path}/.github/workflows/saropa-lints.yml');
      final result = emitCiWorkflow(outFile, dryRun: true);

      expect(result, EmitCiResult.wouldWrite);
      expect(outFile.existsSync(), isFalse);
      expect(Directory('${dir.path}/.github').existsSync(), isFalse);
    } finally {
      safeDeleteDir(dir);
    }
  });

  test('emitCiWorkflow refuses to overwrite an existing file', () {
    final dir = Directory.systemTemp.createTempSync('saropa_emit_ci_');
    try {
      final outFile = File('${dir.path}/.github/workflows/saropa-lints.yml')
        ..createSync(recursive: true)
        ..writeAsStringSync('# hand-edited\n');

      final result = emitCiWorkflow(outFile, dryRun: false);

      expect(result, EmitCiResult.refusedExists);
      // Untouched: the existing content must survive the refusal.
      expect(outFile.readAsStringSync(), '# hand-edited\n');
    } finally {
      safeDeleteDir(dir);
    }
  });

  test('parseArguments accepts --emit-ci default path', () {
    final args = parseArguments(['--emit-ci']);
    expect(args.emitCi, '.github/workflows/saropa-lints.yml');
  });

  test('parseArguments accepts explicit --emit-ci path', () {
    final args = parseArguments(['--emit-ci', 'ci/lints.yml']);
    expect(args.emitCi, 'ci/lints.yml');
  });
}
