/// Module overview (comment coverage pass).
/// comment-coverage: module overview (batch).
///
/// Analyzer-backed tests for `init_emit_ci_test` (init `--emit-ci`).
///
/// Uses `// LINT` markers and `example/` fixtures per CONTRIBUTING.md.
library;

import 'dart:io';

import 'package:saropa_lints/saropa_lints.dart' show saropaLintsVersion;
import 'package:saropa_lints/src/init/cli_args.dart';
import 'package:saropa_lints/src/init/emit_ci_workflow.dart';
import 'package:test/test.dart';

import '../support/safe_delete.dart';

// emit_ci_workflow: emitted GitHub Actions workflow file for --emit-ci.

void main() {
  test('emitCiWorkflow writes a workflow with the provenance header', () {
    final dir = Directory.systemTemp.createTempSync('saropa_emit_ci_');
    try {
      final outFile = File('${dir.path}/.github/workflows/saropa-lints.yml');
      final result = emitCiWorkflow(outFile, dryRun: false);

      expect(result, EmitCiResult.written);
      expect(outFile.existsSync(), isTrue);

      final contents = outFile.readAsStringSync();
      // The provenance header is load-bearing: later tooling reads the
      // `managed-by` marker to tell a generated-and-untouched file apart
      // from one a human has since hand-edited.
      expect(
        contents,
        startsWith(
          '# Generated by saropa_lints init --emit-ci\n'
          '# managed-by: saropa_lints\n',
        ),
      );
      // The pin must equal the version actually resolved at run time. An
      // earlier version of this test forbade the literal 'v16.2.1' to prove
      // the pin was no longer hardcoded — which failed in this repository,
      // whose own version WAS 16.2.1 at the time, so the correctly-derived
      // pin produced exactly the string being forbidden. Assert the contract
      // instead of a string the contract happens not to produce elsewhere.
      final String expectedRef = saropaLintsVersion == 'unknown'
          ? 'main'
          : 'v$saropaLintsVersion';
      expect(contents, contains('uses: saropa/saropa_lints@$expectedRef'));
      // Interpolation must actually have happened, and an unresolvable
      // version must never be dressed up as a real tag.
      expect(contents, isNot(contains(r'saropa_lints@$ref')));
      expect(contents, isNot(contains('saropa_lints@vunknown')));
      // Never the moving major-version tag: the release process only ever
      // creates exact tags, so `@v16` would not resolve.
      expect(contents, isNot(contains('saropa_lints@v16\n')));
      // `since` must NOT appear. It is an audit-only flag, and the action's
      // input validation rejects it under `scan` — which is what mode: gate
      // resolves to — so emitting it would produce a workflow that fails on
      // its first run. This assertion exists to stop it coming back.
      expect(contents, isNot(contains('since:')));
      // gate, not annotate: gate runs `scan`, which honors the project's own
      // analysis_options.yaml. annotate runs `audit`, which bypasses the
      // configured tier and reports all 2332 rules.
      expect(contents, contains('mode: gate'));
      // Reports without blocking. A project decides to enforce by removing
      // this line, once it is clean enough to.
      expect(contents, contains('continue-on-error: true'));
      // scan produces no SARIF, so the upload permission is not requested.
      expect(contents, isNot(contains('security-events')));
      expect(contents, contains('contents: read'));
    } finally {
      safeDeleteDir(dir);
    }
  });

  test('buildCiWorkflow pins the running version, never a broken ref', () {
    final withVersion = buildCiWorkflow(version: '16.3.0');
    expect(withVersion, contains('uses: saropa/saropa_lints@v16.3.0'));

    // A version that cannot be resolved must not become `@vunknown`, which
    // would look like a real tag and fail at run time.
    final unknown = buildCiWorkflow(version: 'unknown');
    expect(unknown, contains('uses: saropa/saropa_lints@main'));
    expect(unknown, isNot(contains('vunknown')));
    expect(unknown, contains('could not be determined'));
  });

  test('emitCiWorkflow --dry-run writes nothing', () {
    final dir = Directory.systemTemp.createTempSync('saropa_emit_ci_');
    try {
      final outFile = File('${dir.path}/.github/workflows/saropa-lints.yml');
      final result = emitCiWorkflow(outFile, dryRun: true);

      expect(result, EmitCiResult.wouldWrite);
      expect(outFile.existsSync(), isFalse);
      expect(Directory('${dir.path}/.github').existsSync(), isFalse);
    } finally {
      safeDeleteDir(dir);
    }
  });

  test('emitCiWorkflow refuses to overwrite an existing file', () {
    final dir = Directory.systemTemp.createTempSync('saropa_emit_ci_');
    try {
      final outFile = File('${dir.path}/.github/workflows/saropa-lints.yml')
        ..createSync(recursive: true)
        ..writeAsStringSync('# hand-edited\n');

      final result = emitCiWorkflow(outFile, dryRun: false);

      expect(result, EmitCiResult.refusedExists);
      // Untouched: the existing content must survive the refusal.
      expect(outFile.readAsStringSync(), '# hand-edited\n');
    } finally {
      safeDeleteDir(dir);
    }
  });

  test('parseArguments accepts --emit-ci default path', () {
    final args = parseArguments(['--emit-ci']);
    expect(args.emitCi, '.github/workflows/saropa-lints.yml');
  });

  test('parseArguments accepts explicit --emit-ci path', () {
    final args = parseArguments(['--emit-ci', 'ci/lints.yml']);
    expect(args.emitCi, 'ci/lints.yml');
  });
}
