/**
 * Rule pack metadata for the VS Code Rule Packs sidebar and pack detection.
 *
 * Each entry ties pubspec dependency names to the lint codes that belong to that
 * ecosystem pack. Optional gates hide a pack until SDK or dependency constraints
 * match the user project (see isPackDetected).
 *
 * GENERATED by tool/generate_rule_pack_registry.dart — do not edit by hand.
 */

/** One selectable pack: stable id, human label, markers, rules, optional gates. */
export interface RulePackDefinition {
  /** Pack id; matches Dart registry keys in kRulePackRuleCodesGenerated. */
  readonly id: string;
  /** Sidebar display name (title case from pack id). */
  readonly label: string;
  /** Pub package names whose presence in pubspec implies this pack may apply. */
  readonly matchPubNames: readonly string[];
  /** Lint rule codes enabled when this pack is on (subset of saropa_lints rules). */
  readonly ruleCodes: readonly string[];
  /** If set, pack is gated until this direct dependency satisfies the semver constraint. */
  readonly dependencyGate?: { readonly package: string; readonly constraint: string };
  /** If set, pack is gated until environment[sdkKey] lower bound satisfies constraint. */
  readonly sdkGate?: { readonly sdkKey: string; readonly constraint: string };
}

export const RULE_PACK_DEFINITIONS: readonly RulePackDefinition[] = [
  {
    id: 'auto_route',
    label: 'Auto Route',
    matchPubNames: ['auto_route'],
    ruleCodes: [
      'avoid_auto_route_context_navigation',
      'avoid_auto_route_keep_history_misuse',
      'prefer_auto_route_path_params_simple',
      'prefer_auto_route_typed_args',
      'require_auto_route_deep_link_config',
      'require_auto_route_full_hierarchy',
      'require_auto_route_guard_resume',
    ],
  },
  {
    id: 'bloc',
    label: 'Bloc',
    matchPubNames: ['bloc', 'flutter_bloc', 'hydrated_bloc'],
    ruleCodes: [
      'avoid_bloc_business_logic_in_ui',
      'avoid_bloc_context_dependency',
      'avoid_bloc_emit_after_close',
      'avoid_bloc_event_in_constructor',
      'avoid_bloc_event_mutation',
      'avoid_bloc_in_bloc',
      'avoid_bloc_listen_in_build',
      'avoid_bloc_public_fields',
      'avoid_bloc_public_methods',
      'avoid_bloc_state_mutation',
      'avoid_cubit_usage',
      'avoid_duplicate_bloc_event_handlers',
      'avoid_existing_instances_in_bloc_provider',
      'avoid_instantiating_in_bloc_value_provider',
      'avoid_large_bloc',
      'avoid_long_event_handlers',
      'avoid_overengineered_bloc_states',
      'avoid_passing_bloc_to_bloc',
      'avoid_passing_build_context_to_blocs',
      'avoid_returning_value_from_cubit_methods',
      'avoid_yield_in_on_event',
      'check_is_not_closed_after_async_gap',
      'emit_new_bloc_state_instances',
      'prefer_bloc_event_suffix',
      'prefer_bloc_extensions',
      'prefer_bloc_hydration',
      'prefer_bloc_listener_for_side_effects',
      'prefer_bloc_state_suffix',
      'prefer_bloc_transform',
      'prefer_copy_with_for_state',
      'prefer_correct_bloc_provider',
      'prefer_cubit_for_simple',
      'prefer_cubit_for_simple_state',
      'prefer_immutable_bloc_events',
      'prefer_immutable_bloc_state',
      'prefer_multi_bloc_provider',
      'prefer_sealed_bloc_events',
      'prefer_sealed_bloc_state',
      'prefer_sealed_events',
      'require_bloc_close',
      'require_bloc_consumer_when_both',
      'require_bloc_error_state',
      'require_bloc_event_sealed',
      'require_bloc_initial_state',
      'require_bloc_loading_state',
      'require_bloc_manual_dispose',
      'require_bloc_observer',
      'require_bloc_repository_abstraction',
      'require_bloc_repository_injection',
      'require_bloc_selector',
      'require_bloc_transformer',
      'require_error_state',
      'require_immutable_bloc_state',
      'require_initial_state',
    ],
  },
  {
    id: 'bloc_8',
    label: 'Bloc 8.x',
    matchPubNames: ['bloc', 'flutter_bloc', 'hydrated_bloc'],
    ruleCodes: [
      'avoid_bloc_map_event_to_state',
    ],
    dependencyGate: { package: 'bloc', constraint: '>=8.0.0' },
  },
  {
    id: 'collection_compat',
    label: 'collection_compat',
    matchPubNames: ['collection'],
    ruleCodes: [
      'avoid_collection_methods_with_unrelated_types',
    ],
    dependencyGate: { package: 'collection', constraint: '>=1.19.0' },
  },
  {
    id: 'dart_sdk_3_2',
    label: 'Dart SDK 3.2',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_legacy_jsboolean_return_assumptions',
      'avoid_removed_js_number_to_dart',
      'prefer_int_for_jsarray_with_length',
      'prefer_string_for_typeof_equals',
    ],
    sdkGate: { sdkKey: 'sdk', constraint: '>=3.2.0' },
  },
  {
    id: 'dart_sdk_3_4',
    label: 'Dart SDK 3.4',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_deprecated_expires_getter',
      'avoid_deprecated_file_system_delete_event_is_directory',
      'avoid_deprecated_has_next_iterator',
      'avoid_deprecated_list_constructor',
      'avoid_deprecated_network_interface_list_supported',
      'avoid_removed_abstract_class_instantiation_error',
      'avoid_removed_bidirectional_iterator',
      'avoid_removed_cast_error',
      'avoid_removed_cyclic_initialization_error',
      'avoid_removed_dart_developer_metrics',
      'avoid_removed_deferred_library',
      'avoid_removed_fall_through_error',
      'avoid_removed_max_user_tags_constant',
      'avoid_removed_nosuchmethoderror_default_constructor',
      'avoid_removed_null_thrown_error',
      'avoid_removed_provisional_annotation',
      'avoid_removed_proxy_annotation',
    ],
    sdkGate: { sdkKey: 'sdk', constraint: '>=3.4.0' },
  },
  {
    id: 'dio',
    label: 'Dio',
    matchPubNames: ['dio'],
    ruleCodes: [
      'avoid_dio_debug_print_production',
      'avoid_dio_form_data_leak',
      'avoid_dio_without_base_url',
      'prefer_dio_base_options',
      'prefer_dio_cancel_token',
      'prefer_dio_over_http',
      'prefer_dio_transformer',
      'require_dio_error_handling',
      'require_dio_interceptor_error_handler',
      'require_dio_response_type',
      'require_dio_retry_interceptor',
      'require_dio_singleton',
      'require_dio_ssl_pinning',
      'require_dio_timeout',
    ],
  },
  {
    id: 'dio_5',
    label: 'Dio 5.x',
    matchPubNames: ['dio'],
    ruleCodes: [
      'avoid_dio_error',
    ],
    dependencyGate: { package: 'dio', constraint: '>=5.0.0' },
  },
  {
    id: 'drift',
    label: 'Drift',
    matchPubNames: ['drift', 'drift_dev'],
    ruleCodes: [
      'avoid_drift_close_streams_in_tests',
      'avoid_drift_database_on_main_isolate',
      'avoid_drift_enum_index_reorder',
      'avoid_drift_foreign_key_in_migration',
      'avoid_drift_get_single_without_unique',
      'avoid_drift_insert_missing_conflict_target',
      'avoid_drift_lazy_database',
      'avoid_drift_log_statements_production',
      'avoid_drift_missing_updates_param',
      'avoid_drift_nullable_converter_mismatch',
      'avoid_drift_query_in_migration',
      'avoid_drift_raw_sql_interpolation',
      'avoid_drift_replace_without_all_columns',
      'avoid_drift_unsafe_web_storage',
      'avoid_drift_update_without_where',
      'avoid_drift_validate_schema_production',
      'avoid_drift_value_null_vs_absent',
      'avoid_isar_import_with_drift',
      'prefer_drift_batch_operations',
      'prefer_drift_foreign_key_declaration',
      'prefer_drift_isolate_sharing',
      'prefer_drift_use_columns_false',
      'require_await_in_drift_transaction',
      'require_drift_create_all_in_oncreate',
      'require_drift_database_close',
      'require_drift_equals_value',
      'require_drift_foreign_key_pragma',
      'require_drift_onupgrade_handler',
      'require_drift_read_table_or_null',
      'require_drift_reads_from',
      'require_drift_schema_version_bump',
      'require_drift_stream_cancel',
    ],
  },
  {
    id: 'equatable',
    label: 'Equatable',
    matchPubNames: ['equatable'],
    ruleCodes: [
      'avoid_equatable_datetime',
      'avoid_equatable_nested_equality',
      'avoid_mutable_field_in_equatable',
      'list_all_equatable_fields',
      'prefer_equatable_mixin',
      'prefer_equatable_stringify',
      'prefer_immutable_annotation',
      'prefer_record_over_equatable',
      'prefer_unmodifiable_collections',
      'require_copy_with_null_handling',
      'require_deep_equality_collections',
      'require_equatable_copy_with',
      'require_equatable_props_override',
      'require_extend_equatable',
    ],
  },
  {
    id: 'firebase',
    label: 'Firebase',
    matchPubNames: ['cloud_firestore', 'firebase_analytics', 'firebase_auth', 'firebase_core', 'firebase_messaging', 'firebase_storage'],
    ruleCodes: [
      'avoid_database_in_build',
      'avoid_firebase_realtime_in_build',
      'avoid_firebase_user_data_in_auth',
      'avoid_firestore_in_widget_build',
      'avoid_firestore_unbounded_query',
      'avoid_map_markers_in_build',
      'avoid_secure_storage_on_web',
      'avoid_storing_user_data_in_auth',
      'incorrect_firebase_event_name',
      'incorrect_firebase_parameter_name',
      'prefer_correct_topics',
      'prefer_deep_link_auth',
      'prefer_firebase_auth_persistence',
      'prefer_firebase_remote_config_defaults',
      'prefer_firebase_transaction_for_counters',
      'prefer_firestore_batch_write',
      'prefer_marker_clustering',
      'prefer_transaction_for_batch',
      'require_background_message_handler',
      'require_crashlytics_user_id',
      'require_database_index',
      'require_database_migration',
      'require_fcm_token_refresh_handler',
      'require_firebase_app_check',
      'require_firebase_app_check_production',
      'require_firebase_composite_index',
      'require_firebase_email_enumeration_protection',
      'require_firebase_error_handling',
      'require_firebase_init_before_use',
      'require_firebase_offline_persistence',
      'require_firebase_reauthentication',
      'require_firebase_token_refresh',
      'require_firestore_index',
      'require_firestore_security_rules',
      'require_map_idle_callback',
    ],
  },
  {
    id: 'flame',
    label: 'Flame',
    matchPubNames: ['flame'],
    ruleCodes: [
      'avoid_creating_vector_in_update',
      'avoid_redundant_async_on_load',
    ],
  },
  {
    id: 'flutter_hooks',
    label: 'Flutter Hooks',
    matchPubNames: ['flutter_hooks'],
    ruleCodes: [
      'avoid_conditional_hooks',
      'avoid_hooks_outside_build',
      'avoid_misused_hooks',
      'avoid_unnecessary_hook_widgets',
      'prefer_use_callback',
    ],
  },
  {
    id: 'flutter_sdk_3_0',
    label: 'Flutter SDK 3.0',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_removed_render_object_element_methods',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.0.0' },
  },
  {
    id: 'flutter_sdk_3_10',
    label: 'Flutter SDK 3.10',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_deprecated_flutter_test_window',
      'avoid_removed_appbar_backwards_compatibility',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.10.0' },
  },
  {
    id: 'flutter_sdk_3_16',
    label: 'Flutter SDK 3.16',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_deprecated_use_material3_copy_with',
      'prefer_utf8_encode',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.16.0' },
  },
  {
    id: 'flutter_sdk_3_18',
    label: 'Flutter SDK 3.18',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_key_event',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.18.0' },
  },
  {
    id: 'flutter_sdk_3_19',
    label: 'Flutter SDK 3.19',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_context_menu_builder',
      'prefer_keepalive_dispose',
      'prefer_pan_axis',
      'prefer_platform_menu_bar_child',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.19.0' },
  },
  {
    id: 'flutter_sdk_3_22',
    label: 'Flutter SDK 3.22',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_m3_text_theme',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.22.0' },
  },
  {
    id: 'flutter_sdk_3_24',
    label: 'Flutter SDK 3.24',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_iterable_cast',
      'prefer_overflow_bar_over_button_bar',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.24.0' },
  },
  {
    id: 'flutter_sdk_3_28',
    label: 'Flutter SDK 3.28',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_button_style_icon_alignment',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.28.0' },
  },
  {
    id: 'flutter_sdk_3_29',
    label: 'Flutter SDK 3.29',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_deprecated_on_surface_destroyed',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.29.0' },
  },
  {
    id: 'flutter_sdk_3_32',
    label: 'Flutter SDK 3.32',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_dropdown_menu_item_button_opacity_animation',
      'prefer_tabbar_theme_indicator_color',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.32.0' },
  },
  {
    id: 'flutter_sdk_3_35',
    label: 'Flutter SDK 3.35',
    matchPubNames: ['environment'],
    ruleCodes: [
      'prefer_dropdown_initial_value',
      'prefer_on_pop_with_result',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.35.0' },
  },
  {
    id: 'flutter_sdk_3_38',
    label: 'Flutter SDK 3.38',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_asset_manifest_json',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.38.0' },
  },
  {
    id: 'flutter_sdk_3_7',
    label: 'Flutter SDK 3.7',
    matchPubNames: ['environment'],
    ruleCodes: [
      'avoid_deprecated_animated_list_typedefs',
      'avoid_deprecated_use_inherited_media_query',
      'prefer_scrollbar_theme_of',
    ],
    sdkGate: { sdkKey: 'flutter', constraint: '>=3.7.0' },
  },
  {
    id: 'geolocator',
    label: 'Geolocator',
    matchPubNames: ['geolocator'],
    ruleCodes: [
      'avoid_continuous_location_updates',
      'avoid_geolocator_background_without_config',
      'prefer_geocoding_cache',
      'prefer_geolocation_coarse_location',
      'require_geolocator_battery_awareness',
    ],
  },
  {
    id: 'get_it',
    label: 'get_it',
    matchPubNames: ['get_it'],
    ruleCodes: [
      'avoid_getit_in_build',
      'prefer_injectable_package',
      'require_getit_dispose_registration',
      'require_getit_registration_order',
      'require_getit_reset_in_tests',
    ],
  },
  {
    id: 'getx',
    label: 'GetX',
    matchPubNames: ['get', 'getx'],
    ruleCodes: [
      'always_remove_getx_listener',
      'avoid_get_find_in_build',
      'avoid_getx_build_context_bypass',
      'avoid_getx_context_outside_widget',
      'avoid_getx_dialog_snackbar_in_controller',
      'avoid_getx_global_navigation',
      'avoid_getx_global_state',
      'avoid_getx_rx_inside_build',
      'avoid_getx_rx_nested_obs',
      'avoid_getx_static_context',
      'avoid_getx_static_get',
      'avoid_mutable_rx_variables',
      'avoid_obs_outside_controller',
      'avoid_tight_coupling_with_getx',
      'dispose_getx_fields',
      'prefer_getx_builder',
      'prefer_getx_builder_over_obx',
      'proper_getx_super_calls',
      'require_getx_binding',
      'require_getx_binding_routes',
      'require_getx_controller_dispose',
      'require_getx_lazy_put',
      'require_getx_permanent_cleanup',
      'require_getx_worker_dispose',
    ],
  },
  {
    id: 'graphql',
    label: 'GraphQL',
    matchPubNames: ['graphql'],
    ruleCodes: [
      'avoid_graphql_string_queries',
    ],
  },
  {
    id: 'hive',
    label: 'Hive',
    matchPubNames: ['hive', 'hive_flutter'],
    ruleCodes: [
      'avoid_hive_binary_storage',
      'avoid_hive_box_name_collision',
      'avoid_hive_datetime_local',
      'avoid_hive_field_index_reuse',
      'avoid_hive_large_single_entry',
      'avoid_hive_synchronous_in_ui',
      'avoid_hive_type_modification',
      'prefer_hive_compact',
      'prefer_hive_compact_periodically',
      'prefer_hive_encryption',
      'prefer_hive_lazy_box',
      'prefer_hive_value_listenable',
      'prefer_hive_web_aware',
      'prefer_lazy_box_for_large',
      'require_hive_adapter_registration_order',
      'require_hive_box_close',
      'require_hive_database_close',
      'require_hive_encryption_key_secure',
      'require_hive_field_default_value',
      'require_hive_initialization',
      'require_hive_migration_strategy',
      'require_hive_nested_object_adapter',
      'require_hive_type_adapter',
      'require_hive_type_id_management',
      'require_hive_web_subdirectory',
      'require_type_adapter_registration',
    ],
  },
  {
    id: 'isar',
    label: 'Isar',
    matchPubNames: ['isar', 'isar_flutter_libs'],
    ruleCodes: [
      'avoid_cached_isar_stream',
      'avoid_isar_clear_in_production',
      'avoid_isar_embedded_large_objects',
      'avoid_isar_enum_field',
      'avoid_isar_float_equality_queries',
      'avoid_isar_import_with_drift',
      'avoid_isar_schema_breaking_changes',
      'avoid_isar_string_contains_without_index',
      'avoid_isar_transaction_nesting',
      'avoid_isar_web_limitations',
      'prefer_isar_async_writes',
      'prefer_isar_batch_operations',
      'prefer_isar_composite_index',
      'prefer_isar_for_complex_queries',
      'prefer_isar_index_for_queries',
      'prefer_isar_lazy_links',
      'prefer_isar_query_stream',
      'require_isar_close_on_dispose',
      'require_isar_collection_annotation',
      'require_isar_id_field',
      'require_isar_inspector_debug_only',
      'require_isar_links_load',
      'require_isar_nullable_field',
    ],
  },
  {
    id: 'package_specific',
    label: 'Mixed packages',
    matchPubNames: [],
    ruleCodes: [
      'avoid_app_links_sensitive_params',
      'avoid_image_picker_quick_succession',
      'avoid_openai_key_in_code',
      'avoid_webview_file_access',
      'prefer_geolocator_distance_filter',
      'prefer_image_picker_max_dimensions',
      'prefer_uuid_v4',
      'require_analytics_error_handling',
      'require_apple_signin_nonce',
      'require_calendar_timezone_handling',
      'require_envied_obfuscation',
      'require_google_fonts_fallback',
      'require_google_signin_error_handling',
      'require_keyboard_visibility_dispose',
      'require_openai_error_handling',
      'require_speech_stop_on_dispose',
      'require_svg_error_handler',
      'require_url_launcher_mode',
      'require_webview_ssl_error_handling',
    ],
  },
  {
    id: 'provider',
    label: 'Provider',
    matchPubNames: ['provider'],
    ruleCodes: [
      'avoid_change_notifier_in_widget',
      'avoid_instantiating_in_value_provider',
      'avoid_nested_providers',
      'avoid_provider_in_init_state',
      'avoid_provider_in_widget',
      'avoid_provider_listen_false_in_build',
      'avoid_provider_of_in_build',
      'avoid_provider_recreate',
      'avoid_provider_value_rebuild',
      'avoid_watch_in_callbacks',
      'dispose_provided_instances',
      'dispose_provider_instances',
      'prefer_change_notifier_proxy',
      'prefer_change_notifier_proxy_provider',
      'prefer_consumer_over_provider_of',
      'prefer_context_read_in_callbacks',
      'prefer_multi_provider',
      'prefer_nullable_provider_types',
      'prefer_provider_extensions',
      'prefer_proxy_provider',
      'prefer_selector_over_consumer',
      'prefer_selector_widget',
      'require_multi_provider',
      'require_provider_dispose',
      'require_provider_generic_type',
      'require_provider_update_should_notify',
      'require_update_callback',
      'require_update_should_notify',
    ],
  },
  {
    id: 'qr_scanner',
    label: 'QR / scanner',
    matchPubNames: ['mobile_scanner', 'qr_flutter'],
    ruleCodes: [
      'avoid_qr_scanner_always_active',
      'require_qr_content_validation',
      'require_qr_scan_feedback',
    ],
  },
  {
    id: 'riverpod',
    label: 'Riverpod',
    matchPubNames: ['flutter_riverpod', 'hooks_riverpod', 'riverpod'],
    ruleCodes: [
      'avoid_assigning_notifiers',
      'avoid_circular_provider_deps',
      'avoid_global_riverpod_providers',
      'avoid_listen_in_async',
      'avoid_notifier_constructors',
      'avoid_nullable_async_value_pattern',
      'avoid_ref_in_build_body',
      'avoid_ref_in_dispose',
      'avoid_ref_inside_state_dispose',
      'avoid_ref_read_inside_build',
      'avoid_ref_watch_outside_build',
      'avoid_riverpod_for_network_only',
      'avoid_riverpod_navigation',
      'avoid_riverpod_notifier_in_build',
      'avoid_riverpod_state_mutation',
      'avoid_riverpod_string_provider_name',
      'avoid_unnecessary_consumer_widgets',
      'prefer_consumer_widget',
      'prefer_context_selector',
      'prefer_family_for_params',
      'prefer_immutable_provider_arguments',
      'prefer_ref_watch_over_read',
      'prefer_riverpod_auto_dispose',
      'prefer_riverpod_code_gen',
      'prefer_riverpod_family_for_params',
      'prefer_riverpod_keep_alive',
      'prefer_riverpod_select',
      'prefer_select_for_partial',
      'require_async_value_order',
      'require_auto_dispose',
      'require_error_handling_in_async',
      'require_flutter_riverpod_not_riverpod',
      'require_flutter_riverpod_package',
      'require_provider_scope',
      'require_riverpod_async_value_guard',
      'require_riverpod_error_handling',
      'require_riverpod_lint',
      'use_ref_and_state_synchronously',
      'use_ref_read_synchronously',
    ],
  },
  {
    id: 'riverpod_2',
    label: 'Riverpod 2.x',
    matchPubNames: ['flutter_riverpod', 'hooks_riverpod', 'riverpod'],
    ruleCodes: [
      'prefer_notifier_over_state',
    ],
    dependencyGate: { package: 'riverpod', constraint: '>=2.0.0' },
  },
  {
    id: 'riverpod_3',
    label: 'Riverpod 3.x',
    matchPubNames: ['flutter_riverpod', 'hooks_riverpod', 'riverpod'],
    ruleCodes: [
      'avoid_riverpod_state_notifier',
    ],
    dependencyGate: { package: 'riverpod', constraint: '>=3.0.0' },
  },
  {
    id: 'rxdart',
    label: 'RxDart',
    matchPubNames: ['rxdart'],
    ruleCodes: [
      'avoid_behavior_subject_last_value',
      'prefer_rxdart_for_complex_streams',
    ],
  },
  {
    id: 'shared_preferences',
    label: 'shared_preferences',
    matchPubNames: ['shared_preferences'],
    ruleCodes: [
      'avoid_auth_state_in_prefs',
      'avoid_prefs_for_large_data',
      'avoid_shared_prefs_in_isolate',
      'avoid_shared_prefs_large_data',
      'avoid_shared_prefs_sensitive_data',
      'avoid_shared_prefs_sync_race',
      'prefer_encrypted_prefs',
      'prefer_shared_prefs_async_api',
      'prefer_typed_prefs_wrapper',
      'require_shared_prefs_key_constants',
      'require_shared_prefs_null_handling',
      'require_shared_prefs_prefix',
    ],
  },
  {
    id: 'sqflite',
    label: 'sqflite',
    matchPubNames: ['sqflite'],
    ruleCodes: [
      'avoid_sqflite_type_mismatch',
      'prefer_sqflite_encryption',
      'require_sqflite_index_for_queries',
    ],
  },
  {
    id: 'supabase',
    label: 'Supabase',
    matchPubNames: ['supabase', 'supabase_flutter'],
    ruleCodes: [
      'avoid_supabase_anon_key_in_code',
      'require_supabase_error_handling',
      'require_supabase_realtime_unsubscribe',
    ],
  },
  {
    id: 'url_launcher',
    label: 'url_launcher',
    matchPubNames: ['url_launcher'],
    ruleCodes: [
      'avoid_url_launcher_simulator_tests',
      'prefer_url_launcher_fallback',
      'require_url_launcher_can_launch_check',
    ],
  },
  {
    id: 'workmanager',
    label: 'workmanager',
    matchPubNames: ['workmanager'],
    ruleCodes: [
      'require_workmanager_constraints',
      'require_workmanager_for_background',
      'require_workmanager_result_return',
    ],
  },
];

/** Lexicographic numeric segment compare for x.y.z strings (not full semver). */
function _compareSemver(a: string, b: string): number {
  const pa = a.split(".").map((x) => Number.parseInt(x, 10));
  const pb = b.split(".").map((x) => Number.parseInt(x, 10));
  const n = Math.max(pa.length, pb.length);
  for (let i = 0; i < n; i++) {
    const da = Number.isFinite(pa[i]) ? pa[i] : 0;
    const db = Number.isFinite(pb[i]) ? pb[i] : 0;
    if (da !== db) return da < db ? -1 : 1;
  }
  return 0;
}

/** Parse environment block for sdkKey and return a x.y.z lower bound if inferable. */
function _parseSdkLowerBoundFromPubspec(pubspecYamlContent: string, sdkKey: string): string | null {
  const envMatch = /^environment:\s*\n((?:[ \t]+.*\n)+)/m.exec(pubspecYamlContent);
  if (!envMatch) return null;
  const envBlock = envMatch[1] ?? "";
  for (const line of envBlock.split("\n")) {
    const trimmed = line.trimStart();
    if (!trimmed.startsWith(sdkKey + ':')) continue;
    const raw = trimmed.slice(sdkKey.length + 1).trim();
    const rawConstraint = raw.replace(/^['"]/, '').replace(/['"]\s*$/, '');
    if (!rawConstraint || rawConstraint.length === 0 || rawConstraint === "any") return null;
    const geMatch = />=\s*(\d+\.\d+\.\d+)/.exec(rawConstraint);
    const lower = geMatch?.[1] ?? (rawConstraint.startsWith("^") ? rawConstraint.slice(1).trim() : rawConstraint);
    const semver = /^\d+\.\d+\.\d+/.exec(lower)?.[0];
    if (semver) return semver;
  }
  return null;
}

/** True when constraint is >= style and parsed min is <= lowerBound (semver compare). */
function _constraintAllowsLowerBound(constraint: string, lowerBound: string): boolean {
  const c = constraint.trim();
  if (c.startsWith(">=")) {
    const min = /^>=\s*(\d+\.\d+\.\d+)/.exec(c)?.[1];
    if (!min) return false;
    return _compareSemver(lowerBound, min) >= 0;
  }
  return false;
}

/** True when pubspec markers / environment gates suggest the pack applies. */
export function isPackDetected(def: RulePackDefinition, pubspecContent: string): boolean {
  if (def.sdkGate) {
    const lower = _parseSdkLowerBoundFromPubspec(pubspecContent, def.sdkGate.sdkKey);
    if (!lower) return false;
    return _constraintAllowsLowerBound(def.sdkGate.constraint, lower);
  }
  return def.matchPubNames.some((n) => new RegExp('^\\s+' + n + '\\s*:', 'm').test(pubspecContent));
}
