/**
 * Stylistic (opinionated) rule pack metadata for the Config Dashboard.
 *
 * Stylistic rules are OFF in every tier (including pedantic); each is an
 * explicit per-rule opt-in. Conflicting categories use a pick-one radio so
 * the user cannot enable two contradictory rules at once. No dependency or
 * SDK gates apply — these are pure style choices.
 *
 * GENERATED by tool/generate_rule_pack_registry.dart — do not edit by hand.
 */

/** One stylistic pack: a named group of opinionated rules to opt into. */
export interface StylisticPackDefinition {
  /** Stable snake_case id derived from the category name. */
  readonly id: string;
  /** Display name (category name minus the conflict marker). */
  readonly label: string;
  /** 'pickOne' renders a radio group (mutually exclusive); 'multi' renders toggles. */
  readonly selectionMode: 'multi' | 'pickOne';
  /** Lint rule codes in this group (off by default). */
  readonly ruleCodes: readonly string[];
}

export const STYLISTIC_PACK_DEFINITIONS: readonly StylisticPackDefinition[] = [
  {
    id: 'debug_test_utility',
    label: 'Debug/Test utility',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_fail_test_case',
    ],
  },
  {
    id: 'ordering_sorting',
    label: 'Ordering & Sorting',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_member_ordering',
      'prefer_arguments_ordering',
      'prefer_sorted_parameters',
      'prefer_sorted_pattern_fields',
      'prefer_sorted_record_fields',
      'binary_expression_operand_order',
      'enforce_parameters_ordering',
      'enum_constants_ordering',
      'map_keys_ordering',
    ],
  },
  {
    id: 'naming_conventions',
    label: 'Naming conventions',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_no_getter_prefix',
      'prefer_kebab_tag_name',
      'prefer_capitalized_comment_start',
      'prefer_snake_case_files',
      'prefer_camel_case_method_names',
      'prefer_exception_suffix',
      'prefer_error_suffix',
      'prefer_trailing_underscore_for_unused',
      'prefer_sliver_prefix',
      'prefer_correct_callback_field_name',
      'prefer_correct_handler_name',
      'prefer_correct_setter_parameter_name',
      'prefer_bloc_event_suffix',
      'prefer_bloc_state_suffix',
      'prefer_use_prefix',
    ],
  },
  {
    id: 'boolean_naming',
    label: 'Boolean naming',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_boolean_prefixes',
      'prefer_descriptive_bool_names',
      'prefer_boolean_prefixes_for_params',
      'prefer_boolean_prefixes_for_locals',
    ],
  },
  {
    id: 'code_style_preferences',
    label: 'Code style preferences',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_no_continue_statement',
      'prefer_wildcard_for_unused_param',
      'prefer_rethrow_over_throw_e',
      'prefer_list_first',
      'prefer_list_last',
      'no_boolean_literal_compare',
      'prefer_returning_conditional_expressions',
      'prefer_duration_constants',
      'prefer_immediate_return',
      'prefer_for_in',
      'prefer_conditional_expressions',
      'prefer_returning_condition',
      'prefer_returning_conditionals',
      'prefer_pushing_conditional_expressions',
      'prefer_getter_over_method',
    ],
  },
  {
    id: 'function_parameter_style',
    label: 'Function & Parameter style',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_arrow_functions',
      'prefer_all_named_parameters',
      'prefer_inline_callbacks',
      'avoid_parameter_reassignment',
    ],
  },
  {
    id: 'widget_style',
    label: 'Widget style',
    selectionMode: 'multi',
    ruleCodes: [
      'avoid_shrink_wrap_in_scroll',
      'prefer_one_widget_per_file',
      'prefer_widget_methods_over_classes',
      'prefer_borderradius_circular',
      'avoid_small_text',
      'prefer_sized_box_square',
      'prefer_center_over_align',
      'prefer_spacing_over_sizedbox',
    ],
  },
  {
    id: 'class_record_style',
    label: 'Class & Record style',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_class_over_record_return',
      'prefer_private_underscore_prefix',
      'prefer_explicit_this',
    ],
  },
  {
    id: 'formatting',
    label: 'Formatting',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_blank_line_before_case',
      'prefer_blank_line_before_constructor',
      'prefer_blank_line_before_method',
      'prefer_blank_line_before_else',
      'prefer_blank_line_after_loop',
      'prefer_trailing_comma',
      'double_literal_format',
      'format_comment_style',
    ],
  },
  {
    id: 'comments_documentation',
    label: 'Comments & Documentation',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_todo_format',
      'prefer_fixme_format',
      'prefer_sentence_case_comments',
      'prefer_period_after_doc',
      'prefer_doc_comments_over_regular',
      'prefer_no_commented_out_code',
    ],
  },
  {
    id: 'testing_style',
    label: 'Testing style',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_expect_over_assert_in_tests',
    ],
  },
  {
    id: 'type_argument_style',
    label: 'Type argument style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_inferred_type_arguments',
      'prefer_explicit_type_arguments',
    ],
  },
  {
    id: 'variable_type_style',
    label: 'Variable type style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_type_over_var',
      'prefer_var_over_explicit_type',
    ],
  },
  {
    id: 'dynamic_vs_object',
    label: 'Dynamic vs Object',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_dynamic_over_object',
      'prefer_object_over_dynamic',
    ],
  },
  {
    id: 'import_style',
    label: 'Import style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_absolute_imports',
      'prefer_flat_imports',
      'prefer_grouped_imports',
      'prefer_named_imports',
      'prefer_relative_imports',
    ],
  },
  {
    id: 'quote_style',
    label: 'Quote style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_double_quotes',
      'prefer_single_quotes',
    ],
  },
  {
    id: 'apostrophe_style',
    label: 'Apostrophe style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_doc_curly_apostrophe',
      'prefer_doc_straight_apostrophe',
      'prefer_straight_apostrophe',
    ],
  },
  {
    id: 'string_building',
    label: 'String building',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_interpolation_over_concatenation',
      'prefer_concatenation_over_interpolation',
    ],
  },
  {
    id: 'exit_strategy',
    label: 'Exit strategy',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_early_return',
      'prefer_single_exit_point',
    ],
  },
  {
    id: 'boolean_comparison',
    label: 'Boolean comparison',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_implicit_boolean_comparison',
      'prefer_explicit_boolean_comparison',
    ],
  },
  {
    id: 'error_handling',
    label: 'Error handling',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_catch_over_on',
      'prefer_on_over_catch',
    ],
  },
  {
    id: 'exception_specificity',
    label: 'Exception specificity',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_specific_exceptions',
      'prefer_generic_exception',
    ],
  },
  {
    id: 'async_style',
    label: 'Async style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_await_over_then',
      'prefer_then_over_await',
    ],
  },
  {
    id: 'method_chaining',
    label: 'Method chaining',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_cascade_over_chained',
      'prefer_chained_over_cascade',
    ],
  },
  {
    id: 'spread_vs_addall',
    label: 'Spread vs addAll',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_spread_over_addall',
      'prefer_addall_over_spread',
    ],
  },
  {
    id: 'collection_conditionals',
    label: 'Collection conditionals',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_collection_if_over_ternary',
      'prefer_ternary_over_collection_if',
    ],
  },
  {
    id: 'null_ternary',
    label: 'Null ternary',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_if_null_over_ternary',
      'prefer_ternary_over_if_null',
    ],
  },
  {
    id: 'null_assignment',
    label: 'Null assignment',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_null_aware_assignment',
      'prefer_explicit_null_assignment',
    ],
  },
  {
    id: 'nullable_vs_late',
    label: 'Nullable vs late',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_nullable_over_late',
      'prefer_late_over_nullable',
    ],
  },
  {
    id: 'member_ordering',
    label: 'Member ordering',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_static_members_first',
      'prefer_instance_members_first',
      'prefer_public_members_first',
      'prefer_private_members_first',
    ],
  },
  {
    id: 'field_method_order',
    label: 'Field/method order',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_fields_before_methods',
      'prefer_methods_before_fields',
    ],
  },
  {
    id: 'constant_case',
    label: 'Constant case',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_lower_camel_case_constants',
      'prefer_screaming_case_constants',
    ],
  },
  {
    id: 'trailing_comma',
    label: 'Trailing comma',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_trailing_comma_always',
      'unnecessary_trailing_comma',
    ],
  },
  {
    id: 'blank_line_before_return',
    label: 'Blank line before return',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_blank_line_before_return',
      'prefer_no_blank_line_before_return',
    ],
  },
  {
    id: 'declaration_spacing',
    label: 'Declaration spacing',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_blank_line_after_declarations',
      'prefer_compact_declarations',
    ],
  },
  {
    id: 'member_spacing',
    label: 'Member spacing',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_blank_lines_between_members',
      'prefer_compact_class_members',
    ],
  },
  {
    id: 'container_vs_sizedbox',
    label: 'Container vs SizedBox',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_sizedbox_over_container',
      'prefer_container_over_sizedbox',
    ],
  },
  {
    id: 'expanded_vs_flexible',
    label: 'Expanded vs Flexible',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_expanded_over_flexible',
      'prefer_flexible_over_expanded',
    ],
  },
  {
    id: 'edgeinsets_style',
    label: 'EdgeInsets style',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_edgeinsets_symmetric',
      'prefer_edgeinsets_only',
    ],
  },
  {
    id: 'richtext_widget',
    label: 'RichText widget',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_text_rich_over_richtext',
      'prefer_richtext_over_text_rich',
    ],
  },
  {
    id: 'theme_colors',
    label: 'Theme colors',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_material_theme_colors',
      'prefer_explicit_colors',
    ],
  },
  {
    id: 'test_naming',
    label: 'Test naming',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_test_name_should_when',
      'prefer_test_name_descriptive',
    ],
  },
  {
    id: 'test_comments',
    label: 'Test comments',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_given_when_then_comments',
      'prefer_self_documenting_tests',
    ],
  },
  {
    id: 'test_expectations',
    label: 'Test expectations',
    selectionMode: 'pickOne',
    ruleCodes: [
      'prefer_single_expectation_per_test',
      'prefer_grouped_expectations',
    ],
  },
  {
    id: 'opinionated_rules',
    label: 'Opinionated rules',
    selectionMode: 'multi',
    ruleCodes: [
      'prefer_clip_r_superellipse',
      'prefer_clip_r_superellipse_clipper',
      'prefer_concise_variable_names',
      'prefer_constructor_assertion',
      'prefer_constructor_body_assignment',
      'prefer_curly_apostrophe',
      'prefer_default_enum_case',
      'prefer_descriptive_bool_names_strict',
      'prefer_descriptive_variable_names',
      'prefer_dot_shorthand',
      'prefer_exhaustive_enums',
      'prefer_explicit_types',
      'prefer_factory_for_validation',
      'prefer_fake_over_mock',
      'prefer_future_void_function_over_async_callback',
      'prefer_grouped_by_purpose',
      'prefer_guard_clauses',
      'prefer_initializing_formals',
      'prefer_keys_with_lookup',
      'prefer_map_entries_iteration',
      'prefer_mutable_collections',
      'prefer_no_blank_line_inside_blocks',
      'prefer_positive_conditions',
      'prefer_positive_conditions_first',
      'prefer_record_over_equatable',
      'prefer_required_before_optional',
      'prefer_single_blank_line_max',
      'prefer_super_parameters',
      'prefer_switch_statement',
      'prefer_sync_over_async_where_possible',
      'prefer_test_data_builder',
      'prefer_wheretype_over_where_is',
    ],
  },
];
