/// Reads rule configuration from a project's `analysis_options.yaml`.
///
/// Parses the `diagnostics:` section to determine which rules are
/// enabled/disabled, matching the format generated by the `init` command.
/// Also reads severity overrides from `analysis_options_custom.yaml`.
library;

import 'dart:io' show File, Platform;

/// Rule configuration loaded from a project's config files.
class ScanConfig {
  const ScanConfig({required this.enabledRules, required this.disabledRules});

  final Set<String> enabledRules;
  final Set<String> disabledRules;
}

/// Attempts to load rule config from the project at [projectRoot].
///
/// Returns `null` if no `analysis_options.yaml` exists or it has no
/// `diagnostics:` section. Uses the same regex patterns as the native
/// plugin's config loader.
ScanConfig? loadScanConfig(String projectRoot) {
  final enabled = <String>{};
  final disabled = <String>{};

  // Read severity overrides first (analysis_options_custom.yaml)
  _loadSeverityOverrides(projectRoot, enabled, disabled);

  // Read diagnostics section (analysis_options.yaml)
  final configContent = _readFile(projectRoot, 'analysis_options.yaml');
  if (configContent == null) return null;

  final sectionMatch = RegExp(
    r'^\s+diagnostics:\s*$',
    multiLine: true,
  ).firstMatch(configContent);
  if (sectionMatch == null) return null;

  final lines = configContent.substring(sectionMatch.end).split('\n');
  for (final line in lines) {
    if (line.trim().isEmpty || line.trimLeft().startsWith('#')) continue;
    if (!line.startsWith('      ')) break;

    final match = RegExp(r'^\s+([\w_]+):\s*(true|false)').firstMatch(line);
    if (match == null) continue;

    final ruleName = match.group(1);
    if (ruleName == null || ruleName.isEmpty) continue;

    if (match.group(2) == 'true') {
      enabled.add(ruleName);
      disabled.remove(ruleName);
    } else {
      disabled.add(ruleName);
      enabled.remove(ruleName);
    }
  }

  if (enabled.isEmpty && disabled.isEmpty) return null;
  return ScanConfig(enabledRules: enabled, disabledRules: disabled);
}

/// Parse severity overrides from `analysis_options_custom.yaml`.
///
/// Rules with ERROR/WARNING/INFO are implicitly enabled.
/// Rules with `false` are explicitly disabled.
void _loadSeverityOverrides(
  String projectRoot,
  Set<String> enabled,
  Set<String> disabled,
) {
  final content = _readFile(projectRoot, 'analysis_options_custom.yaml');
  if (content == null) return;

  final sectionMatch = RegExp(
    r'^severities:\s*$',
    multiLine: true,
  ).firstMatch(content);
  if (sectionMatch == null) return;

  final lines = content.substring(sectionMatch.end).split('\n');
  for (final line in lines) {
    if (line.trim().isEmpty || line.trimLeft().startsWith('#')) continue;
    if (!line.startsWith('  ')) break;

    final match = RegExp(r'^\s+(\w+):\s*(\S+)').firstMatch(line);
    if (match == null) continue;

    final ruleName = match.group(1);
    final value = match.group(2);
    if (ruleName == null || value == null) continue;

    final upper = value.toUpperCase();
    if (upper == 'FALSE') {
      disabled.add(ruleName);
    } else if (upper == 'ERROR' || upper == 'WARNING' || upper == 'INFO') {
      enabled.add(ruleName);
    }
  }
}

String? _readFile(String projectRoot, String filename) {
  final sep = Platform.pathSeparator;
  final file = File('$projectRoot$sep$filename');
  if (!file.existsSync()) return null;
  return file.readAsStringSync();
}
