// ignore_for_file: depend_on_referenced_packages, avoid_print

/// Standalone lint rule scanner that runs saropa_lints rules against
/// any Dart project without requiring the target to have saropa_lints
/// as a dependency.
///
/// Reads the project's `analysis_options.yaml` (generated by `init`)
/// to determine which rules to run. When [tier] is set, the tier's rule
/// union is the starting point instead of the config's `diagnostics:`
/// section, but any `diagnostics:` overrides present are still layered on
/// top. If no config exists and no tier is set, returns null to signal the
/// caller to prompt the user to run `init` first.
library;

import 'dart:io' as io;

import 'package:analyzer/analysis_rule/rule_context.dart';
import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart' show AstVisitor, CompilationUnit;
import 'package:analyzer/error/listener.dart';
import 'package:analyzer/file_system/physical_file_system.dart';
// ignore: implementation_imports -- no public API for StringSource (analyzer <=7.4.x)
import 'package:analyzer/src/string_source.dart';
import 'package:path/path.dart' as p;

import '../config/memory_mode.dart' show MemoryModeConfig;
import '../config/rule_lane.dart'
    show RuleLane, lightLaneRuleNames, setActiveRuleLane;
import '../config/runtime_tier_cap.dart';
import '../init/cli_args.dart' show tierOrder;
import '../../saropa_lints.dart';
import 'capturing_registry.dart';
import 'scan_config.dart';
import 'scan_diagnostic.dart';
import 'scan_rule_context.dart';
import 'scan_rule_tracer.dart';
import 'scan_walker.dart';

/// Optional sink for progress and error messages. When null, output goes
/// to stdout (messages) and stderr (progress). When set, all output is
/// sent to this callback so callers can suppress or redirect.
typedef ScanMessageSink = void Function(String message);

/// Scans Dart files using saropa_lints rules without the plugin framework.
class ScanRunner {
  ScanRunner({
    required this.targetPath,
    this.dartFiles,
    this.tier,
    this.enabledRuleNames,
    this.messageSink,
    this.applyExclusionsToFileList = true,
    this.debugRule,
    this.excludeLightLane = false,
    this.lane = RuleLane.full,
    this.laneStats = false,
    List<String> excludeGlobs = const [],
    List<String> includeGlobs = const [],
  })  : _excludePatterns = excludeGlobs.map(_globToRegex).toList(),
        _includePatterns = includeGlobs.map(_globToRegex).toList();

  /// Project root: config is loaded from here and relative [dartFiles] are resolved against it.
  final String targetPath;

  /// Optional explicit list of Dart files to scan. When null or empty, files are discovered under [targetPath].
  final List<String>? dartFiles;

  /// Optional tier name (e.g. `essential`, `recommended`, `pedantic`). When set,
  /// the rule set starts from this tier's union; the project's `diagnostics:`
  /// section (if present) is still layered on top, so a rule the user
  /// explicitly disabled stays disabled even though the tier includes it.
  final String? tier;

  /// Optional explicit set of rule names to enable, bypassing both [tier] and
  /// the project config. Takes precedence over [tier] when both are set. Lets a
  /// caller exercise a rule set that no single tier expresses — notably the
  /// union of every defined rule *including* stylistic rules, which no tier
  /// (not even `pedantic`) contains. Used by the accuracy report so that
  /// stylistic-tier rules are actually run and not falsely reported as silent.
  final Set<String>? enabledRuleNames;

  /// Optional sink for all messages. When null, messages go to stdout and progress to stderr.
  final ScanMessageSink? messageSink;

  /// When [dartFiles] is provided, whether to apply the same exclusions as directory discovery (e.g. `.g.dart`, `build/`). Default true.
  final bool applyExclusionsToFileList;

  /// When set, emits per-node trace output for the named rule, showing type
  /// resolution details at each visited AST node.
  final String? debugRule;

  /// Compiled glob patterns from `--exclude-globs` for user-specified path
  /// exclusions beyond the hardcoded defaults. Built once at construction from
  /// the raw glob strings so matching is a hot-path regex check, not a
  /// per-file glob parse. See #313.
  final List<RegExp> _excludePatterns;

  /// Compiled glob patterns from `--include-globs` that override the hardcoded
  /// exclusions. When a path matches both a hardcoded exclusion AND an include
  /// pattern, the include wins — letting users force-scan paths the defaults
  /// would skip (e.g. auditing third-party plugins in ephemeral dirs).
  final List<RegExp> _includePatterns;

  /// Drops light-lane rules from the scan's rule set.
  ///
  /// Set by the scan daemon when the project's in-process plugin is running
  /// the light lane: those rules already produce live analyzer squiggles, so
  /// scanning them again would report every severe finding twice in the
  /// Problems panel — once as an analyzer diagnostic and once from the
  /// extension's own `DiagnosticCollection`. Membership comes from the shared
  /// predicate in `lib/src/config/rule_lane.dart`, so the two sides cannot
  /// disagree about which rules the split covers.
  final bool excludeLightLane;

  /// Which lane the scan should use. Defaults to [RuleLane.full] so every
  /// enabled rule fires. Set to [RuleLane.light] via `--lane light` to
  /// restrict the scan to the same cheap, resolution-free subset the
  /// analysis server runs in its default lane.
  final RuleLane lane;

  /// When true, prints how many rules are in the light lane vs full-only,
  /// making the lane gate's effect observable. Activated by `--lane-stats`.
  final bool laneStats;

  /// Map from rule name to its declared LintImpact name (error/warning/info).
  /// Built by `_prepare` so [_collectDiagnostics] can stamp each diagnostic.
  Map<String, String> _ruleImpactMap = const {};

  /// Builds an [AnalysisContextCollection] rooted at [projectRoot] for a
  /// long-lived caller (the scan daemon) to hold and reuse across many
  /// [runResolvedWithCollection] calls. This is the expensive step
  /// [runResolved] otherwise repeats on every invocation.
  static AnalysisContextCollection buildProjectCollection(String projectRoot) {
    return AnalysisContextCollection(
      includedPaths: [p.normalize(p.absolute(projectRoot))],
      resourceProvider: PhysicalResourceProvider.INSTANCE,
    );
  }

  /// Writes to stdout (via messageSink or print). Reserved for opt-in
  /// diagnostic output (--debug-rule trace). All progress/status messages
  /// must use `_err` so --format json stdout stays machine-parseable.
  void _debugOut(String message) {
    if (messageSink != null) {
      messageSink!(message);
    } else {
      print(message);
    }
  }

  void _err(String message) {
    if (messageSink != null) {
      messageSink!(message);
    } else {
      io.stderr.writeln(message);
    }
  }

  void _progress(String message) {
    if (messageSink != null) {
      messageSink!(message);
    } else {
      io.stderr.write(message);
    }
  }

  /// Runs the default syntactic scan and returns all diagnostics found.
  ///
  /// Returns `null` if no configuration was found and no [tier] was set (caller should tell
  /// the user to run `init` first), or if [tier] was set to an unknown value.
  ///
  /// This is a purely syntactic pass (`parseString`, no resolution): it is
  /// fast, but rules registered on `addInstanceCreationExpression` and any
  /// type-based rule under-report — see [runResolved] for the resolved path.
  List<ScanDiagnostic>? run() {
    final plan = _prepare();
    if (plan == null) return null;
    if (plan.files.isEmpty) return const [];

    final registrations = _registerRules(
      plan.rules,
      () => ScanRuleContext(definingUnit: _dummyContextUnit()),
    );
    return _scanFiles(plan.files, registrations);
  }

  /// Runs the scan with full type/element resolution and returns all
  /// diagnostics found. Returns `null` under the same no-config / unknown-tier
  /// conditions as [run].
  ///
  /// Resolution rewrites implicit constructor calls (`File('x')`) into
  /// `InstanceCreationExpression` nodes and supplies a real `typeProvider`/
  /// `typeSystem`, so rules that [run] silently misses fire here. The cost: it
  /// builds an [AnalysisContextCollection] and resolves each unit, which is
  /// materially slower and requires the target project to have had `pub get`
  /// run (otherwise units fail to resolve and are skipped with a message).
  Future<List<ScanDiagnostic>?> runResolved() async {
    final plan = _prepare();
    if (plan == null) return null;
    if (plan.files.isEmpty) return const [];

    final registrations = _registerRules(
      plan.rules,
      () => ResolvedScanRuleContext(definingUnit: _dummyContextUnit()),
    );
    return _scanFilesResolved(plan.files, registrations);
  }

  /// Runs the resolved scan for [dartFiles] against an already-built
  /// [collection] instead of creating a new one.
  ///
  /// [runResolved] pays the cost of building an [AnalysisContextCollection]
  /// (full package-graph discovery, on the order of a minute on a large
  /// project) on every call — fine for a one-shot CLI invocation, ruinous for
  /// a save-triggered scan. A long-lived caller (the scan daemon) builds the
  /// collection once for the whole project and reuses it across requests;
  /// this method notifies the collection of the changed files via
  /// [AnalysisContext.changeFile]/[AnalysisContext.applyPendingFileChanges]
  /// so only the edited units are re-resolved, then scans them.
  Future<List<ScanDiagnostic>?> runResolvedWithCollection(
    AnalysisContextCollection collection,
  ) async {
    final plan = _prepare();
    if (plan == null) return null;
    if (plan.files.isEmpty) return const [];

    // A file the target project's analyzer config excludes (or one outside
    // the collection's roots entirely) makes contextFor throw a StateError.
    // For a save-triggered daemon request that must degrade to a skip — the
    // user saved a file their own config says not to analyze — not an error
    // response, so partition the request into scannable files + skips first.
    final absFiles = <String>[];
    for (final f in plan.files.map(p.absolute).map(p.normalize)) {
      try {
        collection.contextFor(f).changeFile(f);
        absFiles.add(f);
      } on StateError {
        _err('  Skipping (outside analysis roots or excluded): $f');
      }
    }
    if (absFiles.isEmpty) return const [];
    final affectedContexts = {
      for (final f in absFiles) collection.contextFor(f),
    };
    for (final ctx in affectedContexts) {
      await ctx.applyPendingFileChanges();
    }

    final registrations = _registerRules(
      plan.rules,
      () => ResolvedScanRuleContext(definingUnit: _dummyContextUnit()),
    );
    final diagnostics = <ScanDiagnostic>[];
    final visitorRule = _visitorRuleMap(registrations);
    for (final f in absFiles) {
      await _scanSingleFileResolved(
        collection,
        f,
        registrations,
        visitorRule,
        diagnostics,
      );
    }
    return diagnostics;
  }

  /// Shared setup for both scan paths: resolves the enabled rule set and the
  /// file list, printing the same progress messages [run] historically did.
  ///
  /// Returns `null` only for the exit-2 conditions (no config and no tier, or
  /// an unknown tier). Otherwise returns the rules and files; an empty `files`
  /// list means "nothing to scan" (all rules disabled, or no Dart files found)
  /// and the caller returns no diagnostics.
  ({List<SaropaLintRule> rules, List<String> files})? _prepare() {
    MemoryModeConfig.markCli();
    // The lane system limits in-process analysis server RSS by gating
    // expensive rules (usesTypeResolution, high cost, INFO severity) to the
    // full lane. The CLI scanner exits after one run, so RSS is irrelevant —
    // default to full coverage. Callers can pass RuleLane.light via --lane
    // to restrict the scan to the cheap subset.
    setActiveRuleLane(lane);
    reloadRuntimeTierCapFromProject(p.absolute(targetPath));
    // Reset before resolving, not after: _resolveRuleNames (via
    // _applyConfigOverrides / _loadRulesFromConfig) sets this when the
    // project has a diagnostics: section. Resetting afterward — the prior
    // order — always stomped that value back to null.
    SaropaLintRule.disabledRules = null;
    final resolved = _resolveRuleNames();
    if (resolved == null) return null;

    // Lane exclusion runs before the empty check so that "the light lane
    // covered everything you asked for" reports as nothing-to-scan rather
    // than scanning duplicates.
    var ruleNames = RuntimeTierCap.filterRuleSet(resolved);
    if (excludeLightLane) {
      // Light-lane membership is published as a side effect of the lazy
      // rule-registry build, which may not have happened yet. Without this
      // the set would still be empty here and the exclusion would silently
      // no-op into duplicate diagnostics.
      ensureRuleRegistryBuilt();
      final before = ruleNames.length;
      ruleNames = excludeLightLaneRules(ruleNames);
      // Progress message — stderr keeps stdout clean for JSON.
      _err(
        'Light lane excluded: $before → ${ruleNames.length} rules '
        '(the rest run live in the analysis server).',
      );
    }
    if (ruleNames.isEmpty) {
      _err('All rules are disabled in the configuration.');
      return (rules: const [], files: const []);
    }

    SaropaLintRule.enabledRules = ruleNames;
    final rules = getRulesFromRegistry(ruleNames);
    // Build the impact lookup so diagnostics carry the rule-declared impact.
    _ruleImpactMap = {
      for (final r in rules) r.code.lowerCaseName: r.impact.name,
    };
    // Copy nullable to local so promotion applies (avoid_nullable_interpolation).
    final tierLabel = tier;
    // Progress messages go to stderr so --format json stdout stays valid JSON.
    if (tierLabel != null) {
      _err('Loaded ${rules.length} rules for tier: $tierLabel');
    } else {
      _err('Loaded ${rules.length} rules from analysis_options.yaml');
    }

    // --lane-stats: show how the lane gate partitions the loaded rules.
    if (laneStats) {
      ensureRuleRegistryBuilt();
      final lightNames = lightLaneRuleNames;
      final lightCount =
          ruleNames.where((n) => lightNames.contains(n)).length;
      final fullOnly = ruleNames.length - lightCount;
      _err(
        'Lane stats: ${ruleNames.length} enabled, '
        '$lightCount light-lane, $fullOnly full-only. '
        'Active lane: ${lane.name}.',
      );
    }

    final filesToScan = _resolveDartFiles();
    if (filesToScan.isEmpty) {
      _err('No .dart files found in: $targetPath');
      return (rules: rules, files: const []);
    }
    _err('Scanning ${filesToScan.length} files...');
    return (rules: rules, files: filesToScan);
  }

  RuleContextUnit _dummyContextUnit() =>
      _createContextUnit('', p.absolute(targetPath));

  /// Resolves enabled rule names: from [tier] if set (validated via [tierOrder]), otherwise from project config.
  Set<String>? _resolveRuleNames() {
    // An explicit rule set wins over tier/config: it is the only way to run a
    // set no tier expresses (e.g. all rules including stylistic).
    final explicit = enabledRuleNames;
    if (explicit != null) return explicit;

    // Copy nullable to local for field promotion (avoid_nullable_interpolation).
    final tierLabel = tier;
    if (tierLabel != null) {
      final normalized = tierLabel.toLowerCase();
      if (!tierOrder.contains(normalized)) {
        _err(
          "Unknown tier: '$tierLabel'. Valid tiers: ${tierOrder.join(', ')}",
        );
        return null;
      }
      return _applyConfigOverrides(getRulesForTier(normalized));
    }
    return _loadRulesFromConfig();
  }

  /// Layers the project's `diagnostics:` overrides on top of [tierRules]: a
  /// rule the user explicitly turned off stays off even though the tier
  /// includes it, and a rule they explicitly turned on runs even if the tier
  /// wouldn't otherwise enable it. Silently a no-op when the project has no
  /// `diagnostics:` section (e.g. the scan-on-save daemon on a project that
  /// never ran `init`).
  Set<String> _applyConfigOverrides(Set<String> tierRules) {
    final config = loadScanConfig(p.absolute(targetPath));
    if (config == null) return tierRules;

    SaropaLintRule.disabledRules = config.disabledRules.isEmpty
        ? null
        : config.disabledRules;
    return tierRules
        .difference(config.disabledRules)
        .union(config.enabledRules);
  }

  /// Loads enabled rules from the project's analysis_options.yaml.
  ///
  /// Returns null if no config file or no diagnostics section found.
  Set<String>? _loadRulesFromConfig() {
    final config = loadScanConfig(p.absolute(targetPath));
    if (config == null) {
      final absPath = p.absolute(targetPath);
      _err('No saropa_lints configuration found in:');
      _err('  $absPath/analysis_options.yaml');
      _err('');
      _err('Run init first to configure rules:');
      _err('  dart run saropa_lints init --target $absPath');
      return null;
    }

    SaropaLintRule.disabledRules = config.disabledRules.isEmpty
        ? null
        : config.disabledRules;
    return config.enabledRules;
  }

  /// Resolves files to scan: [dartFiles] if non-empty (relative paths resolved
  /// against [targetPath], exclusions applied when [applyExclusionsToFileList]);
  /// otherwise discovers under [targetPath]. User-supplied `--exclude-globs`
  /// patterns are applied in both paths.
  List<String> _resolveDartFiles() {
    final raw = dartFiles;
    if (raw == null || raw.isEmpty) {
      return _findDartFiles(targetPath, _excludePatterns, _includePatterns);
    }
    final root = p.absolute(targetPath);
    var list = raw
        .where((path) => path.trim().isNotEmpty)
        .map(
          (path) => p.isAbsolute(path)
              ? p.normalize(path)
              : p.normalize(p.join(root, path)),
        )
        .where((path) => path.endsWith('.dart'))
        .toList();
    if (applyExclusionsToFileList) {
      // Combined exclusion/inclusion filter: _shouldInclude handles the
      // hardcoded defaults, user-supplied exclude-globs, and include-glob
      // overrides in one pass.
      list = list
          .where(
            (path) =>
                _shouldInclude(path, _excludePatterns, _includePatterns),
          )
          .toList();
    }
    return list;
  }

  /// Registers each rule's node visitors against a fresh context produced by
  /// [contextFactory]. The factory varies by scan path ([ScanRuleContext] for
  /// the syntactic pass, [ResolvedScanRuleContext] for `--resolve`); the rest
  /// of the registration loop is identical.
  List<_RuleRegistration> _registerRules(
    List<SaropaLintRule> rules,
    MutableRuleContext Function() contextFactory,
  ) {
    final result = <_RuleRegistration>[];

    for (final rule in rules) {
      final registry = CapturingRuleVisitorRegistry();
      final context = contextFactory();

      try {
        rule.registerNodeProcessors(registry, context);
      } on Object catch (e) {
        _err('  Skipping ${rule.code.lowerCaseName}: $e');
        continue;
      }

      var visitors = registry.capturedVisitors;
      if (visitors.isEmpty) continue;

      final dbg = debugRule;
      if (dbg != null && rule.code.lowerCaseName == dbg) {
        _debugOut(
          'DEBUG: tracing rule "$dbg" '
          '(${visitors.length} visitor(s))',
        );
        visitors = visitors
            .map(
              (v) =>
                  TracingVisitorWrapper(v as AstVisitor<void>, _debugOut, dbg),
            )
            .toList();
      }

      if (visitors.isNotEmpty) {
        result.add(_RuleRegistration(rule, visitors.cast(), context));
      }
    }

    return result;
  }

  List<ScanDiagnostic> _scanFiles(
    List<String> files,
    List<_RuleRegistration> registrations,
  ) {
    final diagnostics = <ScanDiagnostic>[];
    final sw = Stopwatch()..start();
    final visitorRule = _visitorRuleMap(registrations);

    for (var i = 0; i < files.length; i++) {
      // Abort hook: a `.saropa_stop` file in the scan target root stops the
      // walk between files. This must live HERE — the historical sentinel
      // path (SaropaLintRule._checkAbortSentinel) keys on
      // AnalysisReporter.projectRoot, which is null in the scan CLI, so it
      // never fired; and even when armed it only no-ops rule callbacks
      // without ending the file loop, leaving long scans unkillable except
      // by killing the process (which loses the report and timing profile).
      if (_stopSentinelHit(i, files.length, diagnostics.length)) break;
      _showProgress(i, files.length, diagnostics.length, files[i], sw);
      _scanSingleFile(files[i], registrations, visitorRule, diagnostics);
    }

    // Clear progress line when using stderr
    if (messageSink == null) {
      io.stderr.write('\r${' ' * 79}\r');
    }
    return diagnostics;
  }

  /// True when the user dropped a `.saropa_stop` file in the scan target
  /// root, requesting the scan stop early with a partial report.
  ///
  /// Checked once per file — a single `existsSync` is trivial next to the
  /// ~100ms of rule work an average file costs, and per-file checking keeps
  /// abort latency at one file instead of one batch. The sentinel is deleted
  /// on detection so the NEXT scan does not instantly abort on the leftover
  /// file; a delete failure (e.g. permissions) still aborts, because honoring
  /// the user's stop request matters more than the cleanup.
  bool _stopSentinelHit(int scanned, int total, int issueCount) {
    final sentinel = io.File(p.join(p.absolute(targetPath), '.saropa_stop'));
    try {
      if (!sentinel.existsSync()) return false;
    } on io.IOException {
      // Unreadable sentinel state: keep scanning rather than abort on an OS
      // error the user never asked for.
      return false;
    }
    try {
      sentinel.deleteSync();
    } on io.IOException {
      // Leave the stale sentinel; the abort itself still proceeds.
    }
    // Abort notice goes to stderr so stdout stays valid JSON.
    _err(
      '[saropa_lints] Scan aborted by .saropa_stop after '
      '$scanned/$total files ($issueCount issues so far). '
      'Partial report follows.',
    );
    return true;
  }

  void _scanSingleFile(
    String filePath,
    List<_RuleRegistration> registrations,
    Map<AstVisitor<void>, String> visitorRule,
    List<ScanDiagnostic> diagnostics,
  ) {
    final content = io.File(filePath).readAsStringSync();
    final unit = parseString(
      content: content,
      path: filePath,
      throwIfDiagnostics: false,
    ).unit;

    final listener = RecordingDiagnosticListener();
    final source = StringSource(content, filePath);
    final reporter = DiagnosticReporter(listener, source);
    final ctxUnit = _createContextUnit(content, filePath, unit: unit);

    final allVisitors = <AstVisitor<void>>[];
    for (final reg in registrations) {
      reg.context.currentUnit = ctxUnit;
      reg.rule.reporter = reporter;
      allVisitors.addAll(reg.visitors);
    }

    if (allVisitors.isNotEmpty) {
      unit.accept(
        ScanWalker(
          allVisitors,
          onError: _onVisitorError(visitorRule, filePath),
        ),
      );
    }

    _collectDiagnostics(listener, unit, filePath, diagnostics);
  }

  /// Maps each registered visitor back to its rule name so a visitor that
  /// throws mid-walk can be reported by name.
  Map<AstVisitor<void>, String> _visitorRuleMap(
    List<_RuleRegistration> registrations,
  ) {
    final map = <AstVisitor<void>, String>{};
    for (final reg in registrations) {
      final name = reg.rule.code.lowerCaseName;
      for (final v in reg.visitors) {
        map[v] = name;
      }
    }
    return map;
  }

  /// Builds the per-file error sink passed to [ScanWalker]. A rule that throws
  /// is reported (rule name + file) and disabled for the rest of that file's
  /// walk, so one buggy rule never aborts the whole scan.
  ScanVisitorError _onVisitorError(
    Map<AstVisitor<void>, String> visitorRule,
    String filePath,
  ) {
    return (visitor, error, stackTrace) {
      final rule = visitorRule[visitor] ?? 'unknown_rule';
      _err('  Rule "$rule" failed on ${p.basename(filePath)}: $error');
    };
  }

  /// Resolves and scans [files] one at a time, returning all diagnostics.
  ///
  /// A single [AnalysisContextCollection] spans every file so the analyzer's
  /// per-context caches are reused across the run. Paths are absolutized
  /// because the analyzer requires absolute, normalized paths.
  Future<List<ScanDiagnostic>> _scanFilesResolved(
    List<String> files,
    List<_RuleRegistration> registrations,
  ) async {
    final diagnostics = <ScanDiagnostic>[];
    final sw = Stopwatch()..start();
    final visitorRule = _visitorRuleMap(registrations);

    final absFiles = files.map(p.absolute).map(p.normalize).toList();
    final collection = AnalysisContextCollection(
      includedPaths: absFiles,
      resourceProvider: PhysicalResourceProvider.INSTANCE,
    );

    for (var i = 0; i < absFiles.length; i++) {
      _showProgress(i, absFiles.length, diagnostics.length, absFiles[i], sw);
      await _scanSingleFileResolved(
        collection,
        absFiles[i],
        registrations,
        visitorRule,
        diagnostics,
      );
    }

    // Clear progress line when using stderr
    if (messageSink == null) {
      io.stderr.write('\r${' ' * 79}\r');
    }
    return diagnostics;
  }

  Future<void> _scanSingleFileResolved(
    AnalysisContextCollection collection,
    String filePath,
    List<_RuleRegistration> registrations,
    Map<AstVisitor<void>, String> visitorRule,
    List<ScanDiagnostic> diagnostics,
  ) async {
    final session = collection.contextFor(filePath).currentSession;
    final result = await session.getResolvedUnit(filePath);
    // A file outside the resolved package, or one whose project lacks
    // `pub get`, resolves to an error result with no usable unit. Skip it with
    // a message rather than crashing or silently dropping it.
    if (result is! ResolvedUnitResult) {
      _err('  Skipping (could not resolve): $filePath');
      return;
    }

    final unit = result.unit;
    final listener = RecordingDiagnosticListener();
    final reporter = DiagnosticReporter(
      listener,
      StringSource(result.content, filePath),
    );
    final ctxUnit = RuleContextUnit(
      file: PhysicalResourceProvider.INSTANCE.getFile(filePath),
      content: result.content,
      diagnosticReporter: reporter,
      unit: unit,
    );

    final allVisitors = <AstVisitor<void>>[];
    for (final reg in registrations) {
      // The factory in runResolved only ever produces ResolvedScanRuleContext,
      // so this cast is safe; updating its resolution results per file is what
      // makes type-based rules see the current file rather than the first one.
      final context = reg.context as ResolvedScanRuleContext;
      context.currentUnit = ctxUnit;
      context.setResolved(
        typeProvider: result.typeProvider,
        typeSystem: result.typeSystem,
        library: result.libraryElement,
      );
      reg.rule.reporter = reporter;
      allVisitors.addAll(reg.visitors);
    }

    if (allVisitors.isNotEmpty) {
      unit.accept(
        ScanWalker(
          allVisitors,
          onError: _onVisitorError(visitorRule, filePath),
        ),
      );
    }

    _collectDiagnostics(listener, unit, filePath, diagnostics);
  }

  /// Converts recorded analyzer diagnostics into [ScanDiagnostic]s, resolving
  /// each offset to a line/column via the unit's line info. Shared by the
  /// syntactic and resolved scan paths.
  void _collectDiagnostics(
    RecordingDiagnosticListener listener,
    CompilationUnit unit,
    String filePath,
    List<ScanDiagnostic> diagnostics,
  ) {
    for (final d in listener.diagnostics) {
      final loc = unit.lineInfo.getLocation(d.offset);
      // End position lets the extension highlight the full diagnostic span
      // instead of a single character (which triggers "find all occurrences").
      final endLoc = unit.lineInfo.getLocation(d.offset + d.length);
      final ruleName = d.diagnosticCode.lowerCaseName;
      diagnostics.add(
        ScanDiagnostic(
          ruleName: ruleName,
          filePath: filePath,
          line: loc.lineNumber,
          column: loc.columnNumber,
          offset: d.offset,
          length: d.length,
          endLine: endLoc.lineNumber,
          endColumn: endLoc.columnNumber,
          severity: d.diagnosticCode.severity.name,
          problemMessage: d.problemMessage.messageText(includeUrl: false),
          // Look up the rule's declared impact; null for non-saropa diagnostics.
          impact: _ruleImpactMap[ruleName],
        ),
      );
    }
  }

  void _showProgress(
    int index,
    int total,
    int issues,
    String filePath,
    Stopwatch sw,
  ) {
    if (index % 10 != 0) return;
    final elapsed = sw.elapsedMilliseconds / 1000;
    final rate = elapsed > 0 ? (index / elapsed).round() : 0;
    final name = p.basename(filePath);
    _progress(
      '\r  Files: $index/$total | ${elapsed.toStringAsFixed(1)}s'
      ' | $rate/s | Issues: $issues | $name${' ' * 20}',
    );
  }

  /// Creates a [RuleContextUnit] for the given file content.
  static RuleContextUnit _createContextUnit(
    String content,
    String filePath, {
    CompilationUnit? unit,
  }) {
    final provider = PhysicalResourceProvider.INSTANCE;
    final file = provider.getFile(filePath);
    final listener = RecordingDiagnosticListener();
    final reporter = DiagnosticReporter(
      listener,
      StringSource(content, filePath),
    );
    return RuleContextUnit(
      file: file,
      content: content,
      diagnosticReporter: reporter,
      unit:
          unit ?? parseString(content: content, throwIfDiagnostics: false).unit,
    );
  }

  /// Public wrapper around [_findDartFiles] for callers that need the
  /// project's discovered file list up front (e.g. the scan daemon's
  /// `listFiles` request, which the IDE baseline scan uses to build chunked
  /// batches before issuing per-chunk resolved scans).
  static List<String> discoverDartFiles(String directory) =>
      _findDartFiles(directory);

  static List<String> _findDartFiles(
    String directory, [
    List<RegExp> excludePatterns = const [],
    List<RegExp> includePatterns = const [],
  ]) {
    final dir = io.Directory(directory);
    if (!dir.existsSync()) return const [];

    return dir
        .listSync(recursive: true)
        .whereType<io.File>()
        .where((f) => f.path.endsWith('.dart'))
        .where((f) => _shouldInclude(f.path, excludePatterns, includePatterns))
        .map((f) => p.normalize(f.path))
        .toList();
  }

  /// Combined exclusion/inclusion check: a file is kept when it passes the
  /// hardcoded exclusions AND user-supplied exclude-globs, OR when it matches
  /// an include-glob (which overrides both). Include wins over exclude so
  /// users can force-scan paths the defaults would skip.
  static bool _shouldInclude(
    String path,
    List<RegExp> excludePatterns,
    List<RegExp> includePatterns,
  ) {
    // Include-globs override all exclusions — check first.
    if (_matchesExcludeGlob(path, includePatterns)) return true;
    // Normal exclusion chain: hardcoded defaults + user-supplied globs.
    if (_isExcluded(path)) return false;
    if (_matchesExcludeGlob(path, excludePatterns)) return false;
    return true;
  }

  /// Paths that are never user code — build artifacts, generated files, and
  /// platform ephemeral directories (symlinked plugin sources the user can't
  /// control). See #313 for the ephemeral/.plugin_symlinks addition.
  static bool _isExcluded(String path) {
    final n = path.replaceAll('\\', '/');
    return n.contains('/.dart_tool/') ||
        n.contains('/build/') ||
        n.contains('/bin/') ||
        n.contains('/example') ||
        n.contains('/ephemeral/') ||
        n.contains('/.plugin_symlinks/') ||
        n.contains('.g.dart') ||
        n.contains('.freezed.dart') ||
        n.contains('.gr.dart') ||
        n.contains('.gen.dart') ||
        n.contains('.mocks.dart') ||
        n.contains('.config.dart') ||
        n.contains('/generated/');
  }

  /// Converts a simple glob pattern to a [RegExp] for path matching.
  ///
  /// Supports `**` (any path segments), `*` (any non-separator chars), and
  /// `?` (single non-separator char). Pattern is matched against the
  /// forward-slash-normalized path.
  static RegExp _globToRegex(String glob) {
    // Normalize Windows backslashes so patterns typed on Windows (e.g.
    // `windows\flutter\ephemeral\**`) match forward-slash-normalized paths.
    final normalized = glob.replaceAll('\\', '/');
    final buf = StringBuffer('^');
    var i = 0;
    while (i < normalized.length) {
      final c = normalized[i];
      if (c == '*') {
        // `**` matches any number of path segments (including separators).
        if (i + 1 < normalized.length && normalized[i + 1] == '*') {
          buf.write('.*');
          i += 2;
          // Skip a trailing slash after `**` so `**/foo` works naturally.
          if (i < normalized.length && normalized[i] == '/') i++;
          continue;
        }
        // Single `*` matches anything except `/`.
        buf.write('[^/]*');
      } else if (c == '?') {
        buf.write('[^/]');
      } else {
        // Escape regex metacharacters in the literal portion.
        buf.write(RegExp.escape(c));
      }
      i++;
    }
    buf.write(r'$');
    return RegExp(buf.toString(), caseSensitive: false);
  }

  /// Returns true if [path] matches any of the compiled [excludePatterns].
  static bool _matchesExcludeGlob(
    String path,
    List<RegExp> excludePatterns,
  ) {
    if (excludePatterns.isEmpty) return false;
    final normalized = path.replaceAll('\\', '/');
    return excludePatterns.any((re) => re.hasMatch(normalized));
  }
}

class _RuleRegistration {
  const _RuleRegistration(this.rule, this.visitors, this.context);
  final SaropaLintRule rule;
  final List<AstVisitor<void>> visitors;

  /// The shared context for this rule. [ScanRuleContext] for the syntactic
  /// scan, [ResolvedScanRuleContext] for `--resolve`; both are
  /// [MutableRuleContext] so the runner can update [currentUnit] per file.
  final MutableRuleContext context;
}
